use_frameworks!
platform :ios, '9.0'

target 'nRFBlinky' do
  pod 'CoreBluetoothMock', :path => '../'

  target 'nRFBlinky_Tests' do
    inherit! :search_paths
  end

  target 'nRFBlinky_UITests'
end
