platform :ios, '8.0'

target 'nRFBlinky' do
  use_frameworks!
  pod 'CoreBluetoothMock', :path => '../'

  target 'nRFBlinky_Tests' do
    inherit! :search_paths
  end

  target 'nRFBlinky_UITests'
end
