{"defaultImplementationsSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didDiscoverIncludedServicesFor:error:)-g4lr"],"anchor":"CBMPeripheralDelegate-Implementations","title":"CBMPeripheralDelegate Implementations"}],"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmperipheraldelegate\/peripheral(_:diddiscoverincludedservicesfor:error:)-6b62q"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate"]]},"abstract":[{"text":"This method returns the result of a ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/discoverIncludedServices(_:for:)","isActive":true},{"type":"text","text":" call."},{"text":" ","type":"text"},{"text":"If the included service(s) were read successfully, they can be retrieved via service’s","type":"text"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService\/includedServices"},{"type":"text","text":" property."}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didDiscoverIncludedServicesFor:error:)-6b62q","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheral"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"peripheral","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CBMPeripheral","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDiscoverIncludedServicesFor"},{"kind":"text","text":" "},{"text":"service","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService","text":"CBMService","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The peripheral providing this information."}],"type":"paragraph"}],"name":"peripheral"},{"name":"service","content":[{"inlineContent":[{"type":"text","text":"The "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService","type":"reference"},{"type":"text","text":" object containing the included services."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"If an error occurred, the cause of the failure."}],"type":"paragraph"}],"name":"error"}],"kind":"parameters"}],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","kind":"typeIdentifier","text":"CBMPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDiscoverIncludedServicesFor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService","text":"CBMService","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?)","kind":"text"}],"required":true,"role":"symbol","externalID":"s:17CoreBluetoothMock21CBMPeripheralDelegateP10peripheral_30didDiscoverIncludedServicesFor5erroryAA0D0_p_AA10CBMServiceCs5Error_pSgtF","modules":[{"name":"CoreBluetoothMock"}],"title":"peripheral(_:didDiscoverIncludedServicesFor:error:)","symbolKind":"method"},"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegate":{"type":"topic","title":"CBMPeripheralDelegate","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CBMPeripheralDelegate","kind":"identifier"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegate","abstract":[{"type":"text","text":"A protocol that provides updates on the use of a peripheral’s services."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralDelegate"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMService/includedServices":{"abstract":[{"type":"text","text":"A list of included services that have so far been discovered in this service."}],"title":"includedServices","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"includedServices","kind":"identifier"},{"text":": [","kind":"text"},{"text":"CBMService","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService"},{"text":"]?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService\/includedServices","url":"\/documentation\/corebluetoothmock\/cbmservice\/includedservices","type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral/discoverIncludedServices(_:for:)":{"abstract":[{"text":"Discovers the specified included services of a previously-discovered service.","type":"text"}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheral\/discoverincludedservices(_:for:)","required":true,"kind":"symbol","title":"discoverIncludedServices(_:for:)","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/discoverIncludedServices(_:for:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"discoverIncludedServices","kind":"identifier"},{"text":"([","kind":"text"},{"text":"CBMUUID","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CBMService","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService"},{"text":")","kind":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMService":{"abstract":[{"text":"A collection of data and associated behaviors that accomplish a function or feature of a device.","type":"text"}],"kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmservice","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMService","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMService"}],"title":"CBMService","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegate/peripheral(_:didDiscoverIncludedServicesFor:error:)-6b62q":{"abstract":[{"type":"text","text":"This method returns the result of a "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/discoverIncludedServices(_:for:)","isActive":true},{"text":" call.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If the included service(s) were read successfully, they can be retrieved via service’s"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService\/includedServices","isActive":true},{"text":" property.","type":"text"}],"title":"peripheral(_:didDiscoverIncludedServicesFor:error:)","kind":"symbol","role":"symbol","defaultImplementations":1,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didDiscoverIncludedServicesFor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService","text":"CBMService"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"required":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didDiscoverIncludedServicesFor:error:)-6b62q","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegate\/peripheral(_:diddiscoverincludedservicesfor:error:)-6b62q","type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegate/peripheral(_:didDiscoverIncludedServicesFor:error:)-g4lr":{"abstract":[{"text":"This method returns the result of a ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/discoverIncludedServices(_:for:)","isActive":true},{"type":"text","text":" call."},{"type":"text","text":" "},{"text":"If the included service(s) were read successfully, they can be retrieved via service’s","type":"text"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService\/includedServices"},{"type":"text","text":" property."}],"url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegate\/peripheral(_:diddiscoverincludedservicesfor:error:)-g4lr","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheral"},{"kind":"text","text":"("},{"preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","text":"CBMPeripheral","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didDiscoverIncludedServicesFor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService","text":"CBMService"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didDiscoverIncludedServicesFor:error:)-g4lr","title":"peripheral(_:didDiscoverIncludedServicesFor:error:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/title","value":"CBMService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/fragments","value":[{"kind":"identifier","text":"CBMService"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/navigatorTitle","value":[{"text":"CBMService","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}