{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate"]]},"abstract":[{"type":"text","text":"This method returns the result of a "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/setNotifyValue(_:for:)","isActive":true},{"text":" call.","type":"text"}],"defaultImplementationsSections":[{"anchor":"CBMPeripheralDelegate-Implementations","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didUpdateNotificationStateFor:error:)-5tl1y"],"title":"CBMPeripheralDelegate Implementations"}],"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmperipheraldelegate\/peripheral(_:didupdatenotificationstatefor:error:)-9ryr0"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didUpdateNotificationStateFor:error:)-9ryr0","interfaceLanguage":"swift"},"metadata":{"title":"peripheral(_:didUpdateNotificationStateFor:error:)","modules":[{"name":"CoreBluetoothMock"}],"externalID":"s:17CoreBluetoothMock21CBMPeripheralDelegateP10peripheral_29didUpdateNotificationStateFor5erroryAA0D0_p_AA17CBMCharacteristicCs5Error_pSgtF","role":"symbol","symbolKind":"method","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheral"},{"kind":"text","text":"("},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"kind":"text","text":", "},{"text":"didUpdateNotificationStateFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBMCharacteristic","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"roleHeading":"Instance Method"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"peripheral"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","text":"CBMPeripheral","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral"},{"text":", ","kind":"text"},{"text":"didUpdateNotificationStateFor","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"characteristic","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic","text":"CBMCharacteristic"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The peripheral providing this information."}]}],"name":"peripheral"},{"content":[{"inlineContent":[{"type":"text","text":"A "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic"},{"type":"text","text":" object."}],"type":"paragraph"}],"name":"characteristic"},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"If an error occurred, the cause of the failure."}],"type":"paragraph"}]}]}],"sections":[],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegate/peripheral(_:didUpdateNotificationStateFor:error:)-5tl1y":{"url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegate\/peripheral(_:didupdatenotificationstatefor:error:)-5tl1y","abstract":[{"text":"This method returns the result of a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/setNotifyValue(_:for:)"},{"text":" call.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didUpdateNotificationStateFor:error:)-5tl1y","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"kind":"text","text":", "},{"text":"didUpdateNotificationStateFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBMCharacteristic","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"title":"peripheral(_:didUpdateNotificationStateFor:error:)","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegate/peripheral(_:didUpdateNotificationStateFor:error:)-9ryr0":{"defaultImplementations":1,"title":"peripheral(_:didUpdateNotificationStateFor:error:)","type":"topic","abstract":[{"text":"This method returns the result of a ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/setNotifyValue(_:for:)","isActive":true},{"type":"text","text":" call."}],"url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegate\/peripheral(_:didupdatenotificationstatefor:error:)-9ryr0","role":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didUpdateNotificationStateFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBMCharacteristic","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didUpdateNotificationStateFor:error:)-9ryr0"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral/setNotifyValue(_:for:)":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/setNotifyValue(_:for:)","type":"topic","role":"symbol","abstract":[{"text":"Sets notifications or indications for the value of a specified characteristic.","type":"text"}],"required":true,"title":"setNotifyValue(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setNotifyValue","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic","text":"CBMCharacteristic","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheral\/setnotifyvalue(_:for:)","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegate":{"type":"topic","title":"CBMPeripheralDelegate","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CBMPeripheralDelegate","kind":"identifier"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegate","abstract":[{"type":"text","text":"A protocol that provides updates on the use of a peripheral’s services."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralDelegate"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristic":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMCharacteristic"}],"title":"CBMCharacteristic","type":"topic","abstract":[{"text":"A characteristic of a remote peripheral’s service.","type":"text"}],"navigatorTitle":[{"text":"CBMCharacteristic","kind":"identifier"}],"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcharacteristic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/title","value":"CBMCharacteristic","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/fragments","value":[{"kind":"identifier","text":"CBMCharacteristic"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/navigatorTitle","value":[{"text":"CBMCharacteristic","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}