{"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/corebluetoothmock"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/corebluetoothmock"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Test "},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"metadata":{"roleHeading":"Framework","modules":[{"name":"CoreBluetoothMock"}],"externalID":"CoreBluetoothMock","symbolKind":"module","role":"collection","title":"CoreBluetoothMock"},"hierarchy":{"paths":[[]]},"sections":[],"primaryContentSections":[{"content":[{"level":2,"type":"heading","anchor":"Overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"inlineContent":[{"text":"CoreBluetoothMock","type":"text"}],"type":"strong"},{"type":"text","text":" library provides an intuitive API for mocking physical"},{"text":" ","type":"text"},{"text":"Bluetooth LE devices using an implementation in Swift. This allows:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Testing Bluetooth LE connectivity on a simulator,","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Simulating a Bluetooth LE device during the development phase,","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Reliable method for automating tests and taking screenshots."}],"type":"paragraph"}]}],"type":"unorderedList"},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Current version supports testing only central manager features."},{"text":" ","type":"text"},{"type":"text","text":"The peripheral manager functionality is planned."}]}]}],"kind":"content"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"How to migrate a project to CoreBluetooth Mock framework","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/Migration-guide"],"anchor":"How-to-migrate-a-project-to-CoreBluetooth-Mock-framework"},{"title":"How to create mock peripherals","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/Mocking-peripherals"],"anchor":"How-to-create-mock-peripherals"},{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/Simulation"],"title":"How to simulate test events","anchor":"How-to-simulate-test-events"},{"title":"Known issues","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/KnownIssues"],"anchor":"Known-issues"},{"abstract":[{"text":"The following objects can be used to create mock implementation of Bluetooth LE","type":"text"},{"text":" ","type":"text"},{"text":"devices. Such mock peripherals will be available using ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock","isActive":true},{"type":"text","text":"."}],"title":"Mocking Bluetooth LE Devices","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMProximity","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAdvertisementConfig"],"anchor":"Mocking-Bluetooth-LE-Devices"},{"anchor":"Central-Manager","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerFactory","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerState","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerAuthorization"],"title":"Central Manager"},{"title":"Central Manager Initialization Options","anchor":"Central-Manager-Initialization-Options","abstract":[{"type":"text","text":"Keys used to pass options when initializing a central manager."}],"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerOptionRestoreIdentifierKey","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerOptionShowPowerAlertKey"]},{"anchor":"Central-Manager-State-Restoration-Options","abstract":[{"type":"text","text":"Keys used to pass state restoration options to the central manager initializer."}],"title":"Central Manager State Restoration Options","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerRestoredStatePeripheralsKey","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerRestoredStateScanServicesKey","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerRestoredStateScanOptionsKey"]},{"anchor":"Peripheral","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeer","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxyWithL2CAPChannel","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralPreview","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralState","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBML2CAPPSM","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBML2CAPChannel"],"title":"Peripheral"},{"abstract":[{"text":"Keys used to pass options when connecting to a peripheral.","type":"text"}],"title":"Peripheral Connection Options","anchor":"Peripheral-Connection-Options","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionEnableAutoReconnect","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionNotifyOnConnectionKey","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionNotifyOnDisconnectionKey","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionNotifyOnNotificationKey","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionEnableTransportBridgingKey","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionRequiresANCS","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionStartDelayKey"]},{"title":"Attributes","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAttribute","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicWriteType","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicProperties","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptorMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMClientCharacteristicConfigurationDescriptorMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCCCDescriptorMock"],"anchor":"Attributes"},{"anchor":"Scanning-options","title":"Scanning options","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerScanOptionAllowDuplicatesKey","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerScanOptionSolicitedServiceUUIDsKey"],"abstract":[{"type":"text","text":"Keys used to pass options when scanning for peripherals."}]},{"title":"Advertisement Data Retrieval Keys","anchor":"Advertisement-Data-Retrieval-Keys","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAdvertisementDataLocalNameKey","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAdvertisementDataManufacturerDataKey","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAdvertisementDataServiceDataKey","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAdvertisementDataServiceUUIDsKey","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAdvertisementDataOverflowServiceUUIDsKey","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAdvertisementDataTxPowerLevelKey","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAdvertisementDataIsConnectable","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAdvertisementDataSolicitedServiceUUIDsKey"],"abstract":[{"type":"text","text":"Keys used to specify items in a dictionary of peripheral advertisement data."}]},{"anchor":"Other","title":"Other","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMError","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMATTError"]}],"kind":"symbol","references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMDescriptorMock":{"type":"topic","abstract":[{"text":"Mock implementation of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptorMock","role":"symbol","title":"CBMDescriptorMock","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMDescriptorMock","kind":"identifier"}],"navigatorTitle":[{"text":"CBMDescriptorMock","kind":"identifier"}],"url":"\/documentation\/corebluetoothmock\/cbmdescriptormock"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralPreview":{"url":"\/documentation\/corebluetoothmock\/cbmperipheralpreview","title":"CBMPeripheralPreview","abstract":[{"text":"A stub ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","isActive":true},{"text":" implementation designed only for SwiftUI Previews.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPeripheralPreview","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralPreview","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralPreview"}],"role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate":{"navigatorTitle":[{"text":"CBMPeripheralSpecDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"This delegate should implement the behavior of a real Bluetooth LE device during a connection."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheralSpecDelegate","kind":"identifier"}],"title":"CBMPeripheralSpecDelegate","type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate","url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CoreBluetoothMockVersionString":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CoreBluetoothMockVersionString","fragments":[{"text":"CoreBluetoothMockVersionString","kind":"identifier"}],"type":"topic","title":"CoreBluetoothMockVersionString","url":"\/documentation\/corebluetoothmock\/corebluetoothmockversionstring","kind":"symbol","role":"symbol","abstract":[]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMService":{"abstract":[{"text":"A collection of data and associated behaviors that accomplish a function or feature of a device.","type":"text"}],"kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmservice","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMService","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMService"}],"title":"CBMService","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMClientCharacteristicConfigurationDescriptorMock":{"url":"\/documentation\/corebluetoothmock\/cbmclientcharacteristicconfigurationdescriptormock","abstract":[{"text":"A mock implementation of Client Characteristic Configuration descriptor (CCCD).","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMClientCharacteristicConfigurationDescriptorMock","title":"CBMClientCharacteristicConfigurationDescriptorMock","kind":"symbol","navigatorTitle":[{"text":"CBMClientCharacteristicConfigurationDescriptorMock","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMClientCharacteristicConfigurationDescriptorMock"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeer":{"navigatorTitle":[{"text":"CBMPeer","kind":"identifier"}],"url":"\/documentation\/corebluetoothmock\/cbmpeer","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPeer","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that represents a remote device."}],"title":"CBMPeer","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeer"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerOptionRestoreIdentifierKey":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerOptionRestoreIdentifierKey","role":"symbol","abstract":[{"type":"text","text":"A string containing a unique identifier (UID) for the central manager to instantiate."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMCentralManagerOptionRestoreIdentifierKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanageroptionrestoreidentifierkey","type":"topic","title":"CBMCentralManagerOptionRestoreIdentifierKey"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/Migration-guide":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/Migration-guide","abstract":[{"text":"Migration guide from ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" to ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetoothFramework"}]},{"text":".","type":"text"}],"role":"article","url":"\/documentation\/corebluetoothmock\/migration-guide","title":"Migration guide","type":"topic","kind":"article"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralMock":{"abstract":[{"type":"text","text":"Mock implementation of the "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","isActive":true},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralmock","kind":"symbol","title":"CBMPeripheralMock","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock","navigatorTitle":[{"text":"CBMPeripheralMock","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMPeripheralMock"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristicMock":{"url":"\/documentation\/corebluetoothmock\/cbmcharacteristicmock","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CBMCharacteristicMock","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMCharacteristicMock"}],"abstract":[{"type":"text","text":"Mock implementation of "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic","type":"reference","isActive":true},{"type":"text","text":"."}],"title":"CBMCharacteristicMock","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicMock","type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerRestoredStateScanServicesKey":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerRestoredStateScanServicesKey","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"CBMCentralManagerRestoredStateScanServicesKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerrestoredstatescanserviceskey","abstract":[{"text":"An array of service IDs for use when restoring state.","type":"text"}],"title":"CBMCentralManagerRestoredStateScanServicesKey","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMConnectPeripheralOptionNotifyOnDisconnectionKey":{"type":"topic","abstract":[{"text":"A Boolean value that specifies whether the system should display an alert when","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"disconnecting a peripheral in the background."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionNotifyOnDisconnectionKey","role":"symbol","title":"CBMConnectPeripheralOptionNotifyOnDisconnectionKey","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMConnectPeripheralOptionNotifyOnDisconnectionKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/corebluetoothmock\/cbmconnectperipheraloptionnotifyondisconnectionkey"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMManagerState":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerState","navigatorTitle":[{"text":"CBMManagerState","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The possible states of a Core Bluetooth manager."}],"title":"CBMManagerState","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMManagerState","kind":"identifier"}],"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmmanagerstate"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative":{"abstract":[{"type":"text","text":"A native implementation of "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","type":"reference"},{"text":" that will proxy all requests to an underlying ","type":"text"},{"code":"CBPeripheral","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMPeripheralNative","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralNative"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative","type":"topic","title":"CBMPeripheralNative","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/Simulation":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/Simulation","abstract":[{"text":"Set of methods for simulating various Bluetooth LE events.","type":"text"}],"role":"article","title":"Simulation","url":"\/documentation\/corebluetoothmock\/simulation","type":"topic","kind":"article"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristic":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMCharacteristic"}],"title":"CBMCharacteristic","type":"topic","abstract":[{"text":"A characteristic of a remote peripheral’s service.","type":"text"}],"navigatorTitle":[{"text":"CBMCharacteristic","kind":"identifier"}],"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcharacteristic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerMock":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManagerMock"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagermock","abstract":[{"text":"Mock implementation of the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager"},{"type":"text","text":"."}],"title":"CBMCentralManagerMock","kind":"symbol","navigatorTitle":[{"text":"CBMCentralManagerMock","kind":"identifier"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMAdvertisementDataOverflowServiceUUIDsKey":{"abstract":[{"text":"An array of UUIDs found in the overflow area of the advertisement data.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"CBMAdvertisementDataOverflowServiceUUIDsKey","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAdvertisementDataOverflowServiceUUIDsKey","url":"\/documentation\/corebluetoothmock\/cbmadvertisementdataoverflowserviceuuidskey","type":"topic","title":"CBMAdvertisementDataOverflowServiceUUIDsKey","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMConnectPeripheralOptionStartDelayKey":{"type":"topic","abstract":[{"text":"An option that indicates a delay before the system makes a connection.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionStartDelayKey","role":"symbol","title":"CBMConnectPeripheralOptionStartDelayKey","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"CBMConnectPeripheralOptionStartDelayKey","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/corebluetoothmock\/cbmconnectperipheraloptionstartdelaykey"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMError":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMError","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMError","kind":"identifier"}],"abstract":[{"text":"An error that Core Bluetooth returns during Bluetooth transactions.","type":"text"}],"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmerror","title":"CBMError","navigatorTitle":[{"kind":"identifier","text":"CBMError"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMProximity":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMProximity","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMProximity","kind":"identifier"}],"url":"\/documentation\/corebluetoothmock\/cbmproximity","abstract":[{"type":"text","text":"The approximate mock device proximity."}],"title":"CBMProximity","kind":"symbol","navigatorTitle":[{"text":"CBMProximity","kind":"identifier"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegateProxy":{"abstract":[{"type":"text","text":"A helper class that allows setting delegate callbacks as closures."}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegateproxy","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy","title":"CBMCentralManagerDelegateProxy","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMCentralManagerDelegateProxy","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManagerDelegateProxy"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManager"}],"title":"CBMCentralManager","abstract":[{"type":"text","text":"An object that scans for, discovers, connects to, and manages peripherals."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManager"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerScanOptionAllowDuplicatesKey":{"title":"CBMCentralManagerScanOptionAllowDuplicatesKey","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerscanoptionallowduplicateskey","abstract":[{"text":"A Boolean value that specifies whether the scan should run without duplicate filtering.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerScanOptionAllowDuplicatesKey","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"CBMCentralManagerScanOptionAllowDuplicatesKey","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralState":{"url":"\/documentation\/corebluetoothmock\/cbmperipheralstate","title":"CBMPeripheralState","abstract":[{"type":"text","text":"Values representing the connection state of a peripheral."}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPeripheralState","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralState","navigatorTitle":[{"text":"CBMPeripheralState","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMAdvertisementDataTxPowerLevelKey":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMAdvertisementDataTxPowerLevelKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmadvertisementdatatxpowerlevelkey","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAdvertisementDataTxPowerLevelKey","title":"CBMAdvertisementDataTxPowerLevelKey","role":"symbol","abstract":[{"text":"The transmit power of a peripheral.","type":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristicProperties":{"url":"\/documentation\/corebluetoothmock\/cbmcharacteristicproperties","abstract":[{"text":"Values that represent the possible properties of a characteristic.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicProperties","kind":"symbol","title":"CBMCharacteristicProperties","navigatorTitle":[{"kind":"identifier","text":"CBMCharacteristicProperties"}],"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"CBMCharacteristicProperties","kind":"identifier"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristicWriteType":{"title":"CBMCharacteristicWriteType","url":"\/documentation\/corebluetoothmock\/cbmcharacteristicwritetype","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicWriteType","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCharacteristicWriteType"}],"abstract":[{"type":"text","text":"Values representing the possible write types to a characteristic’s value."}],"navigatorTitle":[{"kind":"identifier","text":"CBMCharacteristicWriteType"}],"kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegateProxyWithL2CAPChannel":{"navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralDelegateProxyWithL2CAPChannel"}],"kind":"symbol","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxywithl2capchannel","abstract":[{"text":"A helper class that allows setting delegate callbacks as closures.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPeripheralDelegateProxyWithL2CAPChannel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxyWithL2CAPChannel","title":"CBMPeripheralDelegateProxyWithL2CAPChannel","type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMAdvertisementDataLocalNameKey":{"abstract":[{"text":"The local name of a peripheral.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"CBMAdvertisementDataLocalNameKey","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAdvertisementDataLocalNameKey","url":"\/documentation\/corebluetoothmock\/cbmadvertisementdatalocalnamekey","type":"topic","title":"CBMAdvertisementDataLocalNameKey","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/Mocking-peripherals":{"title":"Mocking Bluetooth LE Devices","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/Mocking-peripherals","role":"article","abstract":[{"text":"How to create mock peripherals to be used in tests.","type":"text"}],"type":"topic","kind":"article","url":"\/documentation\/corebluetoothmock\/mocking-peripherals"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMAdvertisementDataSolicitedServiceUUIDsKey":{"abstract":[{"text":"An array of solicited service UUIDs.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"CBMAdvertisementDataSolicitedServiceUUIDsKey","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAdvertisementDataSolicitedServiceUUIDsKey","url":"\/documentation\/corebluetoothmock\/cbmadvertisementdatasolicitedserviceuuidskey","type":"topic","title":"CBMAdvertisementDataSolicitedServiceUUIDsKey","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMConnectPeripheralOptionNotifyOnConnectionKey":{"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmconnectperipheraloptionnotifyonconnectionkey","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMConnectPeripheralOptionNotifyOnConnectionKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionNotifyOnConnectionKey","role":"symbol","abstract":[{"text":"A Boolean value that specifies whether the system should display an alert when","type":"text"},{"text":" ","type":"text"},{"text":"connecting a peripheral in the background.","type":"text"}],"title":"CBMConnectPeripheralOptionNotifyOnConnectionKey"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMConnectPeripheralOptionEnableAutoReconnect":{"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmconnectperipheraloptionenableautoreconnect","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMConnectPeripheralOptionEnableAutoReconnect"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionEnableAutoReconnect","role":"symbol","abstract":[{"text":"An Boolean indicating that the AutoReconnect is enabled for the peripheral is connected.","type":"text"}],"title":"CBMConnectPeripheralOptionEnableAutoReconnect"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMUUID":{"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMUUID"}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmuuid","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID","title":"CBMUUID","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMUUID"}],"abstract":[{"text":"A universally unique identifier, as defined by Bluetooth standards.","type":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMAdvertisementDataIsConnectable":{"abstract":[{"text":"A Boolean value that indicates whether the advertising event type is connectable.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMAdvertisementDataIsConnectable"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAdvertisementDataIsConnectable","url":"\/documentation\/corebluetoothmock\/cbmadvertisementdataisconnectable","type":"topic","title":"CBMAdvertisementDataIsConnectable","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/KnownIssues":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/KnownIssues","kind":"article","role":"article","abstract":[{"text":"Known issues when using ","type":"text"},{"type":"strong","inlineContent":[{"text":"CoreBluetoothMock","type":"text"}]},{"type":"text","text":" framework instead of native "},{"type":"strong","inlineContent":[{"text":"CoreBluetooth","type":"text"}]},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/corebluetoothmock\/knownissues","title":"Known issues"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMAttribute":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAttribute","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMAttribute","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBMAttribute"}],"title":"CBMAttribute","url":"\/documentation\/corebluetoothmock\/cbmattribute","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A representation of common aspects of services offered by a peripheral."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMATTError":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMATTError"}],"navigatorTitle":[{"text":"CBMATTError","kind":"identifier"}],"title":"CBMATTError","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMATTError","role":"symbol","abstract":[{"type":"text","text":"An error that Core Bluetooth returns while using Attribute Protocol (ATT)."}],"type":"topic","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmatterror"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMConnectPeripheralOptionNotifyOnNotificationKey":{"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmconnectperipheraloptionnotifyonnotificationkey","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMConnectPeripheralOptionNotifyOnNotificationKey"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionNotifyOnNotificationKey","role":"symbol","abstract":[{"type":"text","text":"A Boolean value that specifies whether the system should display an alert for any"},{"type":"text","text":" "},{"text":"notification sent by a peripheral.","type":"text"}],"title":"CBMConnectPeripheralOptionNotifyOnNotificationKey"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerOptionShowPowerAlertKey":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMCentralManagerOptionShowPowerAlertKey"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"CBMCentralManagerOptionShowPowerAlertKey","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerOptionShowPowerAlertKey","abstract":[{"type":"text","text":"A Boolean value that specifies whether the system warns the user if the app instantiates"},{"type":"text","text":" "},{"type":"text","text":"the central manager when Bluetooth service isn’t available."}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanageroptionshowpoweralertkey"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec":{"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralspec","navigatorTitle":[{"text":"CBMPeripheralSpec","kind":"identifier"}],"title":"CBMPeripheralSpec","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPeripheralSpec","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Specification of a mock peripheral."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerRestoredStatePeripheralsKey":{"title":"CBMCentralManagerRestoredStatePeripheralsKey","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerRestoredStatePeripheralsKey","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMCentralManagerRestoredStatePeripheralsKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerrestoredstateperipheralskey","abstract":[{"type":"text","text":"An array of peripherals for use when restoring the state of a central manager."}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMAdvertisementDataServiceDataKey":{"abstract":[{"type":"text","text":"A dictionary that contains service-specific advertisement data."}],"kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmadvertisementdataservicedatakey","role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMAdvertisementDataServiceDataKey","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"CBMAdvertisementDataServiceDataKey","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAdvertisementDataServiceDataKey"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMAdvertisementConfig":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMAdvertisementConfig"}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmadvertisementconfig","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAdvertisementConfig","title":"CBMAdvertisementConfig","role":"symbol","navigatorTitle":[{"text":"CBMAdvertisementConfig","kind":"identifier"}],"abstract":[{"text":"Advertisement configuration.","type":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMConnectPeripheralOptionRequiresANCS":{"type":"topic","abstract":[{"text":"An option to require Apple Notification Center Service (ANCS) when connecting a device.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionRequiresANCS","role":"symbol","title":"CBMConnectPeripheralOptionRequiresANCS","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMConnectPeripheralOptionRequiresANCS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/corebluetoothmock\/cbmconnectperipheraloptionrequiresancs"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMDescriptor":{"role":"symbol","title":"CBMDescriptor","abstract":[{"text":"An object that provides further information about a remote peripheral’s characteristic.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmdescriptor","navigatorTitle":[{"kind":"identifier","text":"CBMDescriptor"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMDescriptor","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegate":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManagerDelegate"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate","navigatorTitle":[{"text":"CBMCentralManagerDelegate","kind":"identifier"}],"title":"CBMCentralManagerDelegate","kind":"symbol","abstract":[{"type":"text","text":"A protocol that provides updates for the discovery and management of peripheral devices."}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative":{"kind":"symbol","abstract":[{"type":"text","text":"An implementation  of "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"reference","isActive":true},{"type":"text","text":" that will proxy all the requests and responses"},{"text":" ","type":"text"},{"type":"text","text":"to the native "},{"type":"codeVoice","code":"CBCentralManager"},{"text":" object.","type":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative","title":"CBMCentralManagerNative","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMCentralManagerNative","kind":"identifier"}],"navigatorTitle":[{"text":"CBMCentralManagerNative","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerScanOptionSolicitedServiceUUIDsKey":{"title":"CBMCentralManagerScanOptionSolicitedServiceUUIDsKey","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerScanOptionSolicitedServiceUUIDsKey","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"CBMCentralManagerScanOptionSolicitedServiceUUIDsKey","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"text":"An array of service UUIDs that you want to scan for.","type":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerscanoptionsolicitedserviceuuidskey","type":"topic","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCCCDescriptorMock":{"url":"\/documentation\/corebluetoothmock\/cbmcccdescriptormock","abstract":[{"text":"A type alias of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMClientCharacteristicConfigurationDescriptorMock"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCCCDescriptorMock","title":"CBMCCCDescriptorMock","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMCCCDescriptorMock"}],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMCCCDescriptorMock"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMManagerAuthorization":{"title":"CBMManagerAuthorization","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerAuthorization","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMManagerAuthorization","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMManagerAuthorization"}],"url":"\/documentation\/corebluetoothmock\/cbmmanagerauthorization","abstract":[{"text":"The current authorization state of a Core Bluetooth manager.","type":"text"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMConnectPeripheralOptionEnableTransportBridgingKey":{"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmconnectperipheraloptionenabletransportbridgingkey","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMConnectPeripheralOptionEnableTransportBridgingKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionEnableTransportBridgingKey","role":"symbol","abstract":[{"type":"text","text":"A Boolean value that specifies whether the system should to connect non-GATT profiles"},{"text":" ","type":"text"},{"text":"on classic Bluetooth devices, if there is a low energy GATT connection to the same device.","type":"text"}],"title":"CBMConnectPeripheralOptionEnableTransportBridgingKey"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegate":{"type":"topic","title":"CBMPeripheralDelegate","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CBMPeripheralDelegate","kind":"identifier"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegate","abstract":[{"type":"text","text":"A protocol that provides updates on the use of a peripheral’s services."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralDelegate"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMAdvertisementDataServiceUUIDsKey":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMAdvertisementDataServiceUUIDsKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmadvertisementdataserviceuuidskey","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAdvertisementDataServiceUUIDsKey","title":"CBMAdvertisementDataServiceUUIDsKey","role":"symbol","abstract":[{"text":"An array of service UUIDs.","type":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerFactory":{"kind":"symbol","abstract":[{"text":"The factory that instantiates the ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","isActive":true,"type":"reference"},{"text":" object.","type":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerfactory","title":"CBMCentralManagerFactory","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMCentralManagerFactory","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMCentralManagerFactory"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerFactory","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMServiceMock":{"type":"topic","abstract":[{"type":"text","text":"Mock implementation of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock","role":"symbol","title":"CBMServiceMock","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMServiceMock"}],"navigatorTitle":[{"kind":"identifier","text":"CBMServiceMock"}],"url":"\/documentation\/corebluetoothmock\/cbmservicemock"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBML2CAPChannel":{"navigatorTitle":[{"kind":"identifier","text":"CBML2CAPChannel"}],"url":"\/documentation\/corebluetoothmock\/cbml2capchannel","kind":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBML2CAPChannel","kind":"identifier"}],"abstract":[{"text":"A live L2CAP connection to a remote device.","type":"text"}],"title":"CBML2CAPChannel","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBML2CAPChannel"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerRestoredStateScanOptionsKey":{"abstract":[{"type":"text","text":"A dictionary of peripheral scan options for use when restoring state."}],"title":"CBMCentralManagerRestoredStateScanOptionsKey","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerrestoredstatescanoptionskey","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManagerRestoredStateScanOptionsKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerRestoredStateScanOptionsKey"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegateProxy":{"title":"CBMPeripheralDelegateProxy","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy","kind":"symbol","abstract":[{"type":"text","text":"A helper class that allows setting delegate callbacks as closures."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}],"type":"topic","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxy","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMAdvertisementDataManufacturerDataKey":{"type":"topic","kind":"symbol","title":"CBMAdvertisementDataManufacturerDataKey","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmadvertisementdatamanufacturerdatakey","abstract":[{"text":"The manufacturer data of a peripheral.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMAdvertisementDataManufacturerDataKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAdvertisementDataManufacturerDataKey"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBML2CAPPSM":{"url":"\/documentation\/corebluetoothmock\/cbml2cappsm","title":"CBML2CAPPSM","abstract":[{"type":"text","text":"The type of PSM identifiers."}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBML2CAPPSM","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBML2CAPPSM","navigatorTitle":[{"kind":"identifier","text":"CBML2CAPPSM"}],"role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CoreBluetoothMockVersionNumber":{"kind":"symbol","abstract":[],"url":"\/documentation\/corebluetoothmock\/corebluetoothmockversionnumber","title":"CoreBluetoothMockVersionNumber","type":"topic","fragments":[{"kind":"identifier","text":"CoreBluetoothMockVersionNumber"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CoreBluetoothMockVersionNumber","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/Migration-guide"],"anchor":"How-to-migrate-a-project-to-CoreBluetooth-Mock-framework","title":"How to migrate a project to CoreBluetooth Mock framework"},{"title":"How to create mock peripherals","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/Mocking-peripherals"],"anchor":"How-to-create-mock-peripherals"},{"title":"How to simulate test events","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/Simulation"],"anchor":"How-to-simulate-test-events"},{"anchor":"Known-issues","title":"Known issues","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/KnownIssues"]},{"anchor":"Central-Manager","title":"Central Manager","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative"]},{"anchor":"Peripheral","title":"Peripheral","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeer","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxyWithL2CAPChannel","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralPreview"]},{"anchor":"Attributes","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAttribute","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptorMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMClientCharacteristicConfigurationDescriptorMock"],"title":"Attributes"},{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CoreBluetoothMockVersionNumber","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CoreBluetoothMockVersionString"],"title":"Variables","anchor":"Variables","generated":true}],"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptorMock\/title","value":"CBMDescriptorMock"},{"op":"replace","value":[{"kind":"identifier","text":"CBMDescriptorMock"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptorMock\/fragments"},{"value":[{"kind":"identifier","text":"CBMDescriptorMock"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptorMock\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralPreview\/title","value":"CBMPeripheralPreview"},{"value":[{"kind":"identifier","text":"CBMPeripheralPreview"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralPreview\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralPreview\/navigatorTitle","value":[{"text":"CBMPeripheralPreview","kind":"identifier"}]},{"value":"CBMService","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/fragments","value":[{"text":"CBMService","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBMService"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMClientCharacteristicConfigurationDescriptorMock\/title","value":"CBMClientCharacteristicConfigurationDescriptorMock"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMClientCharacteristicConfigurationDescriptorMock\/fragments","value":[{"kind":"identifier","text":"CBMClientCharacteristicConfigurationDescriptorMock"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMClientCharacteristicConfigurationDescriptorMock\/navigatorTitle","value":[{"text":"CBMClientCharacteristicConfigurationDescriptorMock","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeer\/title","value":"CBMPeer"},{"op":"replace","value":[{"kind":"identifier","text":"CBMPeer"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeer\/fragments"},{"op":"replace","value":[{"text":"CBMPeer","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeer\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock\/title","op":"replace","value":"CBMPeripheralMock"},{"value":[{"text":"CBMPeripheralMock","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock\/fragments"},{"op":"replace","value":[{"text":"CBMPeripheralMock","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristicMock\/title","value":"CBMCharacteristicMock","op":"replace"},{"value":[{"text":"CBMCharacteristicMock","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristicMock\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristicMock\/navigatorTitle","op":"replace","value":[{"text":"CBMCharacteristicMock","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative\/title","value":"CBMPeripheralNative"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMPeripheralNative"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBMPeripheralNative"}]},{"op":"replace","value":"CBMCharacteristic","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/fragments","value":[{"text":"CBMCharacteristic","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/navigatorTitle","value":[{"kind":"identifier","text":"CBMCharacteristic"}],"op":"replace"},{"value":"CBMCentralManagerMock","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerMock\/title","op":"replace"},{"value":[{"text":"CBMCentralManagerMock","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerMock\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerMock\/navigatorTitle","value":[{"text":"CBMCentralManagerMock","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerDelegateProxy\/title","value":"CBMCentralManagerDelegateProxy"},{"value":[{"text":"CBMCentralManagerDelegateProxy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerDelegateProxy\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerDelegateProxy\/navigatorTitle","value":[{"kind":"identifier","text":"CBMCentralManagerDelegateProxy"}],"op":"replace"},{"value":"CBMCentralManager","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/fragments","value":[{"kind":"identifier","text":"CBMCentralManager"}],"op":"replace"},{"value":[{"kind":"identifier","text":"CBMCentralManager"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxyWithL2CAPChannel\/title","value":"CBMPeripheralDelegateProxyWithL2CAPChannel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxyWithL2CAPChannel\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMPeripheralDelegateProxyWithL2CAPChannel"}]},{"value":[{"kind":"identifier","text":"CBMPeripheralDelegateProxyWithL2CAPChannel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxyWithL2CAPChannel\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMAttribute\/title","value":"CBMAttribute"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMAttribute\/fragments","op":"replace","value":[{"text":"CBMAttribute","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"CBMAttribute"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMAttribute\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/title","value":"CBMDescriptor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/fragments","value":[{"text":"CBMDescriptor","kind":"identifier"}]},{"op":"replace","value":[{"text":"CBMDescriptor","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/title","value":"CBMCentralManagerNative"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/fragments","value":[{"text":"CBMCentralManagerNative","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/navigatorTitle","op":"replace","value":[{"text":"CBMCentralManagerNative","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/title","op":"replace","value":"CBMServiceMock"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/fragments","value":[{"text":"CBMServiceMock","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/navigatorTitle","op":"replace","value":[{"text":"CBMServiceMock","kind":"identifier"}]},{"value":"CBMPeripheralDelegateProxy","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/fragments","value":[{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/navigatorTitle","value":[{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}