{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralPreview"]]},"abstract":[{"type":"text","text":"The maximum amount of data, in bytes, you can send to a characteristic in a single write type."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmperipheralpreview\/maximumwritevaluelength(for:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralPreview\/maximumWriteValueLength(for:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"maximumWriteValueLength","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBMCharacteristicWriteType","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock26CBMCharacteristicWriteTypea"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","externalID":"s:17CoreBluetoothMock20CBMPeripheralPreviewC23maximumWriteValueLength3forSiSo016CBCharacteristicG4TypeV_tF","modules":[{"name":"CoreBluetoothMock"}],"title":"maximumWriteValueLength(for:)","symbolKind":"method"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"maximumWriteValueLength","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"type"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicWriteType","text":"CBMCharacteristicWriteType","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock26CBMCharacteristicWriteTypea"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The characteristic write type to inspect.","type":"text"}]}],"name":"type"}]}],"sections":[],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralPreview":{"url":"\/documentation\/corebluetoothmock\/cbmperipheralpreview","title":"CBMPeripheralPreview","abstract":[{"text":"A stub ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","isActive":true},{"text":" implementation designed only for SwiftUI Previews.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPeripheralPreview","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralPreview","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralPreview"}],"role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralPreview/maximumWriteValueLength(for:)":{"kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheralpreview\/maximumwritevaluelength(for:)","abstract":[{"type":"text","text":"The maximum amount of data, in bytes, you can send to a characteristic in a single write type."}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"maximumWriteValueLength","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock26CBMCharacteristicWriteTypea","text":"CBMCharacteristicWriteType"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"maximumWriteValueLength(for:)","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralPreview\/maximumWriteValueLength(for:)"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristicWriteType":{"title":"CBMCharacteristicWriteType","url":"\/documentation\/corebluetoothmock\/cbmcharacteristicwritetype","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicWriteType","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCharacteristicWriteType"}],"abstract":[{"type":"text","text":"Values representing the possible write types to a characteristic’s value."}],"navigatorTitle":[{"kind":"identifier","text":"CBMCharacteristicWriteType"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"CBMPeripheralPreview","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralPreview\/title"},{"op":"replace","value":[{"text":"CBMPeripheralPreview","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralPreview\/fragments"},{"value":[{"kind":"identifier","text":"CBMPeripheralPreview"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralPreview\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}