{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/writeValue(_:for:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmperipheral\/writevalue(_:for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"CoreBluetoothMock"}],"symbolKind":"method","title":"writeValue(_:for:)","externalID":"s:17CoreBluetoothMock13CBMPeripheralP10writeValue_3fory10Foundation4DataV_AA13CBMDescriptorCtF","required":true,"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"writeValue","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"CBMDescriptor","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptor","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"writeValue"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"data"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"text":"descriptor","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CBMDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptor","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The value to write."}],"type":"paragraph"}],"name":"data"},{"content":[{"inlineContent":[{"text":"The descriptor containing the value to write.","type":"text"}],"type":"paragraph"}],"name":"descriptor"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"When you call this method to write the value of a characteristic descriptor, the peripheral calls the"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didWriteValueFor:error:)-90cp"},{"type":"text","text":" method of its delegate"},{"text":" ","type":"text"},{"text":"object.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method copies the data passed into the data parameter, and you can dispose of it after the method returns."}]},{"inlineContent":[{"text":"You can’t use this method to write the value of a client configuration descriptor (represented by the","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"CBUUIDClientCharacteristicConfigurationString"},{"text":" constant), which","type":"text"},{"type":"text","text":" "},{"type":"text","text":"describes the configuration of notification or indications for a characteristic’s value. If you want to manage notifications"},{"text":" ","type":"text"},{"text":"or indications for a characteristic’s value, you must use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/setNotifyValue(_:for:)"},{"type":"text","text":" "},{"text":"method instead.","type":"text"}],"type":"paragraph"}]}],"seeAlsoSections":[{"title":"Writing Characteristic and Descriptor Values","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/writeValue(_:for:type:)","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/maximumWriteValueLength(for:)","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicWriteType"],"anchor":"Writing-Characteristic-and-Descriptor-Values","generated":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral"]]},"abstract":[{"text":"Writes the value of a characteristic descriptor.","type":"text"}],"kind":"symbol","references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristicWriteType":{"title":"CBMCharacteristicWriteType","url":"\/documentation\/corebluetoothmock\/cbmcharacteristicwritetype","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicWriteType","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCharacteristicWriteType"}],"abstract":[{"type":"text","text":"Values representing the possible write types to a characteristic’s value."}],"navigatorTitle":[{"kind":"identifier","text":"CBMCharacteristicWriteType"}],"kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral/writeValue(_:for:type:)":{"role":"symbol","title":"writeValue(_:for:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"writeValue"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic","kind":"typeIdentifier","text":"CBMCharacteristic"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBMCharacteristicWriteType","preciseIdentifier":"s:17CoreBluetoothMock26CBMCharacteristicWriteTypea","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/writeValue(_:for:type:)","kind":"symbol","required":true,"url":"\/documentation\/corebluetoothmock\/cbmperipheral\/writevalue(_:for:type:)","type":"topic","abstract":[{"type":"text","text":"Writes the value of a characteristic."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegate/peripheral(_:didWriteValueFor:error:)-90cp":{"title":"peripheral(_:didWriteValueFor:error:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","text":"CBMPeripheral","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didWriteValueFor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CBMDescriptor","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"required":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didWriteValueFor:error:)-90cp","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegate\/peripheral(_:didwritevaluefor:error:)-90cp","kind":"symbol","defaultImplementations":2,"abstract":[{"text":"This method returns the result of a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/writeValue(_:for:)"},{"text":" call.","type":"text"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral/maximumWriteValueLength(for:)":{"title":"maximumWriteValueLength(for:)","url":"\/documentation\/corebluetoothmock\/cbmperipheral\/maximumwritevaluelength(for:)","required":true,"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximumWriteValueLength","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock26CBMCharacteristicWriteTypea","text":"CBMCharacteristicWriteType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/maximumWriteValueLength(for:)","type":"topic","abstract":[{"type":"text","text":"The maximum amount of data, in bytes, you can send to a characteristic in a single write type."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral/setNotifyValue(_:for:)":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/setNotifyValue(_:for:)","type":"topic","role":"symbol","abstract":[{"text":"Sets notifications or indications for the value of a specified characteristic.","type":"text"}],"required":true,"title":"setNotifyValue(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setNotifyValue","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic","text":"CBMCharacteristic","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheral\/setnotifyvalue(_:for:)","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMDescriptor":{"role":"symbol","title":"CBMDescriptor","abstract":[{"text":"An object that provides further information about a remote peripheral’s characteristic.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmdescriptor","navigatorTitle":[{"kind":"identifier","text":"CBMDescriptor"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMDescriptor","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral/writeValue(_:for:)":{"title":"writeValue(_:for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"writeValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptor","text":"CBMDescriptor"},{"kind":"text","text":")"}],"required":true,"url":"\/documentation\/corebluetoothmock\/cbmperipheral\/writevalue(_:for:)","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/writeValue(_:for:)","kind":"symbol","abstract":[{"text":"Writes the value of a characteristic descriptor.","type":"text"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/title","value":"CBMDescriptor","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/fragments","op":"replace","value":[{"text":"CBMDescriptor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/navigatorTitle","value":[{"text":"CBMDescriptor","kind":"identifier"}],"op":"replace"}]}]}