{"kind":"symbol","abstract":[{"text":"A list of the descriptors that have so far been discovered","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"in this characteristic."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmcharacteristic\/descriptors"]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"descriptors","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptor","text":"CBMDescriptor"},{"kind":"text","text":"]?"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"s:17CoreBluetoothMock17CBMCharacteristicC11descriptorsSayAA13CBMDescriptorCGSgvp","title":"descriptors","modules":[{"name":"CoreBluetoothMock"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"descriptors","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptor","text":"CBMDescriptor"},{"kind":"text","text":"]? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic\/descriptors","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic"]]},"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristic/descriptors":{"abstract":[{"text":"A list of the descriptors that have so far been discovered","type":"text"},{"text":" ","type":"text"},{"text":"in this characteristic.","type":"text"}],"type":"topic","title":"descriptors","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"descriptors"},{"text":": [","kind":"text"},{"text":"CBMDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptor"},{"text":"]?","kind":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmcharacteristic\/descriptors","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic\/descriptors","kind":"symbol","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMDescriptor":{"role":"symbol","title":"CBMDescriptor","abstract":[{"text":"An object that provides further information about a remote peripheral’s characteristic.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmdescriptor","navigatorTitle":[{"kind":"identifier","text":"CBMDescriptor"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMDescriptor","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristic":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMCharacteristic"}],"title":"CBMCharacteristic","type":"topic","abstract":[{"text":"A characteristic of a remote peripheral’s service.","type":"text"}],"navigatorTitle":[{"text":"CBMCharacteristic","kind":"identifier"}],"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcharacteristic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/title","value":"CBMDescriptor"},{"op":"replace","value":[{"text":"CBMDescriptor","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/navigatorTitle","value":[{"text":"CBMDescriptor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/title","op":"replace","value":"CBMCharacteristic"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMCharacteristic"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/navigatorTitle","value":[{"text":"CBMCharacteristic","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}