{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmservicemock\/init(type:primary:includedservices:characteristics:)-13qta"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Returns a service, initialized with a service type and UUID."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock\/init(type:primary:includedServices:characteristics:)-13qta","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"init(type:primary:includedServices:characteristics:)","modules":[{"name":"CoreBluetoothMock"}],"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CBMUUID","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa"},{"text":", ","kind":"text"},{"text":"primary","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"includedServices","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"CBMServiceMock","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMServiceMock"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"characteristics"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"CBMCharacteristicMock","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristicMock"},{"text":"]?)","kind":"text"}],"externalID":"s:17CoreBluetoothMock010CBMServiceC0C4type7primary16includedServices15characteristicsACSo6CBUUIDC_SbSayACGSgSayAA017CBMCharacteristicC0CGSgtcfc","symbolKind":"init"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"uuid"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","text":"CBMUUID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"primary","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"isPrimary","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"includedServices","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMServiceMock","text":"CBMServiceMock"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"characteristics"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicMock","text":"CBMCharacteristicMock","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristicMock","kind":"typeIdentifier"},{"kind":"text","text":"]? = nil)"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The Bluetooth UUID of the service.","type":"text"}]}],"name":"uuid"},{"content":[{"inlineContent":[{"type":"text","text":"The type of the service (primary or secondary)."}],"type":"paragraph"}],"name":"isPrimary"},{"name":"includedServices","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional array of included services."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional array of characteristics."}]}],"name":"characteristics"}]}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMService":{"abstract":[{"text":"A collection of data and associated behaviors that accomplish a function or feature of a device.","type":"text"}],"kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmservice","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMService","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMService"}],"title":"CBMService","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMServiceMock/init(type:primary:includedServices:characteristics:)-13qta":{"kind":"symbol","abstract":[{"text":"Returns a service, initialized with a service type and UUID.","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock\/init(type:primary:includedServices:characteristics:)-13qta","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","text":"CBMUUID"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"primary"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includedServices"},{"text":": [","kind":"text"},{"text":"CBMServiceMock","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMServiceMock"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"characteristics"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristicMock","text":"CBMCharacteristicMock"},{"kind":"text","text":"]?)"}],"url":"\/documentation\/corebluetoothmock\/cbmservicemock\/init(type:primary:includedservices:characteristics:)-13qta","title":"init(type:primary:includedServices:characteristics:)"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristicMock":{"url":"\/documentation\/corebluetoothmock\/cbmcharacteristicmock","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CBMCharacteristicMock","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMCharacteristicMock"}],"abstract":[{"type":"text","text":"Mock implementation of "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic","type":"reference","isActive":true},{"type":"text","text":"."}],"title":"CBMCharacteristicMock","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicMock","type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMUUID":{"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMUUID"}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmuuid","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID","title":"CBMUUID","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMUUID"}],"abstract":[{"text":"A universally unique identifier, as defined by Bluetooth standards.","type":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristic":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMCharacteristic"}],"title":"CBMCharacteristic","type":"topic","abstract":[{"text":"A characteristic of a remote peripheral’s service.","type":"text"}],"navigatorTitle":[{"text":"CBMCharacteristic","kind":"identifier"}],"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcharacteristic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMServiceMock":{"type":"topic","abstract":[{"type":"text","text":"Mock implementation of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock","role":"symbol","title":"CBMServiceMock","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMServiceMock"}],"navigatorTitle":[{"kind":"identifier","text":"CBMServiceMock"}],"url":"\/documentation\/corebluetoothmock\/cbmservicemock"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/title","op":"replace","value":"CBMService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/fragments","value":[{"text":"CBMService","kind":"identifier"}]},{"value":[{"text":"CBMService","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristicMock\/title","value":"CBMCharacteristicMock"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristicMock\/fragments","op":"replace","value":[{"text":"CBMCharacteristicMock","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristicMock\/navigatorTitle","value":[{"text":"CBMCharacteristicMock","kind":"identifier"}]},{"value":"CBMCharacteristic","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/title"},{"op":"replace","value":[{"text":"CBMCharacteristic","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/navigatorTitle","op":"replace","value":[{"text":"CBMCharacteristic","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/title","op":"replace","value":"CBMServiceMock"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/fragments","value":[{"text":"CBMServiceMock","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/navigatorTitle","value":[{"kind":"identifier","text":"CBMServiceMock"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}