{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"centralManager"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"central"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","text":"CBMCentralManager","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager"},{"kind":"text","text":", "},{"text":"didDisconnectPeripheral","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"peripheral"},{"text":": ","kind":"text"},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CFAbsoluteTime","preciseIdentifier":"c:@T@CFAbsoluteTime"},{"text":", ","kind":"text"},{"text":"isReconnecting","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"kind":"text","text":": ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?)","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The central manager providing this information."}],"type":"paragraph"}],"name":"central"},{"content":[{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","type":"reference","isActive":true},{"text":" that has disconnected.","type":"text"}],"type":"paragraph"}],"name":"peripheral"},{"name":"timestamp","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Timestamp of the disconnection, it can be now or a few seconds ago."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If reconnect was triggered upon disconnection."}]}],"name":"isReconnecting"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If an error occurred, the cause of the failure."}]}],"name":"error"}],"kind":"parameters"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If peripheral is connected with option"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionEnableAutoReconnect","isActive":true,"type":"reference"},{"text":",","type":"text"},{"text":" ","type":"text"},{"text":"the system will automatically invoke connect to the peripheral and if connection","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"is established with the peripheral afterwards,"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didConnect:)-p052","isActive":true},{"type":"text","text":" "},{"type":"text","text":"can be invoked."}]},{"inlineContent":[{"text":"If peripheral is connected without option","type":"text"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionEnableAutoReconnect","isActive":true,"type":"reference"},{"type":"text","text":", once this"},{"text":" ","type":"text"},{"type":"text","text":"method has been called, no more methods will be invoked peripheral’s"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"},{"name":"Important","style":"important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"If this method is implemented,","type":"text"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didDisconnectPeripheral:error:)-1lv48","isActive":true},{"text":" ","type":"text"},{"text":"will not be invoked. The CoreBluetooth Mock framework will call this method","type":"text"},{"type":"text","text":" "},{"type":"text","text":"on all iOS versions, despite the fact that the native API exists only since iOS 17+."}]}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate\/centralmanager(_:diddisconnectperipheral:timestamp:isreconnecting:error:)-52f9c"]}],"seeAlsoSections":[{"title":"Connection","generated":true,"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didConnect:)-p052","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didFailToConnect:error:)-2h1bb","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didDisconnectPeripheral:error:)-1lv48"],"anchor":"Connection"}],"kind":"symbol","metadata":{"required":true,"externalID":"s:17CoreBluetoothMock25CBMCentralManagerDelegateP07centralE0_23didDisconnectPeripheral9timestamp14isReconnecting5erroryAA0dE0C_AA13CBMPeripheral_pSdSbs5Error_pSgtF","modules":[{"name":"CoreBluetoothMock"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","text":"CBMCentralManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDisconnectPeripheral"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","text":"CBMPeripheral","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"timestamp"},{"text":": ","kind":"text"},{"text":"CFAbsoluteTime","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFAbsoluteTime"},{"kind":"text","text":", "},{"text":"isReconnecting","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"title":"centralManager(_:didDisconnectPeripheral:timestamp:isReconnecting:error:)","symbolKind":"method","role":"symbol"},"sections":[],"abstract":[{"text":"This method is invoked upon the disconnection of a peripheral that was","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"connected by "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/connect(_:options:)","isActive":true},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"defaultImplementationsSections":[{"anchor":"CBMCentralManagerDelegate-Implementations","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didDisconnectPeripheral:timestamp:isReconnecting:error:)-305ej"],"title":"CBMCentralManagerDelegate Implementations"}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didDisconnectPeripheral:timestamp:isReconnecting:error:)-52f9c","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate"]]},"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegate/centralManager(_:didDisconnectPeripheral:error:)-1lv48":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didDisconnectPeripheral:error:)-1lv48","kind":"symbol","abstract":[{"text":"This method is invoked upon the disconnection of a peripheral that was","type":"text"},{"type":"text","text":" "},{"text":"connected by ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/connect(_:options:)"},{"type":"text","text":"."}],"title":"centralManager(_:didDisconnectPeripheral:error:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CBMCentralManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didDisconnectPeripheral"},{"text":": ","kind":"text"},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?)","kind":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate\/centralmanager(_:diddisconnectperipheral:error:)-1lv48","type":"topic","required":true,"defaultImplementations":1},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegate/centralManager(_:didDisconnectPeripheral:timestamp:isReconnecting:error:)-52f9c":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didDisconnectPeripheral:timestamp:isReconnecting:error:)-52f9c","kind":"symbol","abstract":[{"type":"text","text":"This method is invoked upon the disconnection of a peripheral that was"},{"type":"text","text":" "},{"text":"connected by ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/connect(_:options:)","isActive":true,"type":"reference"},{"type":"text","text":"."}],"title":"centralManager(_:didDisconnectPeripheral:timestamp:isReconnecting:error:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"centralManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","text":"CBMCentralManager"},{"text":", ","kind":"text"},{"text":"didDisconnectPeripheral","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CFAbsoluteTime","text":"CFAbsoluteTime","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isReconnecting","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?)"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate\/centralmanager(_:diddisconnectperipheral:timestamp:isreconnecting:error:)-52f9c","type":"topic","required":true,"defaultImplementations":1},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegate/centralManager(_:didConnect:)-p052":{"kind":"symbol","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate\/centralmanager(_:didconnect:)-p052","abstract":[{"text":"This method is invoked when a connection initiated by","type":"text"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/connect(_:options:)","isActive":true},{"text":" has succeeded.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"centralManager"},{"text":"(","kind":"text"},{"text":"CBMCentralManager","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didConnect","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didConnect:)-p052","title":"centralManager(_:didConnect:)","required":true,"type":"topic","defaultImplementations":1},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManager"}],"title":"CBMCentralManager","abstract":[{"type":"text","text":"An object that scans for, discovers, connects to, and manages peripherals."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManager"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegate/centralManager(_:didFailToConnect:error:)-2h1bb":{"required":true,"abstract":[{"type":"text","text":"This method is invoked when a connection initiated by "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/connect(_:options:)","isActive":true},{"text":" ","type":"text"},{"type":"text","text":"has failed to complete."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CBMCentralManager","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager"},{"text":", ","kind":"text"},{"text":"didFailToConnect","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","text":"CBMPeripheral"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didFailToConnect:error:)-2h1bb","title":"centralManager(_:didFailToConnect:error:)","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate\/centralmanager(_:didfailtoconnect:error:)-2h1bb","role":"symbol","defaultImplementations":1,"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMConnectPeripheralOptionEnableAutoReconnect":{"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmconnectperipheraloptionenableautoreconnect","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMConnectPeripheralOptionEnableAutoReconnect"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionEnableAutoReconnect","role":"symbol","abstract":[{"text":"An Boolean indicating that the AutoReconnect is enabled for the peripheral is connected.","type":"text"}],"title":"CBMConnectPeripheralOptionEnableAutoReconnect"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegate/centralManager(_:didDisconnectPeripheral:timestamp:isReconnecting:error:)-305ej":{"type":"topic","title":"centralManager(_:didDisconnectPeripheral:timestamp:isReconnecting:error:)","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate\/centralmanager(_:diddisconnectperipheral:timestamp:isreconnecting:error:)-305ej","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didDisconnectPeripheral:timestamp:isReconnecting:error:)-305ej","abstract":[{"type":"text","text":"This method is invoked upon the disconnection of a peripheral that was"},{"type":"text","text":" "},{"type":"text","text":"connected by "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/connect(_:options:)","isActive":true},{"text":".","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"centralManager"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","text":"CBMCentralManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didDisconnectPeripheral","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"timestamp"},{"text":": ","kind":"text"},{"text":"CFAbsoluteTime","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFAbsoluteTime"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isReconnecting"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?)","kind":"text"}],"role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegate":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManagerDelegate"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate","navigatorTitle":[{"text":"CBMCentralManagerDelegate","kind":"identifier"}],"title":"CBMCentralManagerDelegate","kind":"symbol","abstract":[{"type":"text","text":"A protocol that provides updates for the discovery and management of peripheral devices."}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegate":{"type":"topic","title":"CBMPeripheralDelegate","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CBMPeripheralDelegate","kind":"identifier"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegate","abstract":[{"type":"text","text":"A protocol that provides updates on the use of a peripheral’s services."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralDelegate"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager/connect(_:options:)":{"abstract":[{"text":"Establishes a local connection to a peripheral.","type":"text"}],"type":"topic","kind":"symbol","title":"connect(_:options:)","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager\/connect(_:options:)","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/connect(_:options:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connect"},{"text":"(","kind":"text"},{"text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?)","kind":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"CBMCentralManager","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/fragments","op":"replace","value":[{"text":"CBMCentralManager","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"CBMCentralManager"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}