{"metadata":{"platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","beta":false,"introducedAt":"13.0"},{"beta":false,"unavailable":false,"introducedAt":"13.0","deprecated":false,"name":"iPadOS"},{"beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.0"}],"roleHeading":"Instance Method","extendedModule":"CoreBluetoothMock","symbolKind":"method","title":"centralManager(_:didUpdateANCSAuthorizationFor:)","externalID":"s:17CoreBluetoothMock25CBMCentralManagerDelegatePAAE07centralE0_29didUpdateANCSAuthorizationForyAA0dE0C_AA13CBMPeripheral_ptF","modules":[{"name":"CoreBluetoothMock"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CBMCentralManager","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager"},{"text":", ","kind":"text"},{"text":"didUpdateANCSAuthorizationFor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"kind":"text","text":")"}]},"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didUpdateANCSAuthorizationFor:)-8t3sl","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didUpdateANCSAuthorizationFor:)-6msdh"]]},"abstract":[{"text":"This method is invoked when the authorization status changes for a","type":"text"},{"text":" ","type":"text"},{"text":"peripheral connected with ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/connect(_:options:)","type":"reference","isActive":true},{"type":"text","text":" "},{"type":"text","text":"option "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionRequiresANCS","isActive":true},{"type":"text","text":"."}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate\/centralmanager(_:didupdateancsauthorizationfor:)-8t3sl"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"central","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CBMCentralManager","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didUpdateANCSAuthorizationFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"peripheral"},{"kind":"text","text":": "},{"text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"central","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The central manager providing this information."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","isActive":true,"type":"reference"},{"type":"text","text":" that caused the event."}]}],"name":"peripheral"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"aside","name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"This method is not implemented in mock central manager.","type":"text"}]}],"style":"important"}]}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMConnectPeripheralOptionRequiresANCS":{"type":"topic","abstract":[{"text":"An option to require Apple Notification Center Service (ANCS) when connecting a device.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionRequiresANCS","role":"symbol","title":"CBMConnectPeripheralOptionRequiresANCS","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMConnectPeripheralOptionRequiresANCS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/corebluetoothmock\/cbmconnectperipheraloptionrequiresancs"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager/connect(_:options:)":{"abstract":[{"text":"Establishes a local connection to a peripheral.","type":"text"}],"type":"topic","kind":"symbol","title":"connect(_:options:)","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager\/connect(_:options:)","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/connect(_:options:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connect"},{"text":"(","kind":"text"},{"text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?)","kind":"text"}],"role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManager"}],"title":"CBMCentralManager","abstract":[{"type":"text","text":"An object that scans for, discovers, connects to, and manages peripherals."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManager"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegate/centralManager(_:didUpdateANCSAuthorizationFor:)-6msdh":{"required":true,"title":"centralManager(_:didUpdateANCSAuthorizationFor:)","type":"topic","defaultImplementations":1,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didUpdateANCSAuthorizationFor:)-6msdh","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","text":"CBMCentralManager"},{"text":", ","kind":"text"},{"text":"didUpdateANCSAuthorizationFor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","text":"CBMPeripheral"},{"text":")","kind":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate\/centralmanager(_:didupdateancsauthorizationfor:)-6msdh","abstract":[{"text":"This method is invoked when the authorization status changes for a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"peripheral connected with "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/connect(_:options:)","isActive":true,"type":"reference"},{"type":"text","text":" "},{"text":"option ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionRequiresANCS","isActive":true},{"type":"text","text":"."}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegate":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManagerDelegate"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate","navigatorTitle":[{"text":"CBMCentralManagerDelegate","kind":"identifier"}],"title":"CBMCentralManagerDelegate","kind":"symbol","abstract":[{"type":"text","text":"A protocol that provides updates for the discovery and management of peripheral devices."}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegate/centralManager(_:didUpdateANCSAuthorizationFor:)-8t3sl":{"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate\/centralmanager(_:didupdateancsauthorizationfor:)-8t3sl","type":"topic","role":"symbol","abstract":[{"text":"This method is invoked when the authorization status changes for a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"peripheral connected with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/connect(_:options:)"},{"text":" ","type":"text"},{"text":"option ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionRequiresANCS","type":"reference"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didUpdateANCSAuthorizationFor:)-8t3sl","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"centralManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBMCentralManager","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didUpdateANCSAuthorizationFor"},{"text":": ","kind":"text"},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"text":")","kind":"text"}],"title":"centralManager(_:didUpdateANCSAuthorizationFor:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CBMCentralManager","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/fragments","value":[{"text":"CBMCentralManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/navigatorTitle","value":[{"kind":"identifier","text":"CBMCentralManager"}],"op":"replace"}]}]}