{"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock\/scanForPeripherals(withServices:options:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","role":"symbol","title":"scanForPeripherals(withServices:options:)","modules":[{"name":"CoreBluetoothMock"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scanForPeripherals","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withServices"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CBMUUID","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa"},{"text":"]?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"externalID":"s:17CoreBluetoothMock017CBMCentralManagerC0C18scanForPeripherals12withServices7optionsySaySo6CBUUIDCGSg_SDySSypGSgtF"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scanForPeripherals"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withServices"},{"kind":"text","text":" "},{"text":"serviceUUIDs","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID","text":"CBMUUID","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa"},{"text":"]?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]? = nil)"}],"languages":["swift"]}]},{"parameters":[{"name":"serviceUUIDs","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of "},{"type":"codeVoice","code":"CBMUUID"},{"text":" objects that the app is","type":"text"},{"type":"text","text":" "},{"type":"text","text":"interested in. Each "},{"code":"CBMUUID","type":"codeVoice"},{"type":"text","text":" object represents the"},{"type":"text","text":" "},{"type":"text","text":"UUID of a service that a peripheral advertises."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A dictionary of options for customizing the scan. For"},{"text":" ","type":"text"},{"text":"available options, see Peripheral Scanning Options.","type":"text"}]}],"name":"options"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"You can provide an array of "},{"code":"CBMUUID","type":"codeVoice"},{"type":"text","text":" objects — representing service"},{"text":" ","type":"text"},{"text":"UUIDs — in the serviceUUIDs parameter. When you do, the central","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"manager returns only peripherals that advertise the services you"},{"type":"text","text":" "},{"text":"specify. If the ","type":"text"},{"type":"codeVoice","code":"serviceUUIDs"},{"type":"text","text":" parameter is nil, this method returns"},{"type":"text","text":" "},{"type":"text","text":"all discovered peripherals, regardless of their supported services."}],"type":"paragraph"},{"inlineContent":[{"text":"If the central manager is actively scanning with one set of","type":"text"},{"type":"text","text":" "},{"type":"text","text":"parameters and it receives another set to scan, the new parameters"},{"type":"text","text":" "},{"type":"text","text":"override the previous set. When the central manager discovers a"},{"text":" ","type":"text"},{"type":"text","text":"peripheral, it calls the"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didDisconnectPeripheral:error:)-1lv48","isActive":true,"type":"reference"},{"text":" method of","type":"text"},{"type":"text","text":" "},{"type":"text","text":"its delegate object."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Your app can scan for Bluetooth devices in the background by","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"specifying the bluetooth-central background mode. To do this, your"},{"type":"text","text":" "},{"type":"text","text":"app must explicitly scan for one or more services by specifying"},{"text":" ","type":"text"},{"text":"them in the ","type":"text"},{"type":"codeVoice","code":"serviceUUIDs"},{"type":"text","text":" parameter. The "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","isActive":true},{"text":" scan","type":"text"},{"type":"text","text":" "},{"type":"text","text":"option has no effect while scanning in the background."}]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmcentralmanagermock\/scanforperipherals(withservices:options:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Scans for peripherals that are advertising services.","type":"text"}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMUUID":{"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMUUID"}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmuuid","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID","title":"CBMUUID","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMUUID"}],"abstract":[{"text":"A universally unique identifier, as defined by Bluetooth standards.","type":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerMock/scanForPeripherals(withServices:options:)":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock\/scanForPeripherals(withServices:options:)","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagermock\/scanforperipherals(withservices:options:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanForPeripherals","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withServices"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","text":"CBMUUID"},{"kind":"text","text":"]?, "},{"text":"options","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Scans for peripherals that are advertising services.","type":"text"}],"title":"scanForPeripherals(withServices:options:)"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerMock":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManagerMock"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagermock","abstract":[{"text":"Mock implementation of the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager"},{"type":"text","text":"."}],"title":"CBMCentralManagerMock","kind":"symbol","navigatorTitle":[{"text":"CBMCentralManagerMock","kind":"identifier"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegate/centralManager(_:didDisconnectPeripheral:error:)-1lv48":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didDisconnectPeripheral:error:)-1lv48","kind":"symbol","abstract":[{"text":"This method is invoked upon the disconnection of a peripheral that was","type":"text"},{"type":"text","text":" "},{"text":"connected by ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/connect(_:options:)"},{"type":"text","text":"."}],"title":"centralManager(_:didDisconnectPeripheral:error:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CBMCentralManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didDisconnectPeripheral"},{"text":": ","kind":"text"},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?)","kind":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate\/centralmanager(_:diddisconnectperipheral:error:)-1lv48","type":"topic","required":true,"defaultImplementations":1},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManager"}],"title":"CBMCentralManager","abstract":[{"type":"text","text":"An object that scans for, discovers, connects to, and manages peripherals."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManager"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager/connect(_:options:)":{"abstract":[{"text":"Establishes a local connection to a peripheral.","type":"text"}],"type":"topic","kind":"symbol","title":"connect(_:options:)","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager\/connect(_:options:)","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/connect(_:options:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connect"},{"text":"(","kind":"text"},{"text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?)","kind":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerMock\/title","value":"CBMCentralManagerMock","op":"replace"},{"op":"replace","value":[{"text":"CBMCentralManagerMock","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerMock\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CBMCentralManagerMock"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerMock\/navigatorTitle"},{"value":"CBMCentralManager","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/title"},{"value":[{"kind":"identifier","text":"CBMCentralManager"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBMCentralManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}