{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock"]]},"metadata":{"symbolKind":"property","modules":[{"name":"CoreBluetoothMock"}],"title":"state","externalID":"s:17CoreBluetoothMock017CBMCentralManagerC0C5stateAA15CBMManagerStateOvp","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"preciseIdentifier":"s:17CoreBluetoothMock15CBMManagerStateO","text":"CBMManagerState","kind":"typeIdentifier"}],"role":"symbol"},"abstract":[{"type":"text","text":"The current state of the manager, initially set to "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerState\/unknown","type":"reference"},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmcentralmanagermock\/state"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock15CBMManagerStateO","kind":"typeIdentifier","text":"CBMManagerState","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerState"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"inlineContent":[{"text":"Updates are provided by required delegate method","type":"text"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManagerDidUpdateState(_:)","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock\/state"},"kind":"symbol","references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerMock":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManagerMock"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagermock","abstract":[{"text":"Mock implementation of the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager"},{"type":"text","text":"."}],"title":"CBMCentralManagerMock","kind":"symbol","navigatorTitle":[{"text":"CBMCentralManagerMock","kind":"identifier"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMManagerState/unknown":{"abstract":[{"text":"The manager’s state is unknown.","type":"text"}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmmanagerstate\/unknown","kind":"symbol","title":"CBMManagerState.unknown","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerState\/unknown","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerMock/state":{"abstract":[{"type":"text","text":"The current state of the manager, initially set to "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerState\/unknown","isActive":true},{"text":".","type":"text"}],"kind":"symbol","title":"state","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagermock\/state","type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock\/state","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"state","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:17CoreBluetoothMock15CBMManagerStateO","text":"CBMManagerState","kind":"typeIdentifier"}],"role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManager"}],"title":"CBMCentralManager","abstract":[{"type":"text","text":"An object that scans for, discovers, connects to, and manages peripherals."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManager"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegate/centralManagerDidUpdateState(_:)":{"required":true,"abstract":[{"type":"text","text":"Invoked whenever the central manager’s state has been updated."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"centralManagerDidUpdateState"},{"text":"(","kind":"text"},{"text":"CBMCentralManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManagerDidUpdateState(_:)","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate\/centralmanagerdidupdatestate(_:)","title":"centralManagerDidUpdateState(_:)","type":"topic","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMManagerState":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerState","navigatorTitle":[{"text":"CBMManagerState","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The possible states of a Core Bluetooth manager."}],"title":"CBMManagerState","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMManagerState","kind":"identifier"}],"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmmanagerstate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerMock\/title","value":"CBMCentralManagerMock"},{"op":"replace","value":[{"text":"CBMCentralManagerMock","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerMock\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerMock\/navigatorTitle","value":[{"kind":"identifier","text":"CBMCentralManagerMock"}],"op":"replace"},{"value":"CBMCentralManager","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMCentralManager"}]},{"value":[{"kind":"identifier","text":"CBMCentralManager"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/navigatorTitle"}]}]}