{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeer\/init","interfaceLanguage":"occ"},"metadata":{"title":"init","role":"symbol","modules":[{"name":"CoreBluetoothMock"}],"externalID":"c:@M@CoreBluetoothMock@objc(cs)CBMPeer(im)init","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeer"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/corebluetoothmock\/cbmpeer\/init"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}]}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeer/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/corebluetoothmock\/cbmpeer\/init","kind":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"abstract":[],"title":"init","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeer\/init"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeer":{"navigatorTitle":[{"text":"CBMPeer","kind":"identifier"}],"url":"\/documentation\/corebluetoothmock\/cbmpeer","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPeer","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that represents a remote device."}],"title":"CBMPeer","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeer"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CBMPeer","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeer\/title"},{"value":[{"kind":"identifier","text":"CBMPeer"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeer\/fragments"},{"value":[{"text":"CBMPeer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeer\/navigatorTitle"}]}]}