{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/authorization-swift.type.property"]}],"metadata":{"roleHeading":"Type Property","platforms":[{"name":"iOS","beta":false,"introducedAt":"13.1","deprecated":false,"unavailable":false},{"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"13.1","unavailable":false},{"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false},{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS","introducedAt":"10.15"},{"introducedAt":"13.1","unavailable":false,"name":"tvOS","deprecated":false,"beta":false},{"name":"watchOS","deprecated":false,"unavailable":false,"introducedAt":"6.1","beta":false}],"modules":[{"name":"CoreBluetoothMock"}],"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authorization","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CBMManagerAuthorization","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock23CBMManagerAuthorizationa"}],"externalID":"s:17CoreBluetoothMock23CBMCentralManagerNativeC13authorizationSo22CBManagerAuthorizationVvpZ","title":"authorization"},"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/authorization-swift.type.property","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"authorization","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock23CBMManagerAuthorizationa","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerAuthorization","text":"CBMManagerAuthorization"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Check this property in your implementation of the delegate methods","type":"text"},{"type":"text","text":" "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManagerDidUpdateState(_:)","type":"reference"},{"text":" ","type":"text"},{"type":"text","text":"and "},{"code":"CBPeripheralManager.peripheralManagerDidUpdateState(_:)","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"to determine whether your app can use Core Bluetooth. You can also"},{"type":"text","text":" "},{"type":"text","text":"use it to check the app’s authorization status before creating a "},{"type":"codeVoice","code":"CBManager"},{"text":" instance.","type":"text"}]},{"inlineContent":[{"text":"The initial value of this property is ","type":"text"},{"type":"codeVoice","code":"CBMManagerAuthorization.notDetermined"},{"type":"text","text":"."}],"type":"paragraph"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"The current authorization status for using Bluetooth."}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManager"}],"title":"CBMCentralManager","abstract":[{"type":"text","text":"An object that scans for, discovers, connects to, and manages peripherals."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManager"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMManagerAuthorization":{"title":"CBMManagerAuthorization","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerAuthorization","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMManagerAuthorization","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMManagerAuthorization"}],"url":"\/documentation\/corebluetoothmock\/cbmmanagerauthorization","abstract":[{"text":"The current authorization state of a Core Bluetooth manager.","type":"text"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative":{"kind":"symbol","abstract":[{"type":"text","text":"An implementation  of "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"reference","isActive":true},{"type":"text","text":" that will proxy all the requests and responses"},{"text":" ","type":"text"},{"type":"text","text":"to the native "},{"type":"codeVoice","code":"CBCentralManager"},{"text":" object.","type":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative","title":"CBMCentralManagerNative","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMCentralManagerNative","kind":"identifier"}],"navigatorTitle":[{"text":"CBMCentralManagerNative","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegate/centralManagerDidUpdateState(_:)":{"required":true,"abstract":[{"type":"text","text":"Invoked whenever the central manager’s state has been updated."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"centralManagerDidUpdateState"},{"text":"(","kind":"text"},{"text":"CBMCentralManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManagerDidUpdateState(_:)","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate\/centralmanagerdidupdatestate(_:)","title":"centralManagerDidUpdateState(_:)","type":"topic","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/authorization-swift.type.property":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authorization","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock23CBMManagerAuthorizationa","kind":"typeIdentifier","text":"CBMManagerAuthorization"}],"abstract":[{"type":"text","text":"The current authorization status for using Bluetooth."}],"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/authorization-swift.type.property","title":"authorization","type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/authorization-swift.type.property"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CBMCentralManager","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/fragments","value":[{"kind":"identifier","text":"CBMCentralManager"}]},{"value":[{"text":"CBMCentralManager","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/navigatorTitle","op":"replace"},{"op":"replace","value":"CBMCentralManagerNative","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/fragments","value":[{"text":"CBMCentralManagerNative","kind":"identifier"}]},{"value":[{"text":"CBMCentralManagerNative","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/navigatorTitle","op":"replace"}]}]}