{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/registerforconnectionevents(options:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerForConnectionEvents","kind":"identifier"},{"text":"(","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectionEventMatchingOption","text":"CBMConnectionEventMatchingOption","preciseIdentifier":"s:17CoreBluetoothMock32CBMConnectionEventMatchingOptiona","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]? = nil)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"A dictionary that specifies options for","type":"text"},{"type":"text","text":" "},{"type":"text","text":"connection events. See Peripheral Connection"},{"type":"text","text":" "},{"text":"Options for a list of possible options.","type":"text"}],"type":"paragraph"}],"name":"options"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the central manager makes a connection that matches the"},{"text":" ","type":"text"},{"type":"text","text":"options, it calls the delegate’s"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:connectionEventDidOccur:for:)-1ay8d","isActive":true},{"text":" method.","type":"text"}]}]}],"abstract":[{"type":"text","text":"Register for an event notification when the central manager makes a"},{"type":"text","text":" "},{"text":"connection matching the given options.","type":"text"}],"metadata":{"title":"registerForConnectionEvents(options:)","roleHeading":"Instance Method","role":"symbol","platforms":[{"beta":false,"name":"iOS","unavailable":false,"introducedAt":"13.0","deprecated":false},{"deprecated":false,"name":"iPadOS","beta":false,"unavailable":false,"introducedAt":"13.0"},{"deprecated":false,"introducedAt":"13.0","unavailable":false,"name":"Mac Catalyst","beta":false},{"unavailable":false,"name":"tvOS","introducedAt":"13.0","deprecated":false,"beta":false},{"name":"watchOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"6.0"}],"modules":[{"name":"CoreBluetoothMock"}],"symbolKind":"method","externalID":"s:17CoreBluetoothMock23CBMCentralManagerNativeC27registerForConnectionEvents7optionsySDySo31CBConnectionEventMatchingOptionaypGSg_tF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerForConnectionEvents"},{"text":"(","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:17CoreBluetoothMock32CBMConnectionEventMatchingOptiona","text":"CBMConnectionEventMatchingOption","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/registerForConnectionEvents(options:)"},"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager/registerForConnectionEvents(options:)":{"abstract":[{"type":"text","text":"Register for an event notification when the central manager makes a"},{"text":" ","type":"text"},{"text":"connection matching the given options.","type":"text"}],"type":"topic","role":"symbol","title":"registerForConnectionEvents(options:)","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/registerForConnectionEvents(options:)","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager\/registerforconnectionevents(options:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerForConnectionEvents","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"options"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock32CBMConnectionEventMatchingOptiona","text":"CBMConnectionEventMatchingOption"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/registerForConnectionEvents(options:)":{"title":"registerForConnectionEvents(options:)","role":"symbol","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/registerforconnectionevents(options:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerForConnectionEvents"},{"text":"(","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"CBMConnectionEventMatchingOption","preciseIdentifier":"s:17CoreBluetoothMock32CBMConnectionEventMatchingOptiona","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}],"type":"topic","abstract":[{"type":"text","text":"Register for an event notification when the central manager makes a"},{"type":"text","text":" "},{"text":"connection matching the given options.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/registerForConnectionEvents(options:)"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManager"}],"title":"CBMCentralManager","abstract":[{"type":"text","text":"An object that scans for, discovers, connects to, and manages peripherals."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManager"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMConnectionEventMatchingOption":{"navigatorTitle":[{"kind":"identifier","text":"CBMConnectionEventMatchingOption"}],"abstract":[{"type":"text","text":"A set of options to use when registering for connection events."}],"type":"topic","role":"symbol","title":"CBMConnectionEventMatchingOption","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectionEventMatchingOption","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmconnectioneventmatchingoption","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMConnectionEventMatchingOption"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative":{"kind":"symbol","abstract":[{"type":"text","text":"An implementation  of "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"reference","isActive":true},{"type":"text","text":" that will proxy all the requests and responses"},{"text":" ","type":"text"},{"type":"text","text":"to the native "},{"type":"codeVoice","code":"CBCentralManager"},{"text":" object.","type":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative","title":"CBMCentralManagerNative","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMCentralManagerNative","kind":"identifier"}],"navigatorTitle":[{"text":"CBMCentralManagerNative","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegate/centralManager(_:connectionEventDidOccur:for:)-1ay8d":{"defaultImplementations":1,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","kind":"typeIdentifier","text":"CBMCentralManager"},{"kind":"text","text":", "},{"text":"connectionEventDidOccur","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock18CBMConnectionEventa","text":"CBMConnectionEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","text":"CBMPeripheral","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate\/centralmanager(_:connectioneventdidoccur:for:)-1ay8d","required":true,"abstract":[{"text":"This method is invoked upon the connection or disconnection of a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"peripheral that matches any of the options provided in"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/registerForConnectionEvents(options:)"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:connectionEventDidOccur:for:)-1ay8d","title":"centralManager(_:connectionEventDidOccur:for:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/title","op":"replace","value":"CBMCentralManager"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/fragments","value":[{"kind":"identifier","text":"CBMCentralManager"}]},{"value":[{"kind":"identifier","text":"CBMCentralManager"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/navigatorTitle","op":"replace"},{"value":"CBMCentralManagerNative","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/title","op":"replace"},{"value":[{"text":"CBMCentralManagerNative","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"CBMCentralManagerNative"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/navigatorTitle"}]}]}