{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopScan"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/stopscan()"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Asks the central manager to stop scanning for peripherals."}],"metadata":{"modules":[{"name":"CoreBluetoothMock"}],"title":"stopScan()","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopScan"},{"text":"()","kind":"text"}],"externalID":"s:17CoreBluetoothMock23CBMCentralManagerNativeC8stopScanyyF","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/stopScan()","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/stopScan()":{"type":"topic","kind":"symbol","title":"stopScan()","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/stopscan()","abstract":[{"type":"text","text":"Asks the central manager to stop scanning for peripherals."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopScan","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/stopScan()"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative":{"kind":"symbol","abstract":[{"type":"text","text":"An implementation  of "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"reference","isActive":true},{"type":"text","text":" that will proxy all the requests and responses"},{"text":" ","type":"text"},{"type":"text","text":"to the native "},{"type":"codeVoice","code":"CBCentralManager"},{"text":" object.","type":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative","title":"CBMCentralManagerNative","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMCentralManagerNative","kind":"identifier"}],"navigatorTitle":[{"text":"CBMCentralManagerNative","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManager"}],"title":"CBMCentralManager","abstract":[{"type":"text","text":"An object that scans for, discovers, connects to, and manages peripherals."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManager"}]}},"variantOverrides":[{"patch":[{"value":"CBMCentralManagerNative","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/title","op":"replace"},{"value":[{"text":"CBMCentralManagerNative","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/navigatorTitle","value":[{"kind":"identifier","text":"CBMCentralManagerNative"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/title","value":"CBMCentralManager"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/fragments","value":[{"text":"CBMCentralManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/navigatorTitle","value":[{"text":"CBMCentralManager","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}