{"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"supports"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"features"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","text":"CBMCentralManager","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/Feature","preciseIdentifier":"s:17CoreBluetoothMock17CBMCentralManagerC7Featurea","text":"Feature"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"One or more features that you would like to"},{"type":"text","text":" "},{"type":"text","text":"check for support."}],"type":"paragraph"}],"name":"features"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/supports(_:)"},"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/supports(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Returns a Boolean that indicates whether the device supports a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"specific set of features."}],"metadata":{"modules":[{"name":"CoreBluetoothMock"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supports","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CBMCentralManager","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Feature","preciseIdentifier":"s:17CoreBluetoothMock17CBMCentralManagerC7Featurea"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":[{"introducedAt":"13.0","deprecated":false,"unavailable":false,"name":"iOS","beta":false},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"13.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.0"},{"name":"tvOS","unavailable":false,"introducedAt":"13.0","beta":false,"deprecated":false},{"introducedAt":"6.0","beta":false,"deprecated":false,"name":"watchOS","unavailable":false}],"role":"symbol","title":"supports(_:)","roleHeading":"Type Method","symbolKind":"method","externalID":"s:17CoreBluetoothMock23CBMCentralManagerNativeC8supportsySbSo09CBCentralE7FeatureVFZ"},"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/supports(_:)":{"type":"topic","kind":"symbol","title":"supports(_:)","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/supports(_:)","abstract":[{"type":"text","text":"Returns a Boolean that indicates whether the device supports a"},{"text":" ","type":"text"},{"type":"text","text":"specific set of features."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"supports"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","text":"CBMCentralManager"},{"kind":"text","text":"."},{"text":"Feature","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock17CBMCentralManagerC7Featurea"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/supports(_:)"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager/Feature":{"kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager\/feature","title":"CBMCentralManager.Feature","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/Feature","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Feature"}],"navigatorTitle":[{"kind":"identifier","text":"Feature"}],"abstract":[{"text":"An option set of device-specific features.","type":"text"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManager"}],"title":"CBMCentralManager","abstract":[{"type":"text","text":"An object that scans for, discovers, connects to, and manages peripherals."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManager"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative":{"kind":"symbol","abstract":[{"type":"text","text":"An implementation  of "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"reference","isActive":true},{"type":"text","text":" that will proxy all the requests and responses"},{"text":" ","type":"text"},{"type":"text","text":"to the native "},{"type":"codeVoice","code":"CBCentralManager"},{"text":" object.","type":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative","title":"CBMCentralManagerNative","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMCentralManagerNative","kind":"identifier"}],"navigatorTitle":[{"text":"CBMCentralManagerNative","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/title","value":"CBMCentralManager"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/fragments","value":[{"text":"CBMCentralManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/navigatorTitle","value":[{"text":"CBMCentralManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/title","op":"replace","value":"CBMCentralManagerNative"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/fragments","value":[{"text":"CBMCentralManagerNative","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/navigatorTitle","value":[{"text":"CBMCentralManagerNative","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}