{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debugDescription"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","title":"debugDescription","modules":[{"name":"CoreBluetoothMock"}],"navigatorTitle":[{"text":"debugDescription","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debugDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@CoreBluetoothMock@objc(cs)CBMPeripheralMock(py)debugDescription"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmperipheralmock\/debugdescription"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/corebluetoothmock\/cbmperipheralmock\/debugdescription"]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock\/debugDescription","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralMock/debugDescription":{"title":"debugDescription","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock\/debugDescription","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"debugDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralmock\/debugdescription","navigatorTitle":[{"kind":"identifier","text":"debugDescription"}],"kind":"symbol","abstract":[]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralMock":{"abstract":[{"type":"text","text":"Mock implementation of the "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","isActive":true},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralmock","kind":"symbol","title":"CBMPeripheralMock","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock","navigatorTitle":[{"text":"CBMPeripheralMock","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMPeripheralMock"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"debugDescription"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"debugDescription"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"debugDescription"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock~1debugDescription\/title","value":"debugDescription"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock~1debugDescription\/fragments","value":[{"text":"debugDescription","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock\/title","value":"CBMPeripheralMock","op":"replace"},{"value":[{"kind":"identifier","text":"CBMPeripheralMock"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock\/fragments"},{"op":"replace","value":[{"text":"CBMPeripheralMock","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock\/navigatorTitle"}]}]}