{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmperipheralmock\/delegate"]}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock\/delegate"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock21CBMPeripheralDelegateP","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate","text":"CBMPeripheralDelegate"},{"kind":"text","text":"?"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"For information about how to implement your peripheral delegate, see "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate","isActive":true,"type":"reference"},{"text":".","type":"text"}]}],"kind":"content"}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","title":"delegate","externalID":"s:17CoreBluetoothMock013CBMPeripheralC0C8delegateAA0D8Delegate_pSgvp","modules":[{"name":"CoreBluetoothMock"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"text":"CBMPeripheralDelegate","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock21CBMPeripheralDelegateP"},{"kind":"text","text":"?"}]},"abstract":[{"type":"text","text":"The delegate object specified to receive peripheral events."}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralMock":{"abstract":[{"type":"text","text":"Mock implementation of the "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","isActive":true},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralmock","kind":"symbol","title":"CBMPeripheralMock","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock","navigatorTitle":[{"text":"CBMPeripheralMock","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMPeripheralMock"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegate":{"type":"topic","title":"CBMPeripheralDelegate","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CBMPeripheralDelegate","kind":"identifier"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegate","abstract":[{"type":"text","text":"A protocol that provides updates on the use of a peripheral’s services."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralDelegate"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralMock/delegate":{"abstract":[{"type":"text","text":"The delegate object specified to receive peripheral events."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:17CoreBluetoothMock21CBMPeripheralDelegateP","text":"CBMPeripheralDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock\/delegate","url":"\/documentation\/corebluetoothmock\/cbmperipheralmock\/delegate","type":"topic","title":"delegate","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"}},"variantOverrides":[{"patch":[{"value":"CBMPeripheralMock","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock\/title"},{"value":[{"text":"CBMPeripheralMock","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock\/navigatorTitle","value":[{"text":"CBMPeripheralMock","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}