{"metadata":{"roleHeading":"Instance Method","symbolKind":"method","title":"discoverCharacteristics(_:for:)","modules":[{"name":"CoreBluetoothMock"}],"externalID":"s:17CoreBluetoothMock013CBMPeripheralC0C23discoverCharacteristics_3forySaySo6CBUUIDCGSg_AA10CBMServiceCtF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"discoverCharacteristics"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","text":"CBMUUID","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService","kind":"typeIdentifier","text":"CBMService"},{"kind":"text","text":")"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"discoverCharacteristics","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"characteristicUUIDs","kind":"internalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","text":"CBMUUID","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"service"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CBMService","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"characteristicUUIDs","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A list of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID"},{"type":"text","text":" objects representing the characteristic types"},{"text":" ","type":"text"},{"text":"to be discovered. If ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" or an empty array, all characteristics of service will be discovered."}]}]},{"name":"service","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A GATT service."}]}]}],"kind":"parameters"},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can provide an array of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID"},{"type":"text","text":" objects—representing characteristic UUIDs — in the "},{"code":"characteristicUUIDs","type":"codeVoice"},{"type":"text","text":" "},{"text":"parameter. When you do, the peripheral returns only the characteristics of the service that match the provided UUIDs.","type":"text"},{"text":" ","type":"text"},{"text":"If the ","type":"text"},{"type":"codeVoice","code":"characteristicUUIDs"},{"text":" parameter is ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" or an empty array, this method returns all characteristics of the service."}]},{"style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"If the ","type":"text"},{"code":"characteristicUUIDs","type":"codeVoice"},{"type":"text","text":" parameter is "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" or an empty array, this method returns all of the service’s"},{"type":"text","text":" "},{"type":"text","text":"characteristics. This is much slower than providing an array of characteristic UUIDs to search for."}]}],"type":"aside"},{"inlineContent":[{"type":"text","text":"When the peripheral discovers one or more characteristics of the specified service, it calls the"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didDiscoverCharacteristicsFor:error:)-2pyjk","isActive":true},{"type":"text","text":" method"},{"text":" ","type":"text"},{"type":"text","text":"of its delegate object. After the peripheral discovers the service’s characteristics, you can access them through the service’s"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService\/characteristics","isActive":true,"type":"reference"},{"type":"text","text":" property."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmperipheralmock\/discovercharacteristics(_:for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock\/discoverCharacteristics(_:for:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Discovers the specified characteristics of a service."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralMock":{"abstract":[{"type":"text","text":"Mock implementation of the "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","isActive":true},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralmock","kind":"symbol","title":"CBMPeripheralMock","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock","navigatorTitle":[{"text":"CBMPeripheralMock","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMPeripheralMock"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMUUID":{"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMUUID"}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmuuid","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID","title":"CBMUUID","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMUUID"}],"abstract":[{"text":"A universally unique identifier, as defined by Bluetooth standards.","type":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralMock/discoverCharacteristics(_:for:)":{"url":"\/documentation\/corebluetoothmock\/cbmperipheralmock\/discovercharacteristics(_:for:)","title":"discoverCharacteristics(_:for:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock\/discoverCharacteristics(_:for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"discoverCharacteristics","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","text":"CBMUUID"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"CBMService","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","abstract":[{"text":"Discovers the specified characteristics of a service.","type":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMService":{"abstract":[{"text":"A collection of data and associated behaviors that accomplish a function or feature of a device.","type":"text"}],"kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmservice","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMService","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMService"}],"title":"CBMService","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMService/characteristics":{"abstract":[{"type":"text","text":"A list of characteristics that have so far been discovered in this service."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"characteristics"},{"kind":"text","text":": ["},{"text":"CBMCharacteristic","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic"},{"text":"]?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService\/characteristics","url":"\/documentation\/corebluetoothmock\/cbmservice\/characteristics","type":"topic","title":"characteristics","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral/discoverCharacteristics(_:for:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/discoverCharacteristics(_:for:)","abstract":[{"type":"text","text":"Discovers the specified characteristics of a service."}],"url":"\/documentation\/corebluetoothmock\/cbmperipheral\/discovercharacteristics(_:for:)","required":true,"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"discoverCharacteristics"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","text":"CBMUUID","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService","text":"CBMService"},{"text":")","kind":"text"}],"title":"discoverCharacteristics(_:for:)","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegate/peripheral(_:didDiscoverCharacteristicsFor:error:)-2pyjk":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didDiscoverCharacteristicsFor:error:)-2pyjk","kind":"symbol","abstract":[{"type":"text","text":"This method returns the result of a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/discoverCharacteristics(_:for:)"},{"type":"text","text":" call."},{"type":"text","text":" "},{"text":"If the characteristic(s) were read successfully, they can be retrieved via service’s","type":"text"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService\/characteristics","isActive":true,"type":"reference"},{"type":"text","text":" property."}],"title":"peripheral(_:didDiscoverCharacteristicsFor:error:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didDiscoverCharacteristicsFor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CBMService","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegate\/peripheral(_:diddiscovercharacteristicsfor:error:)-2pyjk","type":"topic","required":true,"defaultImplementations":1}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CBMPeripheralMock","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"CBMPeripheralMock"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock\/navigatorTitle","value":[{"text":"CBMPeripheralMock","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/title","op":"replace","value":"CBMService"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMService"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/navigatorTitle","value":[{"text":"CBMService","kind":"identifier"}]}]}]}