{"abstract":[{"type":"text","text":"The maximum amount of data, in bytes, you can send to a characteristic in a single write type."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock"]]},"metadata":{"externalID":"s:17CoreBluetoothMock013CBMPeripheralC0C23maximumWriteValueLength3forSiSo016CBCharacteristicF4TypeV_tF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"maximumWriteValueLength","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBMCharacteristicWriteType","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock26CBMCharacteristicWriteTypea"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"9.0","beta":false},{"name":"iPadOS","beta":false,"introducedAt":"9.0","deprecated":false,"unavailable":false},{"introducedAt":"9.0","deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false}],"title":"maximumWriteValueLength(for:)","modules":[{"name":"CoreBluetoothMock"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock\/maximumWriteValueLength(for:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"maximumWriteValueLength","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"type"},{"text":": ","kind":"text"},{"text":"CBMCharacteristicWriteType","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicWriteType","preciseIdentifier":"s:17CoreBluetoothMock26CBMCharacteristicWriteTypea"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"type","content":[{"inlineContent":[{"type":"text","text":"The characteristic write type to inspect."}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmperipheralmock\/maximumwritevaluelength(for:)"]}],"sections":[],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralMock/maximumWriteValueLength(for:)":{"abstract":[{"type":"text","text":"The maximum amount of data, in bytes, you can send to a characteristic in a single write type."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"maximumWriteValueLength","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock26CBMCharacteristicWriteTypea","text":"CBMCharacteristicWriteType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock\/maximumWriteValueLength(for:)","url":"\/documentation\/corebluetoothmock\/cbmperipheralmock\/maximumwritevaluelength(for:)","type":"topic","title":"maximumWriteValueLength(for:)","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristicWriteType":{"title":"CBMCharacteristicWriteType","url":"\/documentation\/corebluetoothmock\/cbmcharacteristicwritetype","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicWriteType","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCharacteristicWriteType"}],"abstract":[{"type":"text","text":"Values representing the possible write types to a characteristic’s value."}],"navigatorTitle":[{"kind":"identifier","text":"CBMCharacteristicWriteType"}],"kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralMock":{"abstract":[{"type":"text","text":"Mock implementation of the "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","isActive":true},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralmock","kind":"symbol","title":"CBMPeripheralMock","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock","navigatorTitle":[{"text":"CBMPeripheralMock","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMPeripheralMock"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock\/title","value":"CBMPeripheralMock"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock\/fragments","op":"replace","value":[{"text":"CBMPeripheralMock","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock\/navigatorTitle","value":[{"text":"CBMPeripheralMock","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}