{"metadata":{"title":"peripheral(_:didOpen:error:)","externalID":"s:17CoreBluetoothMock42CBMPeripheralDelegateProxyWithL2CAPChannelC10peripheral_7didOpen5erroryAA0D0_p_So04CBL2I0CSgs5Error_pSgtF","roleHeading":"Instance Method","role":"symbol","platforms":[{"introducedAt":"11.0","name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"11.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"11.0","beta":false},{"introducedAt":"11.0","beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"deprecated":false,"introducedAt":"4.0","name":"watchOS","beta":false,"unavailable":false}],"symbolKind":"method","modules":[{"name":"CoreBluetoothMock"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"kind":"text","text":", "},{"text":"didOpen","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBML2CAPChannel","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock15CBML2CAPChannela"},{"text":"?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"peripheral"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"kind":"text","text":", "},{"text":"didOpen","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"channel"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock15CBML2CAPChannela","text":"CBML2CAPChannel","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBML2CAPChannel","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxyWithL2CAPChannel"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxyWithL2CAPChannel\/peripheral(_:didOpen:error:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxywithl2capchannel\/peripheral(_:didopen:error:)"]}],"kind":"symbol","references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegateProxyWithL2CAPChannel/peripheral(_:didOpen:error:)":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxyWithL2CAPChannel\/peripheral(_:didOpen:error:)","kind":"symbol","title":"peripheral(_:didOpen:error:)","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxywithl2capchannel\/peripheral(_:didopen:error:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didOpen"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CBML2CAPChannel","preciseIdentifier":"s:17CoreBluetoothMock15CBML2CAPChannela"},{"text":"?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegateProxyWithL2CAPChannel":{"navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralDelegateProxyWithL2CAPChannel"}],"kind":"symbol","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxywithl2capchannel","abstract":[{"text":"A helper class that allows setting delegate callbacks as closures.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPeripheralDelegateProxyWithL2CAPChannel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxyWithL2CAPChannel","title":"CBMPeripheralDelegateProxyWithL2CAPChannel","type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBML2CAPChannel":{"navigatorTitle":[{"kind":"identifier","text":"CBML2CAPChannel"}],"url":"\/documentation\/corebluetoothmock\/cbml2capchannel","kind":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBML2CAPChannel","kind":"identifier"}],"abstract":[{"text":"A live L2CAP connection to a remote device.","type":"text"}],"title":"CBML2CAPChannel","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBML2CAPChannel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxyWithL2CAPChannel\/title","value":"CBMPeripheralDelegateProxyWithL2CAPChannel"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxyWithL2CAPChannel\/fragments","value":[{"text":"CBMPeripheralDelegateProxyWithL2CAPChannel","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"CBMPeripheralDelegateProxyWithL2CAPChannel"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxyWithL2CAPChannel\/navigatorTitle","op":"replace"}]}]}