{"metadata":{"roleHeading":"Instance Property","symbolKind":"property","platforms":[{"introducedAt":"13.0","name":"iOS","beta":false,"unavailable":false,"deprecated":false},{"introducedAt":"13.0","unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"introducedAt":"13.0","deprecated":false},{"unavailable":false,"deprecated":false,"introducedAt":"13.0","beta":false,"name":"tvOS"},{"unavailable":false,"deprecated":false,"name":"watchOS","introducedAt":"6.0","beta":false}],"modules":[{"name":"CoreBluetoothMock"}],"externalID":"s:17CoreBluetoothMock19CBMPeripheralNativeC14ancsAuthorizedSbvp","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ancsAuthorized"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"ancsAuthorized"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative"]]},"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmperipheralnative\/ancsauthorized"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/ancsAuthorized"},"abstract":[{"type":"text","text":"A Boolean value that indicates if the remote device has authorization to receive data over ANCS protocol."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ancsAuthorized","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"If this value is false, a user authorization sets this value to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":", which results in a call to the delegate’s"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didUpdateANCSAuthorizationFor:)-6msdh","isActive":true},{"text":" method.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager/connect(_:options:)":{"abstract":[{"text":"Establishes a local connection to a peripheral.","type":"text"}],"type":"topic","kind":"symbol","title":"connect(_:options:)","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager\/connect(_:options:)","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/connect(_:options:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connect"},{"text":"(","kind":"text"},{"text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?)","kind":"text"}],"role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMConnectPeripheralOptionRequiresANCS":{"type":"topic","abstract":[{"text":"An option to require Apple Notification Center Service (ANCS) when connecting a device.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionRequiresANCS","role":"symbol","title":"CBMConnectPeripheralOptionRequiresANCS","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMConnectPeripheralOptionRequiresANCS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/corebluetoothmock\/cbmconnectperipheraloptionrequiresancs"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/ancsAuthorized":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ancsAuthorized","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/ancsAuthorized","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"A Boolean value that indicates if the remote device has authorization to receive data over ANCS protocol.","type":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/ancsauthorized","title":"ancsAuthorized"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegate/centralManager(_:didUpdateANCSAuthorizationFor:)-6msdh":{"required":true,"title":"centralManager(_:didUpdateANCSAuthorizationFor:)","type":"topic","defaultImplementations":1,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:didUpdateANCSAuthorizationFor:)-6msdh","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","text":"CBMCentralManager"},{"text":", ","kind":"text"},{"text":"didUpdateANCSAuthorizationFor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","text":"CBMPeripheral"},{"text":")","kind":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate\/centralmanager(_:didupdateancsauthorizationfor:)-6msdh","abstract":[{"text":"This method is invoked when the authorization status changes for a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"peripheral connected with "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/connect(_:options:)","isActive":true,"type":"reference"},{"type":"text","text":" "},{"text":"option ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionRequiresANCS","isActive":true},{"type":"text","text":"."}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative":{"abstract":[{"type":"text","text":"A native implementation of "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","type":"reference"},{"text":" that will proxy all requests to an underlying ","type":"text"},{"code":"CBPeripheral","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMPeripheralNative","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralNative"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative","type":"topic","title":"CBMPeripheralNative","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"CBMPeripheralNative","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative\/title"},{"value":[{"text":"CBMPeripheralNative","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative\/navigatorTitle","value":[{"kind":"identifier","text":"CBMPeripheralNative"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}