{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/discoverCharacteristics(_:for:)"},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"discoverCharacteristics","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"CBMUUID","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"CBMService","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"discoverCharacteristics(_:for:)","symbolKind":"method","externalID":"s:17CoreBluetoothMock19CBMPeripheralNativeC23discoverCharacteristics_3forySaySo6CBUUIDCGSg_AA10CBMServiceCtF","modules":[{"name":"CoreBluetoothMock"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"text":"Discovers the specified characteristics of a service.","type":"text"}],"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmperipheralnative\/discovercharacteristics(_:for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"discoverCharacteristics","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"characteristicUUIDs","kind":"internalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID","text":"CBMUUID","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa"},{"kind":"text","text":"]?, "},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"service","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CBMService","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A list of "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID","isActive":true},{"text":" objects representing the characteristic types","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to be discovered. If "},{"type":"codeVoice","code":"nil"},{"text":" or an empty array, all characteristics of service will be discovered.","type":"text"}]}],"name":"characteristicUUIDs"},{"name":"service","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A GATT service."}]}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"You can provide an array of ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID","isActive":true},{"text":" objects—representing characteristic UUIDs — in the ","type":"text"},{"code":"characteristicUUIDs","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"parameter. When you do, the peripheral returns only the characteristics of the service that match the provided UUIDs."},{"text":" ","type":"text"},{"text":"If the ","type":"text"},{"type":"codeVoice","code":"characteristicUUIDs"},{"text":" parameter is ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" or an empty array, this method returns all characteristics of the service."}]},{"type":"aside","name":"Note","content":[{"inlineContent":[{"type":"text","text":"If the "},{"type":"codeVoice","code":"characteristicUUIDs"},{"type":"text","text":" parameter is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" or an empty array, this method returns all of the service’s"},{"text":" ","type":"text"},{"type":"text","text":"characteristics. This is much slower than providing an array of characteristic UUIDs to search for."}],"type":"paragraph"}],"style":"note"},{"type":"paragraph","inlineContent":[{"text":"When the peripheral discovers one or more characteristics of the specified service, it calls the","type":"text"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didDiscoverCharacteristicsFor:error:)-2pyjk","isActive":true},{"type":"text","text":" method"},{"text":" ","type":"text"},{"type":"text","text":"of its delegate object. After the peripheral discovers the service’s characteristics, you can access them through the service’s"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService\/characteristics","isActive":true,"type":"reference"},{"type":"text","text":" property."}]}]}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/discoverCharacteristics(_:for:)":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/discoverCharacteristics(_:for:)","kind":"symbol","type":"topic","title":"discoverCharacteristics(_:for:)","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/discovercharacteristics(_:for:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"discoverCharacteristics","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"CBMUUID","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa"},{"text":"]?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService","text":"CBMService","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Discovers the specified characteristics of a service."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative":{"abstract":[{"type":"text","text":"A native implementation of "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","type":"reference"},{"text":" that will proxy all requests to an underlying ","type":"text"},{"code":"CBPeripheral","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMPeripheralNative","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralNative"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative","type":"topic","title":"CBMPeripheralNative","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMService/characteristics":{"abstract":[{"type":"text","text":"A list of characteristics that have so far been discovered in this service."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"characteristics"},{"kind":"text","text":": ["},{"text":"CBMCharacteristic","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic"},{"text":"]?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService\/characteristics","url":"\/documentation\/corebluetoothmock\/cbmservice\/characteristics","type":"topic","title":"characteristics","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMUUID":{"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMUUID"}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmuuid","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID","title":"CBMUUID","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMUUID"}],"abstract":[{"text":"A universally unique identifier, as defined by Bluetooth standards.","type":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegate/peripheral(_:didDiscoverCharacteristicsFor:error:)-2pyjk":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didDiscoverCharacteristicsFor:error:)-2pyjk","kind":"symbol","abstract":[{"type":"text","text":"This method returns the result of a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/discoverCharacteristics(_:for:)"},{"type":"text","text":" call."},{"type":"text","text":" "},{"text":"If the characteristic(s) were read successfully, they can be retrieved via service’s","type":"text"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService\/characteristics","isActive":true,"type":"reference"},{"type":"text","text":" property."}],"title":"peripheral(_:didDiscoverCharacteristicsFor:error:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didDiscoverCharacteristicsFor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CBMService","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegate\/peripheral(_:diddiscovercharacteristicsfor:error:)-2pyjk","type":"topic","required":true,"defaultImplementations":1},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral/discoverCharacteristics(_:for:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/discoverCharacteristics(_:for:)","abstract":[{"type":"text","text":"Discovers the specified characteristics of a service."}],"url":"\/documentation\/corebluetoothmock\/cbmperipheral\/discovercharacteristics(_:for:)","required":true,"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"discoverCharacteristics"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","text":"CBMUUID","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService","text":"CBMService"},{"text":")","kind":"text"}],"title":"discoverCharacteristics(_:for:)","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMService":{"abstract":[{"text":"A collection of data and associated behaviors that accomplish a function or feature of a device.","type":"text"}],"kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmservice","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMService","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMService"}],"title":"CBMService","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative\/title","value":"CBMPeripheralNative"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative\/fragments","value":[{"text":"CBMPeripheralNative","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative\/navigatorTitle","op":"replace","value":[{"text":"CBMPeripheralNative","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/title","value":"CBMService","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/fragments","value":[{"kind":"identifier","text":"CBMService"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/navigatorTitle","value":[{"text":"CBMService","kind":"identifier"}]}]}]}