{"kind":"symbol","variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmperipheralnative\/openl2capchannel(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative"]]},"abstract":[{"type":"text","text":"Attempts to open an L2CAP channel to the peripheral using the supplied Protocol\/Service Multiplexer (PSM)."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/openL2CAPChannel(_:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"roleHeading":"Instance Method","platforms":[{"deprecated":false,"name":"iOS","introducedAt":"11.0","unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"11.0","unavailable":false,"deprecated":false,"beta":false},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"11.0","name":"Mac Catalyst"},{"name":"tvOS","deprecated":false,"beta":false,"introducedAt":"11.0","unavailable":false},{"unavailable":false,"introducedAt":"4.0","name":"watchOS","beta":false,"deprecated":false}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openL2CAPChannel","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock11CBML2CAPPSMa","text":"CBML2CAPPSM","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"openL2CAPChannel(_:)","externalID":"s:17CoreBluetoothMock19CBMPeripheralNativeC16openL2CAPChannelyys6UInt16VF","modules":[{"name":"CoreBluetoothMock"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openL2CAPChannel"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"PSM","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CBML2CAPPSM","preciseIdentifier":"s:17CoreBluetoothMock11CBML2CAPPSMa","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBML2CAPPSM"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The PSM of the channel to open."}]}],"name":"PSM"}]}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/openL2CAPChannel(_:)":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/openL2CAPChannel(_:)","kind":"symbol","type":"topic","title":"openL2CAPChannel(_:)","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/openl2capchannel(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"openL2CAPChannel"},{"text":"(","kind":"text"},{"text":"CBML2CAPPSM","preciseIdentifier":"s:17CoreBluetoothMock11CBML2CAPPSMa","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Attempts to open an L2CAP channel to the peripheral using the supplied Protocol\/Service Multiplexer (PSM)."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative":{"abstract":[{"type":"text","text":"A native implementation of "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","type":"reference"},{"text":" that will proxy all requests to an underlying ","type":"text"},{"code":"CBPeripheral","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMPeripheralNative","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralNative"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative","type":"topic","title":"CBMPeripheralNative","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBML2CAPPSM":{"url":"\/documentation\/corebluetoothmock\/cbml2cappsm","title":"CBML2CAPPSM","abstract":[{"type":"text","text":"The type of PSM identifiers."}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBML2CAPPSM","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBML2CAPPSM","navigatorTitle":[{"kind":"identifier","text":"CBML2CAPPSM"}],"role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative\/title","value":"CBMPeripheralNative","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMPeripheralNative"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative\/navigatorTitle","value":[{"text":"CBMPeripheralNative","kind":"identifier"}]}]}]}