{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmdescriptor\/uuid"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"uuid","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID","text":"CBMUUID","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"uuid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","text":"CBMUUID","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"CoreBluetoothMock"}],"externalID":"s:17CoreBluetoothMock13CBMDescriptorC4uuidSo6CBUUIDCvp","role":"symbol","roleHeading":"Instance Property","title":"uuid"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor\/uuid","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"The Bluetooth-specific UUID of the attribute.","type":"text"}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMDescriptor":{"role":"symbol","title":"CBMDescriptor","abstract":[{"text":"An object that provides further information about a remote peripheral’s characteristic.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmdescriptor","navigatorTitle":[{"kind":"identifier","text":"CBMDescriptor"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMDescriptor","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMUUID":{"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMUUID"}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmuuid","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID","title":"CBMUUID","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMUUID"}],"abstract":[{"text":"A universally unique identifier, as defined by Bluetooth standards.","type":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMDescriptor/uuid":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor\/uuid","abstract":[{"type":"text","text":"The Bluetooth-specific UUID of the attribute."}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmdescriptor\/uuid","title":"uuid","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"uuid","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","text":"CBMUUID"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"CBMDescriptor","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/fragments","value":[{"kind":"identifier","text":"CBMDescriptor"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/navigatorTitle","op":"replace","value":[{"text":"CBMDescriptor","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}