{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/corebluetoothmock\/cbmattribute\/init"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAttribute"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAttribute\/init"},"metadata":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"modules":[{"name":"CoreBluetoothMock"}],"title":"init","role":"symbol","externalID":"c:@M@CoreBluetoothMock@objc(cs)CBMAttribute(im)init","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"init"}]},"sections":[],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMAttribute":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAttribute","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMAttribute","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBMAttribute"}],"title":"CBMAttribute","url":"\/documentation\/corebluetoothmock\/cbmattribute","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A representation of common aspects of services offered by a peripheral."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMAttribute/init":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAttribute\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","url":"\/documentation\/corebluetoothmock\/cbmattribute\/init","kind":"symbol","role":"symbol","abstract":[]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMAttribute\/title","value":"CBMAttribute"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMAttribute\/fragments","value":[{"text":"CBMAttribute","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"CBMAttribute","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMAttribute\/navigatorTitle"}]}]}