{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDiscoverIncludedServices"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","text":"CBMPeripheral","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"CBMService","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService"},{"kind":"text","text":", "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> ())?"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy\/didDiscoverIncludedServices"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxy\/diddiscoverincludedservices"]}],"sections":[],"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"didDiscoverIncludedServices","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"CBMService","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> ())?"}],"role":"symbol","modules":[{"name":"CoreBluetoothMock"}],"roleHeading":"Instance Property","title":"didDiscoverIncludedServices","externalID":"s:17CoreBluetoothMock26CBMPeripheralDelegateProxyC27didDiscoverIncludedServicesyAA0D0_p_AA10CBMServiceCs5Error_pSgtcSgvp"},"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegateProxy/didDiscoverIncludedServices":{"title":"didDiscoverIncludedServices","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxy\/diddiscoverincludedservices","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy\/didDiscoverIncludedServices","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDiscoverIncludedServices"},{"kind":"text","text":": (("},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"kind":"text","text":", "},{"text":"CBMService","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ())?","kind":"text"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMService":{"abstract":[{"text":"A collection of data and associated behaviors that accomplish a function or feature of a device.","type":"text"}],"kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmservice","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMService","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMService"}],"title":"CBMService","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegateProxy":{"title":"CBMPeripheralDelegateProxy","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy","kind":"symbol","abstract":[{"type":"text","text":"A helper class that allows setting delegate callbacks as closures."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}],"type":"topic","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxy","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CBMService","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"CBMService"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBMService"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/title","value":"CBMPeripheralDelegateProxy","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}]},{"value":[{"text":"CBMPeripheralDelegateProxy","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/navigatorTitle","op":"replace"}]}]}