{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"didWriteDescriptorValue","kind":"identifier"},{"kind":"text","text":": (("},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptor","text":"CBMDescriptor"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> ())?"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxy\/didwritedescriptorvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didWriteDescriptorValue"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","text":"CBMPeripheral"},{"kind":"text","text":", "},{"text":"CBMDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptor"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ())?","kind":"text"}],"role":"symbol","externalID":"s:17CoreBluetoothMock26CBMPeripheralDelegateProxyC23didWriteDescriptorValueyAA0D0_p_AA13CBMDescriptorCs5Error_pSgtcSgvp","modules":[{"name":"CoreBluetoothMock"}],"title":"didWriteDescriptorValue","symbolKind":"property"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy\/didWriteDescriptorValue"},"sections":[],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegateProxy/didWriteDescriptorValue":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"didWriteDescriptorValue","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptor","text":"CBMDescriptor"},{"kind":"text","text":", "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> ())?"}],"title":"didWriteDescriptorValue","type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy\/didWriteDescriptorValue","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxy\/didwritedescriptorvalue","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegateProxy":{"title":"CBMPeripheralDelegateProxy","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy","kind":"symbol","abstract":[{"type":"text","text":"A helper class that allows setting delegate callbacks as closures."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}],"type":"topic","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxy","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMDescriptor":{"role":"symbol","title":"CBMDescriptor","abstract":[{"text":"An object that provides further information about a remote peripheral’s characteristic.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmdescriptor","navigatorTitle":[{"kind":"identifier","text":"CBMDescriptor"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMDescriptor","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"CBMPeripheralDelegateProxy","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/fragments"},{"value":[{"text":"CBMPeripheralDelegateProxy","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/title","value":"CBMDescriptor"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/fragments","value":[{"kind":"identifier","text":"CBMDescriptor"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/navigatorTitle","value":[{"text":"CBMDescriptor","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}