{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy\/CBMPeripheralDelegate-Implementations"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateValueFor","kind":"externalParam"},{"kind":"text","text":" "},{"text":"characteristic","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic","text":"CBMCharacteristic","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?)","kind":"text"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy\/peripheral(_:didUpdateValueFor:error:)-nw91","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"CBMPeripheralDelegate.peripheral(_:didUpdateValueFor:error:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxy\/peripheral(_:didupdatevaluefor:error:)-nw91"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"extendedModule":"CoreBluetoothMock","roleHeading":"Instance Method","title":"peripheral(_:didUpdateValueFor:error:)","modules":[{"name":"CoreBluetoothMock"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didUpdateValueFor"},{"kind":"text","text":": "},{"text":"CBMCharacteristic","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"symbolKind":"method","externalID":"s:17CoreBluetoothMock21CBMPeripheralDelegatePAAE10peripheral_17didUpdateValueFor5erroryAA0D0_p_AA17CBMCharacteristicCs5Error_pSgtF::SYNTHESIZED::c:@M@CoreBluetoothMock@objc(cs)CBMPeripheralDelegateProxy","role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegateProxy/CBMPeripheralDelegate-Implementations":{"kind":"article","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxy\/cbmperipheraldelegate-implementations","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy\/CBMPeripheralDelegate-Implementations","type":"topic","role":"collectionGroup","title":"CBMPeripheralDelegate Implementations","abstract":[]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegateProxy":{"title":"CBMPeripheralDelegateProxy","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy","kind":"symbol","abstract":[{"type":"text","text":"A helper class that allows setting delegate callbacks as closures."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}],"type":"topic","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxy","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegateProxy/peripheral(_:didUpdateValueFor:error:)-nw91":{"abstract":[],"type":"topic","kind":"symbol","title":"peripheral(_:didUpdateValueFor:error:)","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxy\/peripheral(_:didupdatevaluefor:error:)-nw91","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy\/peripheral(_:didUpdateValueFor:error:)-nw91","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","kind":"typeIdentifier","text":"CBMPeripheral"},{"kind":"text","text":", "},{"text":"didUpdateValueFor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic","text":"CBMCharacteristic","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristic":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMCharacteristic"}],"title":"CBMCharacteristic","type":"topic","abstract":[{"text":"A characteristic of a remote peripheral’s service.","type":"text"}],"navigatorTitle":[{"text":"CBMCharacteristic","kind":"identifier"}],"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcharacteristic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"CBMPeripheralDelegateProxy","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/fragments","value":[{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/navigatorTitle","value":[{"text":"CBMPeripheralDelegateProxy","kind":"identifier"}]},{"value":"CBMCharacteristic","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/fragments","value":[{"kind":"identifier","text":"CBMCharacteristic"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/navigatorTitle","op":"replace","value":[{"text":"CBMCharacteristic","kind":"identifier"}]}]}]}