{"sections":[],"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxy\/peripheral(_:didreadrssi:error:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral"},{"kind":"text","text":", "},{"text":"didReadRSSI","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"RSSI"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"peripheral","content":[{"inlineContent":[{"type":"text","text":"The peripheral providing this update."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The current RSSI of the link.","type":"text"}],"type":"paragraph"}],"name":"RSSI"},{"content":[{"inlineContent":[{"type":"text","text":"If an error occurred, the cause of the failure."}],"type":"paragraph"}],"name":"error"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy\/peripheral(_:didReadRSSI:error:)"},"abstract":[{"text":"This method returns the result of a ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/readRSSI()","isActive":true},{"type":"text","text":" call."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","text":"CBMPeripheral","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReadRSSI","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"peripheral(_:didReadRSSI:error:)","role":"symbol","externalID":"s:17CoreBluetoothMock26CBMPeripheralDelegateProxyC10peripheral_11didReadRSSI5erroryAA0D0_p_So8NSNumberCs5Error_pSgtF","roleHeading":"Instance Method","modules":[{"name":"CoreBluetoothMock"}],"symbolKind":"method"},"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegateProxy/peripheral(_:didReadRSSI:error:)":{"title":"peripheral(_:didReadRSSI:error:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","kind":"typeIdentifier","text":"CBMPeripheral"},{"text":", ","kind":"text"},{"text":"didReadRSSI","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy\/peripheral(_:didReadRSSI:error:)","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxy\/peripheral(_:didreadrssi:error:)","kind":"symbol","abstract":[{"text":"This method returns the result of a ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/readRSSI()","isActive":true},{"type":"text","text":" call."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegateProxy":{"title":"CBMPeripheralDelegateProxy","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy","kind":"symbol","abstract":[{"type":"text","text":"A helper class that allows setting delegate callbacks as closures."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}],"type":"topic","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxy","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral/readRSSI()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/readRSSI()","abstract":[{"text":"Retrieves the current RSSI value for the peripheral while connected to the central manager.","type":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheral\/readrssi()","required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"readRSSI","kind":"identifier"},{"kind":"text","text":"()"}],"title":"readRSSI()","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CBMPeripheralDelegateProxy","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/title"},{"value":[{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/navigatorTitle","value":[{"text":"CBMPeripheralDelegateProxy","kind":"identifier"}]}]}]}