{"kind":"symbol","variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxy\/peripheralisready(tosendwritewithoutresponse:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy\/peripheralIsReady(toSendWriteWithoutResponse:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"peripheralIsReady","kind":"identifier"},{"text":"(","kind":"text"},{"text":"toSendWriteWithoutResponse","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"kind":"text","text":")"}],"externalID":"s:17CoreBluetoothMock26CBMPeripheralDelegateProxyC17peripheralIsReady26toSendWriteWithoutResponseyAA0D0_p_tF","role":"symbol","title":"peripheralIsReady(toSendWriteWithoutResponse:)","modules":[{"name":"CoreBluetoothMock"}],"roleHeading":"Instance Method","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheralIsReady","kind":"identifier"},{"kind":"text","text":"("},{"text":"toSendWriteWithoutResponse","kind":"externalParam"},{"kind":"text","text":" "},{"text":"peripheral","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CBMPeripheral","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"peripheral","content":[{"inlineContent":[{"type":"text","text":"The peripheral providing this update."}],"type":"paragraph"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy"]]},"abstract":[{"text":"This method is invoked after a failed call to ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/writeValue(_:for:type:)","type":"reference"},{"text":", when","type":"text"},{"type":"text","text":" "},{"type":"text","text":"peripheral is again ready to send characteristic value updates."}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral/writeValue(_:for:type:)":{"role":"symbol","title":"writeValue(_:for:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"writeValue"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic","kind":"typeIdentifier","text":"CBMCharacteristic"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBMCharacteristicWriteType","preciseIdentifier":"s:17CoreBluetoothMock26CBMCharacteristicWriteTypea","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/writeValue(_:for:type:)","kind":"symbol","required":true,"url":"\/documentation\/corebluetoothmock\/cbmperipheral\/writevalue(_:for:type:)","type":"topic","abstract":[{"type":"text","text":"Writes the value of a characteristic."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegateProxy":{"title":"CBMPeripheralDelegateProxy","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy","kind":"symbol","abstract":[{"type":"text","text":"A helper class that allows setting delegate callbacks as closures."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}],"type":"topic","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxy","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegateProxy/peripheralIsReady(toSendWriteWithoutResponse:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy\/peripheralIsReady(toSendWriteWithoutResponse:)","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxy\/peripheralisready(tosendwritewithoutresponse:)","title":"peripheralIsReady(toSendWriteWithoutResponse:)","abstract":[{"type":"text","text":"This method is invoked after a failed call to "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/writeValue(_:for:type:)","isActive":true},{"text":", when","type":"text"},{"text":" ","type":"text"},{"text":"peripheral is again ready to send characteristic value updates.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"peripheralIsReady","kind":"identifier"},{"kind":"text","text":"("},{"text":"toSendWriteWithoutResponse","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/title","value":"CBMPeripheralDelegateProxy"},{"value":[{"text":"CBMPeripheralDelegateProxy","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/fragments","op":"replace"},{"op":"replace","value":[{"text":"CBMPeripheralDelegateProxy","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}