{"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveReadRequestFor:)-7sk6x","interfaceLanguage":"swift"},"sections":[],"defaultImplementationsSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveReadRequestFor:)-5c1ls","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveReadRequestFor:)-6tewg"],"title":"CBMPeripheralSpecDelegate Implementations","anchor":"CBMPeripheralSpecDelegate-Implementations"}],"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didreceivereadrequestfor:)-7sk6x"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC","text":"CBMPeripheralSpec"},{"kind":"text","text":", "},{"text":"didReceiveReadRequestFor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CBMDescriptorMock","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptorMock"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">","kind":"text"}],"role":"symbol","required":true,"externalID":"s:17CoreBluetoothMock25CBMPeripheralSpecDelegateP10peripheral_24didReceiveReadRequestFors6ResultOy10Foundation4DataVs5Error_pGAA0dE0C_AA013CBMDescriptorC0CtF","modules":[{"name":"CoreBluetoothMock"}],"title":"peripheral(_:didReceiveReadRequestFor:)","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate"]]},"kind":"symbol","abstract":[{"type":"text","text":"This method will be called when read request has been initiated from a mock"},{"type":"text","text":" "},{"type":"text","text":"central manager."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CBMPeripheralSpec","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec"},{"text":", ","kind":"text"},{"text":"didReceiveReadRequestFor","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"descriptor","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptorMock","kind":"typeIdentifier","text":"CBMDescriptorMock","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptorMock"},{"kind":"text","text":") -> "},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":">"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"peripheral","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The target peripheral specification."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The descriptor, which value should be returned."}]}],"name":"descriptor"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"When success, the descriptor value should be returned. In case","type":"text"},{"type":"text","text":" "},{"type":"text","text":"of a failure, the returned error will be returned to the"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didUpdateValueFor:error:)-2xce0"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"seeAlsoSections":[{"generated":true,"title":"Handling Requests","anchor":"Handling-Requests","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveReadRequestFor:)-9ybod","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveWriteCommandFor:data:)-58pcn","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveWriteRequestFor:data:)-yspa","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveWriteRequestFor:data:)-81sdk"]}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate/peripheral(_:didReceiveReadRequestFor:)-9ybod":{"url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didreceivereadrequestfor:)-9ybod","required":true,"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBMPeripheralSpec","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC"},{"text":", ","kind":"text"},{"text":"didReceiveReadRequestFor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CBMCharacteristicMock","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristicMock"},{"kind":"text","text":") -> "},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">"}],"defaultImplementations":2,"abstract":[{"type":"text","text":"This method will be called when read request has been initiated from a mock"},{"text":" ","type":"text"},{"type":"text","text":"central manager."}],"title":"peripheral(_:didReceiveReadRequestFor:)","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveReadRequestFor:)-9ybod","type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate/peripheral(_:didReceiveWriteRequestFor:data:)-yspa":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveWriteRequestFor:data:)-yspa","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheral"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBMPeripheralSpec","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveWriteRequestFor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristicMock","text":"CBMCharacteristicMock","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":") -> ","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">"}],"title":"peripheral(_:didReceiveWriteRequestFor:data:)","type":"topic","abstract":[{"type":"text","text":"This method will be called when write request has been initiated from a mock"},{"text":" ","type":"text"},{"type":"text","text":"central manager."}],"required":true,"defaultImplementations":2,"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didreceivewriterequestfor:data:)-yspa"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate/peripheral(_:didReceiveWriteCommandFor:data:)-58pcn":{"url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didreceivewritecommandfor:data:)-58pcn","required":true,"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"text":"CBMPeripheralSpec","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveWriteCommandFor"},{"kind":"text","text":": "},{"text":"CBMCharacteristicMock","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristicMock"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":")"}],"defaultImplementations":1,"abstract":[{"type":"text","text":"This method will be called when write command has been initiated from a mock"},{"type":"text","text":" "},{"text":"central manager. Write command is also known as write without response.","type":"text"}],"title":"peripheral(_:didReceiveWriteCommandFor:data:)","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveWriteCommandFor:data:)-58pcn","type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate/peripheral(_:didReceiveReadRequestFor:)-6tewg":{"abstract":[],"title":"peripheral(_:didReceiveReadRequestFor:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC","text":"CBMPeripheralSpec"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveReadRequestFor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristicMock","kind":"typeIdentifier","text":"CBMCharacteristicMock"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":">"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveReadRequestFor:)-6tewg","url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didreceivereadrequestfor:)-6tewg","type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral/readValue(for:)-1hqxp":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/readValue(for:)-1hqxp","type":"topic","role":"symbol","abstract":[{"text":"Retrieves the value of a specified characteristic.","type":"text"}],"required":true,"title":"readValue(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"readValue"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic","text":"CBMCharacteristic","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheral\/readvalue(for:)-1hqxp","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMDescriptor":{"role":"symbol","title":"CBMDescriptor","abstract":[{"text":"An object that provides further information about a remote peripheral’s characteristic.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmdescriptor","navigatorTitle":[{"kind":"identifier","text":"CBMDescriptor"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMDescriptor","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate/peripheral(_:didReceiveReadRequestFor:)-7sk6x":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveReadRequestFor:)-7sk6x","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheral"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBMPeripheralSpec","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveReadRequestFor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptorMock","text":"CBMDescriptorMock","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">"}],"title":"peripheral(_:didReceiveReadRequestFor:)","type":"topic","abstract":[{"type":"text","text":"This method will be called when read request has been initiated from a mock"},{"text":" ","type":"text"},{"type":"text","text":"central manager."}],"required":true,"defaultImplementations":2,"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didreceivereadrequestfor:)-7sk6x"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMDescriptorMock":{"type":"topic","abstract":[{"text":"Mock implementation of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptorMock","role":"symbol","title":"CBMDescriptorMock","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMDescriptorMock","kind":"identifier"}],"navigatorTitle":[{"text":"CBMDescriptorMock","kind":"identifier"}],"url":"\/documentation\/corebluetoothmock\/cbmdescriptormock"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate/peripheral(_:didReceiveReadRequestFor:)-5c1ls":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"kind":"text","text":"("},{"text":"CBMPeripheralSpec","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didReceiveReadRequestFor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptorMock","text":"CBMDescriptorMock"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":">","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveReadRequestFor:)-5c1ls","url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didreceivereadrequestfor:)-5c1ls","title":"peripheral(_:didReceiveReadRequestFor:)","type":"topic","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate":{"navigatorTitle":[{"text":"CBMPeripheralSpecDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"This delegate should implement the behavior of a real Bluetooth LE device during a connection."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheralSpecDelegate","kind":"identifier"}],"title":"CBMPeripheralSpecDelegate","type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate","url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate/peripheral(_:didReceiveWriteRequestFor:data:)-81sdk":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveWriteRequestFor:data:)-81sdk","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC","text":"CBMPeripheralSpec"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveWriteRequestFor"},{"text":": ","kind":"text"},{"text":"CBMDescriptorMock","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptorMock"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":">","kind":"text"}],"title":"peripheral(_:didReceiveWriteRequestFor:data:)","type":"topic","abstract":[{"text":"This method will be called when write request has been initiated from a mock","type":"text"},{"type":"text","text":" "},{"type":"text","text":"central manager."}],"required":true,"defaultImplementations":2,"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didreceivewriterequestfor:data:)-81sdk"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec":{"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralspec","navigatorTitle":[{"text":"CBMPeripheralSpec","kind":"identifier"}],"title":"CBMPeripheralSpec","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPeripheralSpec","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Specification of a mock peripheral."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegate/peripheral(_:didUpdateValueFor:error:)-2xce0":{"type":"topic","title":"peripheral(_:didUpdateValueFor:error:)","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegate\/peripheral(_:didupdatevaluefor:error:)-2xce0","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"kind":"text","text":"("},{"text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didUpdateValueFor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CBMCharacteristic","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?)","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"This method is invoked after a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/readValue(for:)-1hqxp"},{"text":" call, or upon","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"receipt of a notification\/indication."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didUpdateValueFor:error:)-2xce0","defaultImplementations":2}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/title","value":"CBMDescriptor","op":"replace"},{"value":[{"kind":"identifier","text":"CBMDescriptor"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/fragments"},{"value":[{"text":"CBMDescriptor","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptorMock\/title","value":"CBMDescriptorMock"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptorMock\/fragments","value":[{"kind":"identifier","text":"CBMDescriptorMock"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptorMock\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBMDescriptorMock"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}