{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didUpdateNotificationStateFor:error:)-4aash","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate"]]},"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didupdatenotificationstatefor:error:)-4aash"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"peripheral"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC","text":"CBMPeripheralSpec","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didUpdateNotificationStateFor"},{"text":" ","kind":"text"},{"text":"characteristic","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CBMCharacteristicMock","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristicMock","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicMock"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The target peripheral specification."}]}],"name":"peripheral"},{"name":"characteristic","content":[{"inlineContent":[{"text":"The target characteristic.","type":"text"}],"type":"paragraph"}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error returned from"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveSetNotifyRequest:for:)-9r03q"},{"type":"text","text":"."}]}]}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"It is safe to send value updates using"},{"text":" ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/simulateValueUpdate(_:for:)"},{"type":"text","text":" from this method if"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic\/isNotifying"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"This method will be called when notifications or indications were enabled"},{"type":"text","text":" "},{"type":"text","text":"or disabled on the given characteristic using a mock central manager."}],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveSetNotifyRequest:for:)-9r03q"],"generated":true,"title":"Handling Notifications","anchor":"Handling-Notifications"}],"kind":"symbol","metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC","text":"CBMPeripheralSpec","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateNotificationStateFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBMCharacteristicMock","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristicMock","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}],"required":true,"role":"symbol","externalID":"s:17CoreBluetoothMock25CBMPeripheralSpecDelegateP10peripheral_29didUpdateNotificationStateFor5erroryAA0dE0C_AA017CBMCharacteristicC0Cs5Error_pSgtF","modules":[{"name":"CoreBluetoothMock"}],"title":"peripheral(_:didUpdateNotificationStateFor:error:)","symbolKind":"method"},"defaultImplementationsSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didUpdateNotificationStateFor:error:)-nipu"],"anchor":"CBMPeripheralSpecDelegate-Implementations","title":"CBMPeripheralSpecDelegate Implementations"}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristic":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMCharacteristic"}],"title":"CBMCharacteristic","type":"topic","abstract":[{"text":"A characteristic of a remote peripheral’s service.","type":"text"}],"navigatorTitle":[{"text":"CBMCharacteristic","kind":"identifier"}],"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcharacteristic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristicMock":{"url":"\/documentation\/corebluetoothmock\/cbmcharacteristicmock","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CBMCharacteristicMock","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMCharacteristicMock"}],"abstract":[{"type":"text","text":"Mock implementation of "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic","type":"reference","isActive":true},{"type":"text","text":"."}],"title":"CBMCharacteristicMock","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicMock","type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate/peripheral(_:didReceiveSetNotifyRequest:for:)-9r03q":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveSetNotifyRequest:for:)-9r03q","title":"peripheral(_:didReceiveSetNotifyRequest:for:)","required":true,"defaultImplementations":1,"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didreceivesetnotifyrequest:for:)-9r03q","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"text":"CBMPeripheralSpec","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC"},{"text":", ","kind":"text"},{"text":"didReceiveSetNotifyRequest","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristicMock","text":"CBMCharacteristicMock","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":">","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"This method will be called when client requested enabling or disabling notifications or"},{"type":"text","text":" "},{"type":"text","text":"indications on the given characteristic using a mock central manager."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate/peripheral(_:didUpdateNotificationStateFor:error:)-4aash":{"title":"peripheral(_:didUpdateNotificationStateFor:error:)","role":"symbol","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didupdatenotificationstatefor:error:)-4aash","defaultImplementations":1,"abstract":[{"type":"text","text":"This method will be called when notifications or indications were enabled"},{"type":"text","text":" "},{"type":"text","text":"or disabled on the given characteristic using a mock central manager."}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"text":"CBMPeripheralSpec","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateNotificationStateFor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristicMock","kind":"typeIdentifier","text":"CBMCharacteristicMock"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didUpdateNotificationStateFor:error:)-4aash"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec":{"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralspec","navigatorTitle":[{"text":"CBMPeripheralSpec","kind":"identifier"}],"title":"CBMPeripheralSpec","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPeripheralSpec","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Specification of a mock peripheral."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec/simulateValueUpdate(_:for:)":{"url":"\/documentation\/corebluetoothmock\/cbmperipheralspec\/simulatevalueupdate(_:for:)","type":"topic","title":"simulateValueUpdate(_:for:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"simulateValueUpdate"},{"text":"(","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristicMock","text":"CBMCharacteristicMock"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/simulateValueUpdate(_:for:)","abstract":[{"type":"text","text":"Simulates a notification\/indication sent from the peripheral."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate/peripheral(_:didUpdateNotificationStateFor:error:)-nipu":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didUpdateNotificationStateFor:error:)-nipu","url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didupdatenotificationstatefor:error:)-nipu","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"text":"CBMPeripheralSpec","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC"},{"text":", ","kind":"text"},{"text":"didUpdateNotificationStateFor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristicMock","text":"CBMCharacteristicMock"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"This method will be called when notifications or indications were enabled"},{"type":"text","text":" "},{"text":"or disabled on the given characteristic using a mock central manager.","type":"text"}],"type":"topic","kind":"symbol","title":"peripheral(_:didUpdateNotificationStateFor:error:)"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristic/isNotifying":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isNotifying","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/corebluetoothmock\/cbmcharacteristic\/isnotifying","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic\/isNotifying","abstract":[{"type":"text","text":"Whether the characteristic is currently notifying or not."}],"type":"topic","title":"isNotifying","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate":{"navigatorTitle":[{"text":"CBMPeripheralSpecDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"This delegate should implement the behavior of a real Bluetooth LE device during a connection."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheralSpecDelegate","kind":"identifier"}],"title":"CBMPeripheralSpecDelegate","type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate","url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"CBMCharacteristic","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/fragments","op":"replace","value":[{"text":"CBMCharacteristic","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/navigatorTitle","value":[{"text":"CBMCharacteristic","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristicMock\/title","value":"CBMCharacteristicMock","op":"replace"},{"value":[{"kind":"identifier","text":"CBMCharacteristicMock"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristicMock\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristicMock\/navigatorTitle","op":"replace","value":[{"text":"CBMCharacteristicMock","kind":"identifier"}]}]}]}