{"defaultImplementationsSections":[{"title":"CBMPeripheralSpecDelegate Implementations","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveCharacteristicsDiscoveryRequest:for:)-995x5"],"anchor":"CBMPeripheralSpecDelegate-Implementations"}],"seeAlsoSections":[{"title":"Handling Service Discovery","generated":true,"anchor":"Handling-Service-Discovery","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveServiceDiscoveryRequest:)-pq5f","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveIncludedServiceDiscoveryRequest:for:)-4mqk2","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveDescriptorsDiscoveryRequestFor:)-6rk13"]}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveCharacteristicsDiscoveryRequest:for:)-2doal","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"role":"symbol","externalID":"s:17CoreBluetoothMock25CBMPeripheralSpecDelegateP10peripheral_41didReceiveCharacteristicsDiscoveryRequest3fors6ResultOyyts5Error_pGAA0dE0C_SaySo6CBUUIDCGSgAA010CBMServiceC0CtF","modules":[{"name":"CoreBluetoothMock"}],"required":true,"title":"peripheral(_:didReceiveCharacteristicsDiscoveryRequest:for:)","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC","text":"CBMPeripheralSpec"},{"text":", ","kind":"text"},{"text":"didReceiveCharacteristicsDiscoveryRequest","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","text":"CBMUUID","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMServiceMock","text":"CBMServiceMock","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":">"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC","text":"CBMPeripheralSpec"},{"kind":"text","text":", "},{"text":"didReceiveCharacteristicsDiscoveryRequest","kind":"externalParam"},{"kind":"text","text":" "},{"text":"characteristicUUIDs","kind":"internalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID","kind":"typeIdentifier","text":"CBMUUID","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa"},{"kind":"text","text":"]?, "},{"text":"for","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"service"},{"text":": ","kind":"text"},{"text":"CBMServiceMock","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMServiceMock"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":">","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The target device."}]}],"name":"peripheral"},{"name":"characteristicUUIDs","content":[{"inlineContent":[{"type":"text","text":"Optional characteristics requested."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The parent service.","type":"text"}],"type":"paragraph"}],"name":"service"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Success, or a service discovery error. The error will be reported"},{"text":" ","type":"text"},{"type":"text","text":"using "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didDiscoverCharacteristicsFor:error:)-2pyjk","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"This method will be called when characteristic discovery was initiated using a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"mock central manager. When success is returned, the characteristics will be returned"},{"text":" ","type":"text"},{"text":"automatically based on the device specification.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didreceivecharacteristicsdiscoveryrequest:for:)-2doal"]}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate/peripheral(_:didReceiveDescriptorsDiscoveryRequestFor:)-6rk13":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveDescriptorsDiscoveryRequestFor:)-6rk13","kind":"symbol","abstract":[{"type":"text","text":"This method will be called when descriptor discovery was initiated using a"},{"type":"text","text":" "},{"type":"text","text":"mock central manager. When success is returned, the descriptors will be returned"},{"type":"text","text":" "},{"type":"text","text":"automatically based on the device specification."}],"title":"peripheral(_:didReceiveDescriptorsDiscoveryRequestFor:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CBMPeripheralSpec","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveDescriptorsDiscoveryRequestFor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristicMock","text":"CBMCharacteristicMock"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didreceivedescriptorsdiscoveryrequestfor:)-6rk13","type":"topic","required":true,"defaultImplementations":1},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate/peripheral(_:didReceiveIncludedServiceDiscoveryRequest:for:)-4mqk2":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveIncludedServiceDiscoveryRequest:for:)-4mqk2","kind":"symbol","abstract":[{"type":"text","text":"This method will be called when service discovery of included services was"},{"type":"text","text":" "},{"type":"text","text":"initiated using a mock central manager. When success is returned, the services"},{"type":"text","text":" "},{"text":"will be returned automatically based on the device specification.","type":"text"}],"title":"peripheral(_:didReceiveIncludedServiceDiscoveryRequest:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CBMPeripheralSpec","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC"},{"kind":"text","text":", "},{"text":"didReceiveIncludedServiceDiscoveryRequest","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","text":"CBMUUID","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CBMServiceMock","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMServiceMock","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":", ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didreceiveincludedservicediscoveryrequest:for:)-4mqk2","type":"topic","required":true,"defaultImplementations":1},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate/peripheral(_:didReceiveCharacteristicsDiscoveryRequest:for:)-2doal":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveCharacteristicsDiscoveryRequest:for:)-2doal","kind":"symbol","abstract":[{"text":"This method will be called when characteristic discovery was initiated using a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"mock central manager. When success is returned, the characteristics will be returned"},{"type":"text","text":" "},{"type":"text","text":"automatically based on the device specification."}],"title":"peripheral(_:didReceiveCharacteristicsDiscoveryRequest:for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"text":"CBMPeripheralSpec","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didReceiveCharacteristicsDiscoveryRequest","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"CBMUUID","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMServiceMock","text":"CBMServiceMock"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didreceivecharacteristicsdiscoveryrequest:for:)-2doal","type":"topic","required":true,"defaultImplementations":1},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec":{"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralspec","navigatorTitle":[{"text":"CBMPeripheralSpec","kind":"identifier"}],"title":"CBMPeripheralSpec","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPeripheralSpec","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Specification of a mock peripheral."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMUUID":{"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMUUID"}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmuuid","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID","title":"CBMUUID","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMUUID"}],"abstract":[{"text":"A universally unique identifier, as defined by Bluetooth standards.","type":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate":{"navigatorTitle":[{"text":"CBMPeripheralSpecDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"This delegate should implement the behavior of a real Bluetooth LE device during a connection."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheralSpecDelegate","kind":"identifier"}],"title":"CBMPeripheralSpecDelegate","type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate","url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegate/peripheral(_:didDiscoverCharacteristicsFor:error:)-2pyjk":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didDiscoverCharacteristicsFor:error:)-2pyjk","kind":"symbol","abstract":[{"type":"text","text":"This method returns the result of a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/discoverCharacteristics(_:for:)"},{"type":"text","text":" call."},{"type":"text","text":" "},{"text":"If the characteristic(s) were read successfully, they can be retrieved via service’s","type":"text"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService\/characteristics","isActive":true,"type":"reference"},{"type":"text","text":" property."}],"title":"peripheral(_:didDiscoverCharacteristicsFor:error:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didDiscoverCharacteristicsFor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CBMService","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegate\/peripheral(_:diddiscovercharacteristicsfor:error:)-2pyjk","type":"topic","required":true,"defaultImplementations":1},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMService":{"abstract":[{"text":"A collection of data and associated behaviors that accomplish a function or feature of a device.","type":"text"}],"kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmservice","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMService","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMService"}],"title":"CBMService","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate/peripheral(_:didReceiveServiceDiscoveryRequest:)-pq5f":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveServiceDiscoveryRequest:)-pq5f","kind":"symbol","abstract":[{"type":"text","text":"This method will be called when service discovery was initiated using a"},{"type":"text","text":" "},{"type":"text","text":"mock central manager. When success is returned, the services will be"},{"type":"text","text":" "},{"type":"text","text":"returned automatically based on the device specification."}],"title":"peripheral(_:didReceiveServiceDiscoveryRequest:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"text":"CBMPeripheralSpec","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveServiceDiscoveryRequest"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","text":"CBMUUID","kind":"typeIdentifier"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":">"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didreceiveservicediscoveryrequest:)-pq5f","type":"topic","required":true,"defaultImplementations":1},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMServiceMock":{"type":"topic","abstract":[{"type":"text","text":"Mock implementation of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock","role":"symbol","title":"CBMServiceMock","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMServiceMock"}],"navigatorTitle":[{"kind":"identifier","text":"CBMServiceMock"}],"url":"\/documentation\/corebluetoothmock\/cbmservicemock"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMService/characteristics":{"abstract":[{"type":"text","text":"A list of characteristics that have so far been discovered in this service."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"characteristics"},{"kind":"text","text":": ["},{"text":"CBMCharacteristic","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic"},{"text":"]?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService\/characteristics","url":"\/documentation\/corebluetoothmock\/cbmservice\/characteristics","type":"topic","title":"characteristics","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral/discoverCharacteristics(_:for:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/discoverCharacteristics(_:for:)","abstract":[{"type":"text","text":"Discovers the specified characteristics of a service."}],"url":"\/documentation\/corebluetoothmock\/cbmperipheral\/discovercharacteristics(_:for:)","required":true,"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"discoverCharacteristics"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","text":"CBMUUID","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService","text":"CBMService"},{"text":")","kind":"text"}],"title":"discoverCharacteristics(_:for:)","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate/peripheral(_:didReceiveCharacteristicsDiscoveryRequest:for:)-995x5":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveCharacteristicsDiscoveryRequest:for:)-995x5","kind":"symbol","abstract":[{"type":"text","text":"This method will be called when characteristic discovery was initiated using a"},{"type":"text","text":" "},{"type":"text","text":"mock central manager. When success is returned, the characteristics will be returned"},{"text":" ","type":"text"},{"type":"text","text":"automatically based on the device specification."}],"title":"peripheral(_:didReceiveCharacteristicsDiscoveryRequest:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC","text":"CBMPeripheralSpec"},{"text":", ","kind":"text"},{"text":"didReceiveCharacteristicsDiscoveryRequest","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"CBMUUID","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"CBMServiceMock","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMServiceMock","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":", ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didreceivecharacteristicsdiscoveryrequest:for:)-995x5","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/title","value":"CBMService"},{"op":"replace","value":[{"text":"CBMService","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBMService"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/title","value":"CBMServiceMock"},{"value":[{"text":"CBMServiceMock","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/navigatorTitle","value":[{"kind":"identifier","text":"CBMServiceMock"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}