{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"peripheral"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec","text":"CBMPeripheralSpec","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC"},{"text":", ","kind":"text"},{"text":"didReceiveIncludedServiceDiscoveryRequest","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"serviceUUIDs"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"CBMUUID","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID"},{"kind":"text","text":"]?, "},{"text":"for","kind":"externalParam"},{"kind":"text","text":" "},{"text":"service","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMServiceMock","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock","kind":"typeIdentifier","text":"CBMServiceMock"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"peripheral","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The target device."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional services requested."}]}],"name":"serviceUUIDs"},{"content":[{"inlineContent":[{"text":"The primary service.","type":"text"}],"type":"paragraph"}],"name":"service"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Success, or a service discovery error. The error will be reported","type":"text"},{"type":"text","text":" "},{"text":"using ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didDiscoverIncludedServicesFor:error:)-6b62q","isActive":true},{"type":"text","text":"."}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CBMPeripheralSpec","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC"},{"text":", ","kind":"text"},{"text":"didReceiveIncludedServiceDiscoveryRequest","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","text":"CBMUUID"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"CBMServiceMock","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMServiceMock"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol","modules":[{"name":"CoreBluetoothMock"}],"roleHeading":"Instance Method","extendedModule":"CoreBluetoothMock","title":"peripheral(_:didReceiveIncludedServiceDiscoveryRequest:for:)","externalID":"s:17CoreBluetoothMock25CBMPeripheralSpecDelegatePAAE10peripheral_41didReceiveIncludedServiceDiscoveryRequest3fors6ResultOyyts5Error_pGAA0dE0C_SaySo6CBUUIDCGSgAA010CBMServiceC0CtF"},"abstract":[{"type":"text","text":"This method will be called when service discovery of included services was"},{"type":"text","text":" "},{"text":"initiated using a mock central manager. When success is returned, the services","type":"text"},{"type":"text","text":" "},{"type":"text","text":"will be returned automatically based on the device specification."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveIncludedServiceDiscoveryRequest:for:)-4mqk2"]]},"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveIncludedServiceDiscoveryRequest:for:)-7iofs","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didreceiveincludedservicediscoveryrequest:for:)-7iofs"]}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec":{"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralspec","navigatorTitle":[{"text":"CBMPeripheralSpec","kind":"identifier"}],"title":"CBMPeripheralSpec","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPeripheralSpec","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Specification of a mock peripheral."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMService":{"abstract":[{"text":"A collection of data and associated behaviors that accomplish a function or feature of a device.","type":"text"}],"kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmservice","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMService","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMService"}],"title":"CBMService","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMService/includedServices":{"abstract":[{"type":"text","text":"A list of included services that have so far been discovered in this service."}],"title":"includedServices","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"includedServices","kind":"identifier"},{"text":": [","kind":"text"},{"text":"CBMService","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService"},{"text":"]?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService\/includedServices","url":"\/documentation\/corebluetoothmock\/cbmservice\/includedservices","type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate/peripheral(_:didReceiveIncludedServiceDiscoveryRequest:for:)-4mqk2":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveIncludedServiceDiscoveryRequest:for:)-4mqk2","kind":"symbol","abstract":[{"type":"text","text":"This method will be called when service discovery of included services was"},{"type":"text","text":" "},{"type":"text","text":"initiated using a mock central manager. When success is returned, the services"},{"type":"text","text":" "},{"text":"will be returned automatically based on the device specification.","type":"text"}],"title":"peripheral(_:didReceiveIncludedServiceDiscoveryRequest:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CBMPeripheralSpec","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC"},{"kind":"text","text":", "},{"text":"didReceiveIncludedServiceDiscoveryRequest","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","text":"CBMUUID","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CBMServiceMock","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMServiceMock","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":", ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didreceiveincludedservicediscoveryrequest:for:)-4mqk2","type":"topic","required":true,"defaultImplementations":1},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral/discoverIncludedServices(_:for:)":{"abstract":[{"text":"Discovers the specified included services of a previously-discovered service.","type":"text"}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheral\/discoverincludedservices(_:for:)","required":true,"kind":"symbol","title":"discoverIncludedServices(_:for:)","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/discoverIncludedServices(_:for:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"discoverIncludedServices","kind":"identifier"},{"text":"([","kind":"text"},{"text":"CBMUUID","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CBMService","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService"},{"text":")","kind":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMUUID":{"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMUUID"}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmuuid","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMUUID","title":"CBMUUID","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMUUID"}],"abstract":[{"text":"A universally unique identifier, as defined by Bluetooth standards.","type":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegate/peripheral(_:didDiscoverIncludedServicesFor:error:)-6b62q":{"abstract":[{"type":"text","text":"This method returns the result of a "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral\/discoverIncludedServices(_:for:)","isActive":true},{"text":" call.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If the included service(s) were read successfully, they can be retrieved via service’s"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService\/includedServices","isActive":true},{"text":" property.","type":"text"}],"title":"peripheral(_:didDiscoverIncludedServicesFor:error:)","kind":"symbol","role":"symbol","defaultImplementations":1,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didDiscoverIncludedServicesFor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService","text":"CBMService"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"required":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate\/peripheral(_:didDiscoverIncludedServicesFor:error:)-6b62q","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegate\/peripheral(_:diddiscoverincludedservicesfor:error:)-6b62q","type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate":{"navigatorTitle":[{"text":"CBMPeripheralSpecDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"This delegate should implement the behavior of a real Bluetooth LE device during a connection."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheralSpecDelegate","kind":"identifier"}],"title":"CBMPeripheralSpecDelegate","type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate","url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpecDelegate/peripheral(_:didReceiveIncludedServiceDiscoveryRequest:for:)-7iofs":{"kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheralspecdelegate\/peripheral(_:didreceiveincludedservicediscoveryrequest:for:)-7iofs","title":"peripheral(_:didReceiveIncludedServiceDiscoveryRequest:for:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"text":"CBMPeripheralSpec","preciseIdentifier":"s:17CoreBluetoothMock17CBMPeripheralSpecC","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveIncludedServiceDiscoveryRequest"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","kind":"typeIdentifier","text":"CBMUUID"},{"text":"]?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMServiceMock","text":"CBMServiceMock"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":">","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpecDelegate\/peripheral(_:didReceiveIncludedServiceDiscoveryRequest:for:)-7iofs","type":"topic","abstract":[{"text":"This method will be called when service discovery of included services was","type":"text"},{"type":"text","text":" "},{"text":"initiated using a mock central manager. When success is returned, the services","type":"text"},{"type":"text","text":" "},{"type":"text","text":"will be returned automatically based on the device specification."}],"role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMServiceMock":{"type":"topic","abstract":[{"type":"text","text":"Mock implementation of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock","role":"symbol","title":"CBMServiceMock","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMServiceMock"}],"navigatorTitle":[{"kind":"identifier","text":"CBMServiceMock"}],"url":"\/documentation\/corebluetoothmock\/cbmservicemock"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/title","value":"CBMService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/fragments","value":[{"kind":"identifier","text":"CBMService"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/navigatorTitle","value":[{"kind":"identifier","text":"CBMService"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/title","op":"replace","value":"CBMServiceMock"},{"op":"replace","value":[{"kind":"identifier","text":"CBMServiceMock"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/fragments"},{"value":[{"text":"CBMServiceMock","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/navigatorTitle","op":"replace"}]}]}