{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"centralManager"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","text":"CBMCentralManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didUpdateANCSAuthorizationFor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"text":")","kind":"text"}],"modules":[{"name":"CoreBluetoothMock"}],"extendedModule":"CoreBluetoothMock","symbolKind":"method","title":"centralManager(_:didUpdateANCSAuthorizationFor:)","externalID":"s:17CoreBluetoothMock25CBMCentralManagerDelegatePAAE07centralE0_29didUpdateANCSAuthorizationForyAA0dE0C_AA13CBMPeripheral_ptF::SYNTHESIZED::c:@M@CoreBluetoothMock@objc(cs)CBMCentralManagerDelegateProxy","role":"symbol","roleHeading":"Instance Method","platforms":[{"introducedAt":"13.0","unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"unavailable":false,"name":"iPadOS","introducedAt":"13.0","beta":false,"deprecated":false},{"introducedAt":"13.0","unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false}]},"kind":"symbol","abstract":[{"type":"text","text":"This method is invoked when the authorization status changes for a"},{"type":"text","text":" "},{"type":"text","text":"peripheral connected with "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/connect(_:options:)","type":"reference","isActive":true},{"type":"text","text":" "},{"text":"option ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionRequiresANCS"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy\/centralManager(_:didUpdateANCSAuthorizationFor:)-2ol7m","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"central","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CBMCentralManager","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didUpdateANCSAuthorizationFor","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CBMPeripheral","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"kind":"text","text":")"}]}]},{"parameters":[{"name":"central","content":[{"inlineContent":[{"text":"The central manager providing this information.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","isActive":true,"type":"reference"},{"type":"text","text":" that caused the event."}]}],"name":"peripheral"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"name":"Important","style":"important","content":[{"inlineContent":[{"type":"text","text":"This method is not implemented in mock central manager."}],"type":"paragraph"}],"type":"aside"}]}],"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegateproxy\/centralmanager(_:didupdateancsauthorizationfor:)-2ol7m"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy\/CBMCentralManagerDelegate-Implementations"]]},"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMConnectPeripheralOptionRequiresANCS":{"type":"topic","abstract":[{"text":"An option to require Apple Notification Center Service (ANCS) when connecting a device.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionRequiresANCS","role":"symbol","title":"CBMConnectPeripheralOptionRequiresANCS","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMConnectPeripheralOptionRequiresANCS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/corebluetoothmock\/cbmconnectperipheraloptionrequiresancs"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegateProxy/CBMCentralManagerDelegate-Implementations":{"kind":"article","title":"CBMCentralManagerDelegate Implementations","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegateproxy\/cbmcentralmanagerdelegate-implementations","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy\/CBMCentralManagerDelegate-Implementations","role":"collectionGroup"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegateProxy/centralManager(_:didUpdateANCSAuthorizationFor:)-2ol7m":{"abstract":[{"type":"text","text":"This method is invoked when the authorization status changes for a"},{"type":"text","text":" "},{"text":"peripheral connected with ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/connect(_:options:)"},{"type":"text","text":" "},{"type":"text","text":"option "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectPeripheralOptionRequiresANCS","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"topic","kind":"symbol","title":"centralManager(_:didUpdateANCSAuthorizationFor:)","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegateproxy\/centralmanager(_:didupdateancsauthorizationfor:)-2ol7m","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy\/centralManager(_:didUpdateANCSAuthorizationFor:)-2ol7m","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"centralManager"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","text":"CBMCentralManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateANCSAuthorizationFor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","text":"CBMPeripheral","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManager"}],"title":"CBMCentralManager","abstract":[{"type":"text","text":"An object that scans for, discovers, connects to, and manages peripherals."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManager"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager/connect(_:options:)":{"abstract":[{"text":"Establishes a local connection to a peripheral.","type":"text"}],"type":"topic","kind":"symbol","title":"connect(_:options:)","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager\/connect(_:options:)","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/connect(_:options:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connect"},{"text":"(","kind":"text"},{"text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?)","kind":"text"}],"role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegateProxy":{"abstract":[{"type":"text","text":"A helper class that allows setting delegate callbacks as closures."}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegateproxy","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy","title":"CBMCentralManagerDelegateProxy","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMCentralManagerDelegateProxy","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManagerDelegateProxy"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/title","value":"CBMCentralManager"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/fragments","value":[{"text":"CBMCentralManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/navigatorTitle","value":[{"text":"CBMCentralManager","kind":"identifier"}],"op":"replace"},{"value":"CBMCentralManagerDelegateProxy","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerDelegateProxy\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerDelegateProxy\/fragments","value":[{"kind":"identifier","text":"CBMCentralManagerDelegateProxy"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerDelegateProxy\/navigatorTitle","op":"replace","value":[{"text":"CBMCentralManagerDelegateProxy","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}