{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","title":"centralManager(_:connectionEventDidOccur:for:)","platforms":[{"deprecated":false,"beta":false,"introducedAt":"13.0","unavailable":false,"name":"iOS"},{"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"13.0","unavailable":false},{"introducedAt":"13.0","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false}],"extendedModule":"CoreBluetoothMock","externalID":"s:17CoreBluetoothMock25CBMCentralManagerDelegatePAAE07centralE0_23connectionEventDidOccur3foryAA0dE0C_So012CBConnectionI0VAA13CBMPeripheral_ptF::SYNTHESIZED::c:@M@CoreBluetoothMock@objc(cs)CBMCentralManagerDelegateProxy","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"centralManager","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","text":"CBMCentralManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"connectionEventDidOccur","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CBMConnectionEvent","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock18CBMConnectionEventa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","text":"CBMPeripheral","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","modules":[{"name":"CoreBluetoothMock"}],"roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy\/centralManager(_:connectionEventDidOccur:for:)-1g05k","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegateproxy\/centralmanager(_:connectioneventdidoccur:for:)-1g05k"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"abstract":[{"type":"text","text":"This method is invoked upon the connection or disconnection of a"},{"type":"text","text":" "},{"type":"text","text":"peripheral that matches any of the options provided in"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/registerForConnectionEvents(options:)","type":"reference","isActive":true},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"central","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","text":"CBMCentralManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"connectionEventDidOccur"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"text":": ","kind":"text"},{"text":"CBMConnectionEvent","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectionEvent","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock18CBMConnectionEventa"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"peripheral"},{"text":": ","kind":"text"},{"text":"CBMPeripheral","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"central","content":[{"type":"paragraph","inlineContent":[{"text":"The central manager providing this information.","type":"text"}]}]},{"name":"event","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectionEvent","isActive":true},{"type":"text","text":" that has occurred."}]}]},{"name":"peripheral","content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","isActive":true},{"type":"text","text":" that caused the event."}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy\/CBMCentralManagerDelegate-Implementations"]]},"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegateProxy":{"abstract":[{"type":"text","text":"A helper class that allows setting delegate callbacks as closures."}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegateproxy","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy","title":"CBMCentralManagerDelegateProxy","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMCentralManagerDelegateProxy","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManagerDelegateProxy"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegateProxy/CBMCentralManagerDelegate-Implementations":{"kind":"article","title":"CBMCentralManagerDelegate Implementations","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegateproxy\/cbmcentralmanagerdelegate-implementations","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy\/CBMCentralManagerDelegate-Implementations","role":"collectionGroup"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManager"}],"title":"CBMCentralManager","abstract":[{"type":"text","text":"An object that scans for, discovers, connects to, and manages peripherals."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManager"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegateProxy/centralManager(_:connectionEventDidOccur:for:)-1g05k":{"kind":"symbol","abstract":[{"type":"text","text":"This method is invoked upon the connection or disconnection of a"},{"text":" ","type":"text"},{"type":"text","text":"peripheral that matches any of the options provided in"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/registerForConnectionEvents(options:)"},{"text":".","type":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegateproxy\/centralmanager(_:connectioneventdidoccur:for:)-1g05k","title":"centralManager(_:connectionEventDidOccur:for:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"centralManager"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","text":"CBMCentralManager"},{"kind":"text","text":", "},{"text":"connectionEventDidOccur","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock18CBMConnectionEventa","text":"CBMConnectionEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","text":"CBMPeripheral"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy\/centralManager(_:connectionEventDidOccur:for:)-1g05k","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMConnectionEvent":{"abstract":[{"type":"text","text":"A change to the connection state of a peer."}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMConnectionEvent"}],"navigatorTitle":[{"text":"CBMConnectionEvent","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectionEvent","url":"\/documentation\/corebluetoothmock\/cbmconnectionevent","title":"CBMConnectionEvent","type":"topic","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager/registerForConnectionEvents(options:)":{"abstract":[{"type":"text","text":"Register for an event notification when the central manager makes a"},{"text":" ","type":"text"},{"text":"connection matching the given options.","type":"text"}],"type":"topic","role":"symbol","title":"registerForConnectionEvents(options:)","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/registerForConnectionEvents(options:)","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager\/registerforconnectionevents(options:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerForConnectionEvents","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"options"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock32CBMConnectionEventMatchingOptiona","text":"CBMConnectionEventMatchingOption"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"CBMCentralManagerDelegateProxy","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerDelegateProxy\/title"},{"value":[{"text":"CBMCentralManagerDelegateProxy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerDelegateProxy\/fragments"},{"value":[{"kind":"identifier","text":"CBMCentralManagerDelegateProxy"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerDelegateProxy\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/title","value":"CBMCentralManager","op":"replace"},{"value":[{"text":"CBMCentralManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/navigatorTitle","value":[{"text":"CBMCentralManager","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}