{"metadata":{"modules":[{"name":"CoreBluetoothMock"}],"externalID":"s:17CoreBluetoothMock17CBMPeripheralSpecC8servicesSayAA010CBMServiceC0CGSgvp","symbolKind":"property","role":"symbol","title":"services","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"services","kind":"identifier"},{"text":": [","kind":"text"},{"text":"CBMServiceMock","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMServiceMock"},{"text":"]?","kind":"text"}],"roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/services"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"services","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMServiceMock","text":"CBMServiceMock"},{"text":"]? { get }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmperipheralspec\/services"]}],"sections":[],"kind":"symbol","seeAlsoSections":[{"generated":true,"title":"Properties","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/name","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/mtu","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/advertisement","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/identifier","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/proximity","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/isConnected","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/connectionDelegate","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/connectionInterval","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/supervisionTimeout","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/isKnown"],"anchor":"Properties"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec"]]},"abstract":[{"type":"text","text":"List of services available for service discovery."}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMService":{"abstract":[{"text":"A collection of data and associated behaviors that accomplish a function or feature of a device.","type":"text"}],"kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmservice","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMService","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMService"}],"title":"CBMService","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec/supervisionTimeout":{"url":"\/documentation\/corebluetoothmock\/cbmperipheralspec\/supervisiontimeout","abstract":[{"type":"text","text":"The supervision timeout is a time after which a device realizes"},{"type":"text","text":" "},{"type":"text","text":"that a connected peer has disconnected, had there been no signal"},{"text":" ","type":"text"},{"text":"from it.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/supervisionTimeout","role":"symbol","title":"supervisionTimeout","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supervisionTimeout"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec/identifier":{"abstract":[{"text":"The peripheral identifier.","type":"text"}],"type":"topic","title":"identifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheralspec\/identifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/identifier","kind":"symbol","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMServiceMock":{"type":"topic","abstract":[{"type":"text","text":"Mock implementation of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock","role":"symbol","title":"CBMServiceMock","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMServiceMock"}],"navigatorTitle":[{"kind":"identifier","text":"CBMServiceMock"}],"url":"\/documentation\/corebluetoothmock\/cbmservicemock"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec/name":{"url":"\/documentation\/corebluetoothmock\/cbmperipheralspec\/name","abstract":[{"type":"text","text":"The name of the peripheral returned by Device Name characteristic."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/name","role":"symbol","title":"name","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec/isKnown":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/isKnown","title":"isKnown","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isKnown"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A flag indicating that the peripheral can be retrieved obtained using without scanning."}],"kind":"symbol","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralspec\/isknown"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec/connectionInterval":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/connectionInterval","title":"connectionInterval","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionInterval"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The connection interval."}],"kind":"symbol","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralspec\/connectioninterval"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec":{"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralspec","navigatorTitle":[{"text":"CBMPeripheralSpec","kind":"identifier"}],"title":"CBMPeripheralSpec","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPeripheralSpec","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Specification of a mock peripheral."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec/services":{"type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/services","title":"services","kind":"symbol","abstract":[{"type":"text","text":"List of services available for service discovery."}],"url":"\/documentation\/corebluetoothmock\/cbmperipheralspec\/services","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"services"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMServiceMock","text":"CBMServiceMock","kind":"typeIdentifier"},{"text":"]?","kind":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec/connectionDelegate":{"url":"\/documentation\/corebluetoothmock\/cbmperipheralspec\/connectiondelegate","kind":"symbol","abstract":[{"type":"text","text":"The delegate that will handle connection requests."}],"title":"connectionDelegate","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/connectionDelegate","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connectionDelegate"},{"kind":"text","text":": "},{"text":"CBMPeripheralSpecDelegate","preciseIdentifier":"s:17CoreBluetoothMock25CBMPeripheralSpecDelegateP","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec/mtu":{"url":"\/documentation\/corebluetoothmock\/cbmperipheralspec\/mtu","abstract":[{"type":"text","text":"The MTU (Maximum Transfer Unit)."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/mtu","role":"symbol","title":"mtu","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mtu"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec/advertisement":{"abstract":[{"type":"text","text":"Advertisement configurations of the peripheral."}],"type":"topic","title":"advertisement","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"advertisement"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"CBMAdvertisementConfig","preciseIdentifier":"s:17CoreBluetoothMock22CBMAdvertisementConfigV"},{"kind":"text","text":"]?"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/advertisement","url":"\/documentation\/corebluetoothmock\/cbmperipheralspec\/advertisement","kind":"symbol","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec/proximity":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/proximity","type":"topic","title":"proximity","kind":"symbol","abstract":[{"type":"text","text":"How far the device is."}],"url":"\/documentation\/corebluetoothmock\/cbmperipheralspec\/proximity","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"proximity"},{"kind":"text","text":": "},{"preciseIdentifier":"s:17CoreBluetoothMock12CBMProximityO","text":"CBMProximity","kind":"typeIdentifier"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec/isConnected":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/isConnected","title":"isConnected","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isConnected"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A flag indicating whether the device is connected."}],"kind":"symbol","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralspec\/isconnected"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/title","value":"CBMService"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMService"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/navigatorTitle","value":[{"text":"CBMService","kind":"identifier"}]},{"value":"CBMServiceMock","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/fragments","op":"replace","value":[{"text":"CBMServiceMock","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/navigatorTitle","value":[{"text":"CBMServiceMock","kind":"identifier"}]}]}]}