{"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"simulateServiceChange"},{"text":"(","kind":"text"},{"text":"newName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"newServices"},{"kind":"text","text":": ["},{"text":"CBMServiceMock","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMServiceMock","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"externalID":"s:17CoreBluetoothMock17CBMPeripheralSpecC21simulateServiceChange7newName0I8ServicesySSSg_SayAA010CBMServiceC0CGtF","role":"symbol","title":"simulateServiceChange(newName:newServices:)","modules":[{"name":"CoreBluetoothMock"}],"roleHeading":"Instance Method","symbolKind":"method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/simulateServiceChange(newName:newServices:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"simulateServiceChange","kind":"identifier"},{"kind":"text","text":"("},{"text":"newName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"newServices"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMServiceMock","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock","text":"CBMServiceMock"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The new device name after change."}]}],"name":"newName"},{"name":"newServices","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The new services after change."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"inlineContent":[{"text":"The device must be connectable, otherwise this method does","type":"text"},{"type":"text","text":" "},{"type":"text","text":"nothing."}],"type":"paragraph"},{"style":"important","name":"Important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"In the mock implementation the order of services","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"is irrelevant. This is in contrary to the physical"},{"text":" ","type":"text"},{"text":"Bluetooth LE device, where handle numbers depend","type":"text"},{"type":"text","text":" "},{"type":"text","text":"on order of the services in the attribute database."}]}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec"]]},"abstract":[{"type":"text","text":"Simulates a situation when the device changes its services."},{"text":" ","type":"text"},{"type":"text","text":"Only services that were not in the previous list of services"},{"text":" ","type":"text"},{"type":"text","text":"will be reported as invalidated."}],"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmperipheralspec\/simulateservicechange(newname:newservices:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/simulateConnection()","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/simulateCaching()","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/simulateMacChange(_:)"],"generated":true,"title":"Advanced","anchor":"Advanced"}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec":{"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralspec","navigatorTitle":[{"text":"CBMPeripheralSpec","kind":"identifier"}],"title":"CBMPeripheralSpec","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPeripheralSpec","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Specification of a mock peripheral."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMService":{"abstract":[{"text":"A collection of data and associated behaviors that accomplish a function or feature of a device.","type":"text"}],"kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmservice","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMService","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMService"}],"title":"CBMService","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMServiceMock":{"type":"topic","abstract":[{"type":"text","text":"Mock implementation of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock","role":"symbol","title":"CBMServiceMock","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMServiceMock"}],"navigatorTitle":[{"kind":"identifier","text":"CBMServiceMock"}],"url":"\/documentation\/corebluetoothmock\/cbmservicemock"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager/retrievePeripherals(withIdentifiers:)":{"kind":"symbol","abstract":[{"text":"Returns a list of known peripherals by their identifiers.","type":"text"}],"title":"retrievePeripherals(withIdentifiers:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"retrievePeripherals","kind":"identifier"},{"kind":"text","text":"("},{"text":"withIdentifiers","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":"]) -> [","kind":"text"},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"text":"]","kind":"text"}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager\/retrieveperipherals(withidentifiers:)","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/retrievePeripherals(withIdentifiers:)"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec/simulateMacChange(_:)":{"url":"\/documentation\/corebluetoothmock\/cbmperipheralspec\/simulatemacchange(_:)","abstract":[{"type":"text","text":"Simulates a change of the device’s MAC address."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/simulateMacChange(_:)","title":"simulateMacChange(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"simulateMacChange","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"kind":"text","text":")"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec/simulateServiceChange(newName:newServices:)":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/simulateServiceChange(newName:newServices:)","url":"\/documentation\/corebluetoothmock\/cbmperipheralspec\/simulateservicechange(newname:newservices:)","title":"simulateServiceChange(newName:newServices:)","abstract":[{"type":"text","text":"Simulates a situation when the device changes its services."},{"text":" ","type":"text"},{"type":"text","text":"Only services that were not in the previous list of services"},{"text":" ","type":"text"},{"type":"text","text":"will be reported as invalidated."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"simulateServiceChange"},{"kind":"text","text":"("},{"text":"newName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"newServices","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMServiceMock","text":"CBMServiceMock"},{"text":"])","kind":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec/simulateCaching()":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/simulateCaching()","url":"\/documentation\/corebluetoothmock\/cbmperipheralspec\/simulatecaching()","title":"simulateCaching()","abstract":[{"type":"text","text":"Simulates a situation when the iDevice scans for Bluetooth LE devices"},{"text":" ","type":"text"},{"type":"text","text":"and caches scanned results. Scanned devices become available for retrieval"},{"type":"text","text":" "},{"type":"text","text":"using "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/retrievePeripherals(withIdentifiers:)"},{"text":".","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"simulateCaching"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralSpec/simulateConnection()":{"url":"\/documentation\/corebluetoothmock\/cbmperipheralspec\/simulateconnection()","abstract":[{"text":"Simulates the situation when another application on the device","type":"text"},{"type":"text","text":" "},{"type":"text","text":"connects to the device."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralSpec\/simulateConnection()","title":"simulateConnection()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"simulateConnection","kind":"identifier"},{"kind":"text","text":"()"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/title","value":"CBMService"},{"value":[{"text":"CBMService","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/navigatorTitle","value":[{"text":"CBMService","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/title","value":"CBMServiceMock","op":"replace"},{"value":[{"text":"CBMServiceMock","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/navigatorTitle","value":[{"kind":"identifier","text":"CBMServiceMock"}]}]}]}