{"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock\/registerForConnectionEvents(options:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Register for an event notification when the central manager makes a"},{"type":"text","text":" "},{"text":"connection matching the given options.","type":"text"}],"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmcentralmanagermock\/registerforconnectionevents(options:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock"]]},"metadata":{"modules":[{"name":"CoreBluetoothMock"}],"role":"symbol","title":"registerForConnectionEvents(options:)","symbolKind":"method","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"13.0","name":"iOS"},{"beta":false,"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"13.0"},{"introducedAt":"13.0","deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"introducedAt":"13.0","unavailable":false,"deprecated":false,"name":"tvOS","beta":false},{"unavailable":false,"name":"watchOS","beta":false,"deprecated":false,"introducedAt":"6.0"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerForConnectionEvents","kind":"identifier"},{"kind":"text","text":"("},{"text":"options","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:17CoreBluetoothMock32CBMConnectionEventMatchingOptiona","text":"CBMConnectionEventMatchingOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"roleHeading":"Instance Method","externalID":"s:17CoreBluetoothMock017CBMCentralManagerC0C27registerForConnectionEvents7optionsySDySo31CBConnectionEventMatchingOptionaypGSg_tF"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerForConnectionEvents","kind":"identifier"},{"kind":"text","text":"("},{"text":"options","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectionEventMatchingOption","preciseIdentifier":"s:17CoreBluetoothMock32CBMConnectionEventMatchingOptiona","kind":"typeIdentifier","text":"CBMConnectionEventMatchingOption"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]? = nil)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"options","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A dictionary that specifies options for"},{"type":"text","text":" "},{"type":"text","text":"connection events. See Peripheral Connection"},{"text":" ","type":"text"},{"type":"text","text":"Options for a list of possible options."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"When the central manager makes a connection that matches the","type":"text"},{"type":"text","text":" "},{"text":"options, it calls the delegate’s","type":"text"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:connectionEventDidOccur:for:)-1ay8d","type":"reference","isActive":true},{"text":" method.","type":"text"}]}]}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerMock":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManagerMock"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagermock","abstract":[{"text":"Mock implementation of the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager"},{"type":"text","text":"."}],"title":"CBMCentralManagerMock","kind":"symbol","navigatorTitle":[{"text":"CBMCentralManagerMock","kind":"identifier"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManager"}],"title":"CBMCentralManager","abstract":[{"type":"text","text":"An object that scans for, discovers, connects to, and manages peripherals."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManager"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager/registerForConnectionEvents(options:)":{"abstract":[{"type":"text","text":"Register for an event notification when the central manager makes a"},{"text":" ","type":"text"},{"text":"connection matching the given options.","type":"text"}],"type":"topic","role":"symbol","title":"registerForConnectionEvents(options:)","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/registerForConnectionEvents(options:)","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager\/registerforconnectionevents(options:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerForConnectionEvents","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"options"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock32CBMConnectionEventMatchingOptiona","text":"CBMConnectionEventMatchingOption"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegate/centralManager(_:connectionEventDidOccur:for:)-1ay8d":{"defaultImplementations":1,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","kind":"typeIdentifier","text":"CBMCentralManager"},{"kind":"text","text":", "},{"text":"connectionEventDidOccur","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock18CBMConnectionEventa","text":"CBMConnectionEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP","text":"CBMPeripheral","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate\/centralmanager(_:connectioneventdidoccur:for:)-1ay8d","required":true,"abstract":[{"text":"This method is invoked upon the connection or disconnection of a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"peripheral that matches any of the options provided in"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/registerForConnectionEvents(options:)"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate\/centralManager(_:connectionEventDidOccur:for:)-1ay8d","title":"centralManager(_:connectionEventDidOccur:for:)"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerMock/registerForConnectionEvents(options:)":{"abstract":[{"text":"Register for an event notification when the central manager makes a","type":"text"},{"text":" ","type":"text"},{"text":"connection matching the given options.","type":"text"}],"title":"registerForConnectionEvents(options:)","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagermock\/registerforconnectionevents(options:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerForConnectionEvents"},{"text":"(","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock32CBMConnectionEventMatchingOptiona","text":"CBMConnectionEventMatchingOption","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock\/registerForConnectionEvents(options:)"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMConnectionEventMatchingOption":{"navigatorTitle":[{"kind":"identifier","text":"CBMConnectionEventMatchingOption"}],"abstract":[{"type":"text","text":"A set of options to use when registering for connection events."}],"type":"topic","role":"symbol","title":"CBMConnectionEventMatchingOption","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectionEventMatchingOption","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmconnectioneventmatchingoption","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMConnectionEventMatchingOption"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerMock\/title","value":"CBMCentralManagerMock"},{"value":[{"kind":"identifier","text":"CBMCentralManagerMock"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerMock\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerMock\/navigatorTitle","value":[{"text":"CBMCentralManagerMock","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/title","value":"CBMCentralManager"},{"value":[{"text":"CBMCentralManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/navigatorTitle","value":[{"kind":"identifier","text":"CBMCentralManager"}]}]}]}