{"abstract":[{"type":"text","text":"An option set of device-specific features."}],"metadata":{"externalID":"s:17CoreBluetoothMock17CBMCentralManagerC7Featurea","role":"symbol","platforms":[{"name":"iOS","introducedAt":"13.0","deprecated":false,"beta":false,"unavailable":false},{"unavailable":false,"introducedAt":"13.0","deprecated":false,"name":"iPadOS","beta":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"13.0","deprecated":false,"unavailable":false},{"unavailable":false,"beta":false,"introducedAt":"13.0","name":"tvOS","deprecated":false},{"deprecated":false,"name":"watchOS","beta":false,"introducedAt":"6.0","unavailable":false}],"title":"CBMCentralManager.Feature","roleHeading":"Type Alias","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"Feature","kind":"identifier"}],"symbolKind":"typealias","modules":[{"name":"CoreBluetoothMock"}],"navigatorTitle":[{"text":"Feature","kind":"identifier"}]},"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/Feature","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmcentralmanager\/feature"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Feature"},{"text":" = ","kind":"text"},{"text":"CBCentralManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CBCentralManager"},{"kind":"text","text":"."},{"text":"Feature","preciseIdentifier":"c:@E@CBCentralManagerFeature","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"seeAlsoSections":[{"title":"Inspecting Feature Support","generated":true,"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/supports(_:)"],"anchor":"Inspecting-Feature-Support"}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManager"}],"title":"CBMCentralManager","abstract":[{"type":"text","text":"An object that scans for, discovers, connects to, and manages peripherals."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManager"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager/supports(_:)":{"kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager\/supports(_:)","title":"supports(_:)","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/supports(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"supports","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","text":"CBMCentralManager","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Feature","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock17CBMCentralManagerC7Featurea"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Returns a Boolean that indicates whether the device supports a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"specific set of features."}],"role":"symbol","type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager/Feature":{"kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager\/feature","title":"CBMCentralManager.Feature","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/Feature","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Feature"}],"navigatorTitle":[{"kind":"identifier","text":"Feature"}],"abstract":[{"text":"An option set of device-specific features.","type":"text"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CBMCentralManager","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/fragments","op":"replace","value":[{"text":"CBMCentralManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/navigatorTitle","op":"replace","value":[{"text":"CBMCentralManager","kind":"identifier"}]}]}]}