{"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/init()","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/init(delegate:queue:)","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/init(delegate:queue:options:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/authorization-swift.property","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/isScanning","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/state"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/cancelPeripheralConnection(_:)","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/connect(_:options:)","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/registerForConnectionEvents(options:)","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/retrieveConnectedPeripherals(withServices:)","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/retrievePeripherals(withIdentifiers:)","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/scanForPeripherals(withServices:options:)","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/stopScan()"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true},{"title":"Type Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/authorization-swift.type.property"],"anchor":"Type-Properties"},{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/supports(_:)"],"title":"Type Methods","anchor":"Type-Methods","generated":true}],"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock"]]},"kind":"symbol","abstract":[{"type":"text","text":"An implementation  of "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","isActive":true,"type":"reference"},{"text":" that will proxy all the requests and responses","type":"text"},{"text":" ","type":"text"},{"text":"to the native ","type":"text"},{"code":"CBCentralManager","type":"codeVoice"},{"type":"text","text":" object."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManagerNative"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"inlineContent":[{"type":"text","text":"This manager can only interact with physical Bluetooth LE devices."}],"type":"paragraph"}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/objc(pl)NSObject","doc:\/\/org.cocoapods.CoreBluetoothMock\/s7CVarArgP","doc:\/\/org.cocoapods.CoreBluetoothMock\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.CoreBluetoothMock\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.CoreBluetoothMock\/SQ","doc:\/\/org.cocoapods.CoreBluetoothMock\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"sections":[],"seeAlsoSections":[{"title":"Central Manager","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerFactory","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerState","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerAuthorization"],"anchor":"Central-Manager","generated":true}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManagerNative"}],"externalID":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManagerNative","role":"symbol","title":"CBMCentralManagerNative","modules":[{"name":"CoreBluetoothMock"}],"navigatorTitle":[{"text":"CBMCentralManagerNative","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class"},"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmcentralmanagernative"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/corebluetoothmock\/cbmcentralmanagernative"]}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/s7CVarArgP"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/scanForPeripherals(withServices:options:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanForPeripherals","kind":"identifier"},{"kind":"text","text":"("},{"text":"withServices","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"CBMUUID","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa"},{"kind":"text","text":"]?, "},{"text":"options","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"abstract":[{"type":"text","text":"Scans for peripherals that are advertising services."}],"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/scanforperipherals(withservices:options:)","title":"scanForPeripherals(withServices:options:)","type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/scanForPeripherals(withServices:options:)"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerMock":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManagerMock"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagermock","abstract":[{"text":"Mock implementation of the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager"},{"type":"text","text":"."}],"title":"CBMCentralManagerMock","kind":"symbol","navigatorTitle":[{"text":"CBMCentralManagerMock","kind":"identifier"}]},"doc://org.cocoapods.CoreBluetoothMock/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/init(delegate:queue:options:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock25CBMCentralManagerDelegateP","kind":"typeIdentifier","text":"CBMCentralManagerDelegate"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"queue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue","text":"DispatchQueue"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}],"abstract":[],"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/init(delegate:queue:options:)","title":"init(delegate:queue:options:)","type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/init(delegate:queue:options:)"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/state":{"type":"topic","kind":"symbol","title":"state","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/state","abstract":[{"type":"text","text":"The current state of the manager, initially set to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerState\/unknown"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"state"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CBMManagerState","preciseIdentifier":"s:17CoreBluetoothMock15CBMManagerStateO"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/state"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative":{"kind":"symbol","abstract":[{"type":"text","text":"An implementation  of "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"reference","isActive":true},{"type":"text","text":" that will proxy all the requests and responses"},{"text":" ","type":"text"},{"type":"text","text":"to the native "},{"type":"codeVoice","code":"CBCentralManager"},{"text":" object.","type":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative","title":"CBMCentralManagerNative","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMCentralManagerNative","kind":"identifier"}],"navigatorTitle":[{"text":"CBMCentralManagerNative","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/authorization-swift.type.property":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authorization","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17CoreBluetoothMock23CBMManagerAuthorizationa","kind":"typeIdentifier","text":"CBMManagerAuthorization"}],"abstract":[{"type":"text","text":"The current authorization status for using Bluetooth."}],"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/authorization-swift.type.property","title":"authorization","type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/authorization-swift.type.property"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/authorization-swift.property":{"type":"topic","kind":"symbol","title":"authorization","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/authorization-swift.property","abstract":[{"type":"text","text":"The current authorization status for using Bluetooth."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"authorization","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CBMManagerAuthorization","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock23CBMManagerAuthorizationa"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/authorization-swift.property"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/connect(_:options:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connect","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Establishes a local connection to a peripheral."}],"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/connect(_:options:)","title":"connect(_:options:)","type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/connect(_:options:)"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/init(delegate:queue:)":{"type":"topic","kind":"symbol","title":"init(delegate:queue:)","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/init(delegate:queue:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock25CBMCentralManagerDelegateP","text":"CBMCentralManagerDelegate"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"queue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue","text":"DispatchQueue"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/init(delegate:queue:)"},"doc://org.cocoapods.CoreBluetoothMock/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/registerForConnectionEvents(options:)":{"title":"registerForConnectionEvents(options:)","role":"symbol","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/registerforconnectionevents(options:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerForConnectionEvents"},{"text":"(","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"CBMConnectionEventMatchingOption","preciseIdentifier":"s:17CoreBluetoothMock32CBMConnectionEventMatchingOptiona","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}],"type":"topic","abstract":[{"type":"text","text":"Register for an event notification when the central manager makes a"},{"type":"text","text":" "},{"text":"connection matching the given options.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/registerForConnectionEvents(options:)"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/retrievePeripherals(withIdentifiers:)":{"type":"topic","kind":"symbol","title":"retrievePeripherals(withIdentifiers:)","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/retrieveperipherals(withidentifiers:)","abstract":[{"type":"text","text":"Returns a list of known peripherals by their identifiers."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"retrievePeripherals"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withIdentifiers"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"kind":"text","text":"]) -> ["},{"kind":"typeIdentifier","text":"CBMPeripheral","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/retrievePeripherals(withIdentifiers:)"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManager"}],"title":"CBMCentralManager","abstract":[{"type":"text","text":"An object that scans for, discovers, connects to, and manages peripherals."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManager"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegateProxy":{"abstract":[{"type":"text","text":"A helper class that allows setting delegate callbacks as closures."}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegateproxy","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy","title":"CBMCentralManagerDelegateProxy","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMCentralManagerDelegateProxy","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManagerDelegateProxy"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/SH","type":"unresolvable"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/isScanning":{"type":"topic","navigatorTitle":[{"text":"isScanning","kind":"identifier"}],"kind":"symbol","title":"isScanning","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/isscanning","abstract":[{"text":"Whether or not the central is currently scanning.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isScanning"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/isScanning"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/retrieveConnectedPeripherals(withServices:)":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/retrieveConnectedPeripherals(withServices:)","type":"topic","role":"symbol","abstract":[{"text":"Returns a list of the peripherals connected to the system whose","type":"text"},{"type":"text","text":" "},{"type":"text","text":"services match a given set of criteria."}],"title":"retrieveConnectedPeripherals(withServices:)","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/retrieveconnectedperipherals(withservices:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveConnectedPeripherals"},{"kind":"text","text":"("},{"text":"withServices","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"CBMUUID","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa"},{"text":"]) -> [","kind":"text"},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMManagerState":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerState","navigatorTitle":[{"text":"CBMManagerState","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The possible states of a Core Bluetooth manager."}],"title":"CBMManagerState","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMManagerState","kind":"identifier"}],"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmmanagerstate"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerFactory":{"kind":"symbol","abstract":[{"text":"The factory that instantiates the ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","isActive":true,"type":"reference"},{"text":" object.","type":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerfactory","title":"CBMCentralManagerFactory","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMCentralManagerFactory","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMCentralManagerFactory"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerFactory","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/cancelPeripheralConnection(_:)":{"type":"topic","kind":"symbol","title":"cancelPeripheralConnection(_:)","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/cancelperipheralconnection(_:)","abstract":[{"type":"text","text":"Cancels an active or pending local connection to a peripheral."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelPeripheralConnection"},{"kind":"text","text":"("},{"text":"CBMPeripheral","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock13CBMPeripheralP"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/cancelPeripheralConnection(_:)"},"doc://org.cocoapods.CoreBluetoothMock/SQ":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/supports(_:)":{"type":"topic","kind":"symbol","title":"supports(_:)","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/supports(_:)","abstract":[{"type":"text","text":"Returns a Boolean that indicates whether the device supports a"},{"text":" ","type":"text"},{"type":"text","text":"specific set of features."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"supports"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","text":"CBMCentralManager"},{"kind":"text","text":"."},{"text":"Feature","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock17CBMCentralManagerC7Featurea"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/supports(_:)"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/init()":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/init()","title":"init()","type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/init()"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegate":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManagerDelegate"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate","navigatorTitle":[{"text":"CBMCentralManagerDelegate","kind":"identifier"}],"title":"CBMCentralManagerDelegate","kind":"symbol","abstract":[{"type":"text","text":"A protocol that provides updates for the discovery and management of peripheral devices."}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMManagerState/unknown":{"abstract":[{"text":"The manager’s state is unknown.","type":"text"}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmmanagerstate\/unknown","kind":"symbol","title":"CBMManagerState.unknown","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerState\/unknown","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative/stopScan()":{"type":"topic","kind":"symbol","title":"stopScan()","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative\/stopscan()","abstract":[{"type":"text","text":"Asks the central manager to stop scanning for peripherals."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopScan","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/stopScan()"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMManagerAuthorization":{"title":"CBMManagerAuthorization","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerAuthorization","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMManagerAuthorization","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMManagerAuthorization"}],"url":"\/documentation\/corebluetoothmock\/cbmmanagerauthorization","abstract":[{"text":"The current authorization state of a Core Bluetooth manager.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"CBMCentralManagerNative","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"CBMCentralManagerNative"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CBMCentralManagerNative"}]},{"value":[{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative\/isScanning"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager"],"kind":"relationships"}],"path":"\/relationshipsSections"},{"value":[{"title":"Central Manager","anchor":"Central-Manager","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"CBMCentralManagerNative","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCentralManager","text":"CBMCentralManager"}]}],"kind":"declarations"}},{"value":"CBMCentralManagerMock","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerMock\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerMock\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMCentralManagerMock"}]},{"value":[{"text":"CBMCentralManagerMock","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerMock\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/title","value":"CBMCentralManagerNative","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"CBMCentralManagerNative"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CBMCentralManagerNative"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/title","op":"replace","value":"CBMCentralManager"},{"value":[{"text":"CBMCentralManager","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"CBMCentralManager"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerDelegateProxy\/title","op":"replace","value":"CBMCentralManagerDelegateProxy"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerDelegateProxy\/fragments","value":[{"text":"CBMCentralManagerDelegateProxy","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerDelegateProxy\/navigatorTitle","op":"replace","value":[{"text":"CBMCentralManagerDelegateProxy","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative~1isScanning\/title","value":"isScanning","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative~1isScanning\/fragments","value":[{"kind":"identifier","text":"isScanning"}],"op":"replace"}]}]}