{"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/registerForConnectionEvents(options:)","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectionEvent"],"generated":true,"title":"Receiving Connection Events","anchor":"Receiving-Connection-Events"}],"sections":[],"abstract":[{"text":"A set of options to use when registering for connection events.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMConnectionEventMatchingOption","kind":"identifier"},{"text":" = ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CBConnectionEventMatchingOption","text":"CBConnectionEventMatchingOption"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectionEventMatchingOption"},"kind":"symbol","metadata":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMConnectionEventMatchingOption"}],"externalID":"s:17CoreBluetoothMock32CBMConnectionEventMatchingOptiona","roleHeading":"Type Alias","modules":[{"name":"CoreBluetoothMock"}],"navigatorTitle":[{"kind":"identifier","text":"CBMConnectionEventMatchingOption"}],"symbolKind":"typealias","role":"symbol","title":"CBMConnectionEventMatchingOption"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmconnectioneventmatchingoption"]}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMConnectionEvent":{"abstract":[{"type":"text","text":"A change to the connection state of a peer."}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMConnectionEvent"}],"navigatorTitle":[{"text":"CBMConnectionEvent","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectionEvent","url":"\/documentation\/corebluetoothmock\/cbmconnectionevent","title":"CBMConnectionEvent","type":"topic","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager/registerForConnectionEvents(options:)":{"abstract":[{"type":"text","text":"Register for an event notification when the central manager makes a"},{"text":" ","type":"text"},{"text":"connection matching the given options.","type":"text"}],"type":"topic","role":"symbol","title":"registerForConnectionEvents(options:)","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager\/registerForConnectionEvents(options:)","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager\/registerforconnectionevents(options:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerForConnectionEvents","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"options"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock32CBMConnectionEventMatchingOptiona","text":"CBMConnectionEventMatchingOption"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMConnectionEventMatchingOption":{"navigatorTitle":[{"kind":"identifier","text":"CBMConnectionEventMatchingOption"}],"abstract":[{"type":"text","text":"A set of options to use when registering for connection events."}],"type":"topic","role":"symbol","title":"CBMConnectionEventMatchingOption","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMConnectionEventMatchingOption","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmconnectioneventmatchingoption","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMConnectionEventMatchingOption"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManager"}],"title":"CBMCentralManager","abstract":[{"type":"text","text":"An object that scans for, discovers, connects to, and manages peripherals."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManager"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CBMCentralManager","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/title","op":"replace"},{"op":"replace","value":[{"text":"CBMCentralManager","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/navigatorTitle","value":[{"kind":"identifier","text":"CBMCentralManager"}],"op":"replace"}]}]}