{"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor"],"title":"Inherits From"},{"title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMClientCharacteristicConfigurationDescriptorMock"],"type":"inheritedBy"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/objc(pl)NSObject","doc:\/\/org.cocoapods.CoreBluetoothMock\/s7CVarArgP","doc:\/\/org.cocoapods.CoreBluetoothMock\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.CoreBluetoothMock\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.CoreBluetoothMock\/SQ","doc:\/\/org.cocoapods.CoreBluetoothMock\/SH"],"type":"conformsTo"}],"sections":[],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptorMock\/init(type:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptorMock\/isEqual(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptorMock"},"seeAlsoSections":[{"title":"Attributes","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAttribute","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicWriteType","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicProperties","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMClientCharacteristicConfigurationDescriptorMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCCCDescriptorMock"],"anchor":"Attributes","generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CBMDescriptorMock","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"CBMDescriptorMock","symbolKind":"class","externalID":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptorMock","modules":[{"name":"CoreBluetoothMock"}],"roleHeading":"Class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMDescriptorMock","kind":"identifier"}],"navigatorTitle":[{"text":"CBMDescriptorMock","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmdescriptormock"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/corebluetoothmock\/cbmdescriptormock"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock"]]},"abstract":[{"text":"Mock implementation of ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor","isActive":true,"type":"reference"},{"type":"text","text":"."}],"references":{"doc://org.cocoapods.CoreBluetoothMock/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.CoreBluetoothMock/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMService":{"abstract":[{"text":"A collection of data and associated behaviors that accomplish a function or feature of a device.","type":"text"}],"kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmservice","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMService","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMService"}],"title":"CBMService","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristic":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMCharacteristic"}],"title":"CBMCharacteristic","type":"topic","abstract":[{"text":"A characteristic of a remote peripheral’s service.","type":"text"}],"navigatorTitle":[{"text":"CBMCharacteristic","kind":"identifier"}],"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmcharacteristic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMDescriptorMock/isEqual(_:)":{"abstract":[],"title":"isEqual(_:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptorMock\/isEqual(_:)","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmdescriptormock\/isequal(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCCCDescriptorMock":{"url":"\/documentation\/corebluetoothmock\/cbmcccdescriptormock","abstract":[{"text":"A type alias of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMClientCharacteristicConfigurationDescriptorMock"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCCCDescriptorMock","title":"CBMCCCDescriptorMock","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMCCCDescriptorMock"}],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMCCCDescriptorMock"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMClientCharacteristicConfigurationDescriptorMock":{"url":"\/documentation\/corebluetoothmock\/cbmclientcharacteristicconfigurationdescriptormock","abstract":[{"text":"A mock implementation of Client Characteristic Configuration descriptor (CCCD).","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMClientCharacteristicConfigurationDescriptorMock","title":"CBMClientCharacteristicConfigurationDescriptorMock","kind":"symbol","navigatorTitle":[{"text":"CBMClientCharacteristicConfigurationDescriptorMock","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMClientCharacteristicConfigurationDescriptorMock"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMDescriptorMock/init(type:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa","text":"CBMUUID"},{"kind":"text","text":")"}],"url":"\/documentation\/corebluetoothmock\/cbmdescriptormock\/init(type:)","abstract":[],"title":"init(type:)","type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptorMock\/init(type:)","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMDescriptorMock":{"type":"topic","abstract":[{"text":"Mock implementation of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptorMock","role":"symbol","title":"CBMDescriptorMock","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMDescriptorMock","kind":"identifier"}],"navigatorTitle":[{"text":"CBMDescriptorMock","kind":"identifier"}],"url":"\/documentation\/corebluetoothmock\/cbmdescriptormock"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMServiceMock":{"type":"topic","abstract":[{"type":"text","text":"Mock implementation of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock","role":"symbol","title":"CBMServiceMock","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMServiceMock"}],"navigatorTitle":[{"kind":"identifier","text":"CBMServiceMock"}],"url":"\/documentation\/corebluetoothmock\/cbmservicemock"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMDescriptor":{"role":"symbol","title":"CBMDescriptor","abstract":[{"text":"An object that provides further information about a remote peripheral’s characteristic.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmdescriptor","navigatorTitle":[{"kind":"identifier","text":"CBMDescriptor"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMDescriptor","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMAttribute":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAttribute","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMAttribute","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBMAttribute"}],"title":"CBMAttribute","url":"\/documentation\/corebluetoothmock\/cbmattribute","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A representation of common aspects of services offered by a peripheral."}]},"doc://org.cocoapods.CoreBluetoothMock/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.CoreBluetoothMock/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristicMock":{"url":"\/documentation\/corebluetoothmock\/cbmcharacteristicmock","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CBMCharacteristicMock","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMCharacteristicMock"}],"abstract":[{"type":"text","text":"Mock implementation of "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic","type":"reference","isActive":true},{"type":"text","text":"."}],"title":"CBMCharacteristicMock","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicMock","type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristicWriteType":{"title":"CBMCharacteristicWriteType","url":"\/documentation\/corebluetoothmock\/cbmcharacteristicwritetype","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicWriteType","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCharacteristicWriteType"}],"abstract":[{"type":"text","text":"Values representing the possible write types to a characteristic’s value."}],"navigatorTitle":[{"kind":"identifier","text":"CBMCharacteristicWriteType"}],"kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCharacteristicProperties":{"url":"\/documentation\/corebluetoothmock\/cbmcharacteristicproperties","abstract":[{"text":"Values that represent the possible properties of a characteristic.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicProperties","kind":"symbol","title":"CBMCharacteristicProperties","navigatorTitle":[{"kind":"identifier","text":"CBMCharacteristicProperties"}],"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"CBMCharacteristicProperties","kind":"identifier"}]},"doc://org.cocoapods.CoreBluetoothMock/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/s7CVarArgP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"CBMDescriptorMock","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"CBMDescriptorMock","kind":"identifier"}],"op":"replace"},{"value":[{"text":"CBMDescriptorMock","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptorMock\/isEqual(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor"]},{"type":"inheritedBy","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMClientCharacteristicConfigurationDescriptorMock"],"title":"Inherited By"}]},{"path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMAttribute","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMService","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMServiceMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristic","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCharacteristicMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMClientCharacteristicConfigurationDescriptorMock"],"title":"Attributes","anchor":"Attributes"}],"op":"replace"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMDescriptorMock"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"CBMDescriptor","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptor","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMDescriptor"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/title","op":"replace","value":"CBMService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/fragments","value":[{"text":"CBMService","kind":"identifier"}]},{"value":[{"text":"CBMService","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMService\/navigatorTitle"},{"value":"CBMCharacteristic","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/title"},{"value":[{"text":"CBMCharacteristic","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristic\/navigatorTitle","op":"replace","value":[{"text":"CBMCharacteristic","kind":"identifier"}]},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptorMock~1isEqual(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptorMock~1isEqual(_:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMClientCharacteristicConfigurationDescriptorMock\/title","value":"CBMClientCharacteristicConfigurationDescriptorMock","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMClientCharacteristicConfigurationDescriptorMock\/fragments","value":[{"text":"CBMClientCharacteristicConfigurationDescriptorMock","kind":"identifier"}]},{"value":[{"text":"CBMClientCharacteristicConfigurationDescriptorMock","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMClientCharacteristicConfigurationDescriptorMock\/navigatorTitle"},{"op":"replace","value":"CBMDescriptorMock","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptorMock\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptorMock\/fragments","value":[{"kind":"identifier","text":"CBMDescriptorMock"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptorMock\/navigatorTitle","value":[{"text":"CBMDescriptorMock","kind":"identifier"}]},{"value":"CBMServiceMock","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CBMServiceMock"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CBMServiceMock"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMServiceMock\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/title","value":"CBMDescriptor","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/fragments","value":[{"kind":"identifier","text":"CBMDescriptor"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMDescriptor\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBMDescriptor"}]},{"op":"replace","value":"CBMAttribute","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMAttribute\/title"},{"op":"replace","value":[{"text":"CBMAttribute","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMAttribute\/fragments"},{"value":[{"kind":"identifier","text":"CBMAttribute"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMAttribute\/navigatorTitle"},{"value":"CBMCharacteristicMock","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristicMock\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristicMock\/fragments","value":[{"text":"CBMCharacteristicMock","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCharacteristicMock\/navigatorTitle","value":[{"text":"CBMCharacteristicMock","kind":"identifier"}],"op":"replace"}]}]}