{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock"]]},"seeAlsoSections":[{"title":"Central Manager","generated":true,"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerFactory","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerState"],"anchor":"Central-Manager"}],"variants":[{"paths":["\/documentation\/corebluetoothmock\/cbmmanagerauthorization"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerAuthorization","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"CBMManagerAuthorization"}],"platforms":[{"name":"iOS","introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"13.0"},{"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"13.0","deprecated":false},{"deprecated":false,"introducedAt":"10.15","beta":false,"unavailable":false,"name":"macOS"},{"name":"tvOS","introducedAt":"13.0","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"6.0","unavailable":false,"deprecated":false,"name":"watchOS","beta":false}],"externalID":"s:17CoreBluetoothMock23CBMManagerAuthorizationa","modules":[{"name":"CoreBluetoothMock"}],"title":"CBMManagerAuthorization","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMManagerAuthorization","kind":"identifier"}],"role":"symbol","symbolKind":"typealias","roleHeading":"Type Alias"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMManagerAuthorization"},{"kind":"text","text":" = "},{"kind":"typeIdentifier","text":"CBManagerAuthorization","preciseIdentifier":"c:@E@CBManagerAuthorization"}],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The current authorization state of a Core Bluetooth manager."}],"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMManagerState":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerState","navigatorTitle":[{"text":"CBMManagerState","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The possible states of a Core Bluetooth manager."}],"title":"CBMManagerState","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMManagerState","kind":"identifier"}],"role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmmanagerstate"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegateProxy":{"abstract":[{"type":"text","text":"A helper class that allows setting delegate callbacks as closures."}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegateproxy","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegateProxy","title":"CBMCentralManagerDelegateProxy","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMCentralManagerDelegateProxy","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManagerDelegateProxy"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManager"}],"title":"CBMCentralManager","abstract":[{"type":"text","text":"An object that scans for, discovers, connects to, and manages peripherals."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManager"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerFactory":{"kind":"symbol","abstract":[{"text":"The factory that instantiates the ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","isActive":true,"type":"reference"},{"text":" object.","type":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerfactory","title":"CBMCentralManagerFactory","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMCentralManagerFactory","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMCentralManagerFactory"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerFactory","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerDelegate":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManagerDelegate"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagerdelegate","navigatorTitle":[{"text":"CBMCentralManagerDelegate","kind":"identifier"}],"title":"CBMCentralManagerDelegate","kind":"symbol","abstract":[{"type":"text","text":"A protocol that provides updates for the discovery and management of peripheral devices."}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMManagerAuthorization":{"title":"CBMManagerAuthorization","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMManagerAuthorization","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMManagerAuthorization","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMManagerAuthorization"}],"url":"\/documentation\/corebluetoothmock\/cbmmanagerauthorization","abstract":[{"text":"The current authorization state of a Core Bluetooth manager.","type":"text"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerMock":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerMock","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManagerMock"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagermock","abstract":[{"text":"Mock implementation of the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager"},{"type":"text","text":"."}],"title":"CBMCentralManagerMock","kind":"symbol","navigatorTitle":[{"text":"CBMCentralManagerMock","kind":"identifier"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative":{"kind":"symbol","abstract":[{"type":"text","text":"An implementation  of "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"reference","isActive":true},{"type":"text","text":" that will proxy all the requests and responses"},{"text":" ","type":"text"},{"type":"text","text":"to the native "},{"type":"codeVoice","code":"CBCentralManager"},{"text":" object.","type":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative","title":"CBMCentralManagerNative","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMCentralManagerNative","kind":"identifier"}],"navigatorTitle":[{"text":"CBMCentralManagerNative","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CBMCentralManagerDelegateProxy","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerDelegateProxy\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerDelegateProxy\/fragments","value":[{"text":"CBMCentralManagerDelegateProxy","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerDelegateProxy\/navigatorTitle","value":[{"kind":"identifier","text":"CBMCentralManagerDelegateProxy"}],"op":"replace"},{"op":"replace","value":"CBMCentralManager","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/title"},{"value":[{"text":"CBMCentralManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/fragments"},{"value":[{"kind":"identifier","text":"CBMCentralManager"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerMock\/title","op":"replace","value":"CBMCentralManagerMock"},{"value":[{"kind":"identifier","text":"CBMCentralManagerMock"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerMock\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CBMCentralManagerMock"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerMock\/navigatorTitle"},{"op":"replace","value":"CBMCentralManagerNative","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/fragments","value":[{"text":"CBMCentralManagerNative","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/navigatorTitle","op":"replace","value":[{"text":"CBMCentralManagerNative","kind":"identifier"}]}]}]}