{"kind":"symbol","abstract":[{"type":"text","text":"A native implementation of "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","isActive":true},{"type":"text","text":" that will proxy all requests to an underlying "},{"type":"codeVoice","code":"CBPeripheral"},{"text":".","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/ancsAuthorized","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/canSendWriteWithoutResponse","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/debugDescription","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/delegate","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/hash","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/identifier","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/name","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/peripheral","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/services","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/state"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/discoverCharacteristics(_:for:)","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/discoverDescriptors(for:)","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/discoverIncludedServices(_:for:)","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/discoverServices(_:)","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/maximumWriteValueLength(for:)","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/openL2CAPChannel(_:)","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/readRSSI()","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/readValue(for:)-65lsz","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/readValue(for:)-b1qu","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/setNotifyValue(_:for:)","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/writeValue(_:for:)","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/writeValue(_:for:type:)"],"title":"Instance Methods"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeer"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","doc:\/\/org.cocoapods.CoreBluetoothMock\/objc(pl)NSObject","doc:\/\/org.cocoapods.CoreBluetoothMock\/s7CVarArgP","doc:\/\/org.cocoapods.CoreBluetoothMock\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.CoreBluetoothMock\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.CoreBluetoothMock\/SQ","doc:\/\/org.cocoapods.CoreBluetoothMock\/SH"]}],"metadata":{"title":"CBMPeripheralNative","roleHeading":"Class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralNative"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMPeripheralNative"}],"symbolKind":"class","modules":[{"name":"CoreBluetoothMock"}],"externalID":"c:@M@CoreBluetoothMock@objc(cs)CBMPeripheralNative"},"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeer","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxyWithL2CAPChannel","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralPreview","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralState","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBML2CAPPSM","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBML2CAPChannel"],"title":"Peripheral","anchor":"Peripheral","generated":true}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMPeripheralNative"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"inlineContent":[{"text":"This implementation will be used when creating peripherals by ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative"},{"type":"text","text":"."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Unless required, this class should not be accessed directly, but rather by the common protocol "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","isActive":true},{"type":"text","text":"."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/corebluetoothmock\/cbmperipheralnative"]},{"paths":["\/documentation\/corebluetoothmock\/cbmperipheralnative"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock"]]},"references":{"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheral":{"role":"symbol","title":"CBMPeripheral","abstract":[{"type":"text","text":"A remote peripheral device."}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheral","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheral"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheral","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/maximumWriteValueLength(for:)":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/maximumWriteValueLength(for:)","kind":"symbol","type":"topic","title":"maximumWriteValueLength(for:)","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/maximumwritevaluelength(for:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximumWriteValueLength","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CBMCharacteristicWriteType","preciseIdentifier":"s:17CoreBluetoothMock26CBMCharacteristicWriteTypea"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The maximum amount of data, in bytes, you can send to a characteristic in a single write type."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/ancsAuthorized":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ancsAuthorized","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/ancsAuthorized","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"A Boolean value that indicates if the remote device has authorization to receive data over ANCS protocol.","type":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/ancsauthorized","title":"ancsAuthorized"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralPreview":{"url":"\/documentation\/corebluetoothmock\/cbmperipheralpreview","title":"CBMPeripheralPreview","abstract":[{"text":"A stub ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","isActive":true},{"text":" implementation designed only for SwiftUI Previews.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPeripheralPreview","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralPreview","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralPreview"}],"role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralState":{"url":"\/documentation\/corebluetoothmock\/cbmperipheralstate","title":"CBMPeripheralState","abstract":[{"type":"text","text":"Values representing the connection state of a peripheral."}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPeripheralState","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralState","navigatorTitle":[{"text":"CBMPeripheralState","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/debugDescription":{"url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/debugdescription","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugDescription"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"debugDescription","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"debugDescription","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/debugDescription","type":"topic","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegate":{"type":"topic","title":"CBMPeripheralDelegate","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CBMPeripheralDelegate","kind":"identifier"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegate","abstract":[{"type":"text","text":"A protocol that provides updates on the use of a peripheral’s services."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralDelegate"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/discoverIncludedServices(_:for:)":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/discoverIncludedServices(_:for:)","kind":"symbol","type":"topic","title":"discoverIncludedServices(_:for:)","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/discoverincludedservices(_:for:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"discoverIncludedServices"},{"text":"([","kind":"text"},{"text":"CBMUUID","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa"},{"kind":"text","text":"]?, "},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBMService","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Discovers the specified included services of a previously-discovered service."}]},"doc://org.cocoapods.CoreBluetoothMock/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegateProxyWithL2CAPChannel":{"navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralDelegateProxyWithL2CAPChannel"}],"kind":"symbol","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxywithl2capchannel","abstract":[{"text":"A helper class that allows setting delegate callbacks as closures.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPeripheralDelegateProxyWithL2CAPChannel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxyWithL2CAPChannel","title":"CBMPeripheralDelegateProxyWithL2CAPChannel","type":"topic"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/name":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/name","abstract":[{"text":"The name of the peripheral.","type":"text"}],"kind":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/name","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"name"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/discoverCharacteristics(_:for:)":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/discoverCharacteristics(_:for:)","kind":"symbol","type":"topic","title":"discoverCharacteristics(_:for:)","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/discovercharacteristics(_:for:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"discoverCharacteristics","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"CBMUUID","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa"},{"text":"]?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService","text":"CBMService","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Discovers the specified characteristics of a service."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/writeValue(_:for:type:)":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/writeValue(_:for:type:)","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/writevalue(_:for:type:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Writes the value of a characteristic."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"writeValue"},{"text":"(","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBMCharacteristic","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CBMCharacteristicWriteType","preciseIdentifier":"s:17CoreBluetoothMock26CBMCharacteristicWriteTypea"},{"kind":"text","text":")"}],"title":"writeValue(_:for:type:)","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/readValue(for:)-b1qu":{"title":"readValue(for:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/readValue(for:)-b1qu","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/readvalue(for:)-b1qu","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"readValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBMCharacteristic","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Retrieves the value of a specified characteristic."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/readValue(for:)-65lsz":{"kind":"symbol","title":"readValue(for:)","abstract":[{"text":"Retrieves the value of a specified characteristic descriptor.","type":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/readvalue(for:)-65lsz","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/readValue(for:)-65lsz","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"readValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptor","text":"CBMDescriptor"},{"text":")","kind":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/identifier":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/identifier","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/identifier","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The unique, persistent identifier associated with the peer."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"}],"title":"identifier","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/canSendWriteWithoutResponse":{"title":"canSendWriteWithoutResponse","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/canSendWriteWithoutResponse","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/cansendwritewithoutresponse","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canSendWriteWithoutResponse","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"A Boolean value that indicates whether the remote device can send a write without a response.","type":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeer":{"navigatorTitle":[{"text":"CBMPeer","kind":"identifier"}],"url":"\/documentation\/corebluetoothmock\/cbmpeer","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPeer","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that represents a remote device."}],"title":"CBMPeer","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeer"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/peripheral":{"title":"peripheral","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/peripheral","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/peripheral","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"text":": ","kind":"text"},{"text":"CBPeripheral","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CBPeripheral"}],"abstract":[]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/setNotifyValue(_:for:)":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/setNotifyValue(_:for:)","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/setnotifyvalue(_:for:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Sets notifications or indications for the value of a specified characteristic."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setNotifyValue"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CBMCharacteristic","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic"},{"text":")","kind":"text"}],"title":"setNotifyValue(_:for:)","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManagerNative":{"kind":"symbol","abstract":[{"type":"text","text":"An implementation  of "},{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"reference","isActive":true},{"type":"text","text":" that will proxy all the requests and responses"},{"text":" ","type":"text"},{"type":"text","text":"to the native "},{"type":"codeVoice","code":"CBCentralManager"},{"text":" object.","type":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmcentralmanagernative","title":"CBMCentralManagerNative","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMCentralManagerNative","kind":"identifier"}],"navigatorTitle":[{"text":"CBMCentralManagerNative","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManagerNative","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/SQ":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBML2CAPChannel":{"navigatorTitle":[{"kind":"identifier","text":"CBML2CAPChannel"}],"url":"\/documentation\/corebluetoothmock\/cbml2capchannel","kind":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBML2CAPChannel","kind":"identifier"}],"abstract":[{"text":"A live L2CAP connection to a remote device.","type":"text"}],"title":"CBML2CAPChannel","role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBML2CAPChannel"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/writeValue(_:for:)":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/writeValue(_:for:)","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/writevalue(_:for:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Writes the value of a characteristic descriptor."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"writeValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"CBMDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMDescriptor"},{"text":")","kind":"text"}],"title":"writeValue(_:for:)","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBML2CAPPSM":{"url":"\/documentation\/corebluetoothmock\/cbml2cappsm","title":"CBML2CAPPSM","abstract":[{"type":"text","text":"The type of PSM identifiers."}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBML2CAPPSM","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBML2CAPPSM","navigatorTitle":[{"kind":"identifier","text":"CBML2CAPPSM"}],"role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/openL2CAPChannel(_:)":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/openL2CAPChannel(_:)","kind":"symbol","type":"topic","title":"openL2CAPChannel(_:)","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/openl2capchannel(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"openL2CAPChannel"},{"text":"(","kind":"text"},{"text":"CBML2CAPPSM","preciseIdentifier":"s:17CoreBluetoothMock11CBML2CAPPSMa","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Attempts to open an L2CAP channel to the peripheral using the supplied Protocol\/Service Multiplexer (PSM)."}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/discoverDescriptors(for:)":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/discoverDescriptors(for:)","type":"topic","abstract":[{"text":"Discovers the descriptors of a characteristic.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"discoverDescriptors"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBMCharacteristic","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMCharacteristic"},{"text":")","kind":"text"}],"kind":"symbol","title":"discoverDescriptors(for:)","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/discoverdescriptors(for:)","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralDelegateProxy":{"title":"CBMPeripheralDelegateProxy","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy","kind":"symbol","abstract":[{"type":"text","text":"A helper class that allows setting delegate callbacks as closures."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}],"type":"topic","role":"symbol","url":"\/documentation\/corebluetoothmock\/cbmperipheraldelegateproxy","navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralDelegateProxy"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative":{"abstract":[{"type":"text","text":"A native implementation of "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","type":"reference"},{"text":" that will proxy all requests to an underlying ","type":"text"},{"code":"CBPeripheral","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CBMPeripheralNative","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMPeripheralNative"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative","type":"topic","title":"CBMPeripheralNative","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/state":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/state","kind":"symbol","role":"symbol","title":"state","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/state","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CBMPeripheralState","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock18CBMPeripheralStatea"}],"abstract":[{"text":"The connection state of the peripheral.","type":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/services":{"type":"topic","title":"services","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/services","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"services"},{"text":": [","kind":"text"},{"text":"CBMService","kind":"typeIdentifier","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMService"},{"text":"]?","kind":"text"}],"url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/services","abstract":[{"text":"A list of a peripheral’s discovered services.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMCentralManager"}],"title":"CBMCentralManager","abstract":[{"type":"text","text":"An object that scans for, discovers, connects to, and manages peripherals."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMCentralManager","type":"topic","url":"\/documentation\/corebluetoothmock\/cbmcentralmanager","navigatorTitle":[{"kind":"identifier","text":"CBMCentralManager"}]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/hash":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/hash","kind":"symbol","type":"topic","title":"hash","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/hash","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"abstract":[]},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/readRSSI()":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Retrieves the current RSSI value for the peripheral while connected to the central manager.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/readRSSI()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"readRSSI"},{"kind":"text","text":"()"}],"title":"readRSSI()","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/readrssi()"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock","url":"\/documentation\/corebluetoothmock","type":"topic","kind":"symbol","abstract":[{"text":"Test ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"CoreBluetooth"}]},{"text":" features in your app using mocks.","type":"text"}],"title":"CoreBluetoothMock","role":"collection"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/discoverServices(_:)":{"identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/discoverServices(_:)","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/discoverservices(_:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Discovers the specified services of the peripheral."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"discoverServices","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"CBMUUID","preciseIdentifier":"s:17CoreBluetoothMock7CBMUUIDa"},{"text":"]?)","kind":"text"}],"title":"discoverServices(_:)","role":"symbol"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralNative/delegate":{"title":"delegate","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/delegate","url":"\/documentation\/corebluetoothmock\/cbmperipheralnative\/delegate","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CBMPeripheralDelegate","kind":"typeIdentifier","preciseIdentifier":"s:17CoreBluetoothMock21CBMPeripheralDelegateP"},{"kind":"text","text":"?"}],"abstract":[{"text":"The delegate object specified to receive peripheral events.","type":"text"}]},"doc://org.cocoapods.CoreBluetoothMock/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/objc(pl)NSObject"},"doc://org.cocoapods.CoreBluetoothMock/documentation/CoreBluetoothMock/CBMPeripheralMock":{"abstract":[{"type":"text","text":"Mock implementation of the "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheral","isActive":true},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/corebluetoothmock\/cbmperipheralmock","kind":"symbol","title":"CBMPeripheralMock","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock","navigatorTitle":[{"text":"CBMPeripheralMock","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMPeripheralMock"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"CBMPeripheralNative","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"CBMPeripheralNative","kind":"identifier"}]},{"op":"replace","value":[{"text":"CBMPeripheralNative","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/debugDescription","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralNative\/hash"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeer"],"type":"inheritsFrom","title":"Inherits From"}]},{"value":[{"title":"Peripheral","anchor":"Peripheral","identifiers":["doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeer","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxy","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralDelegateProxyWithL2CAPChannel","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralMock","doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeripheralPreview"],"generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMPeripheralNative","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"CBMPeer","preciseIdentifier":"c:@M@CoreBluetoothMock@objc(cs)CBMPeer","identifier":"doc:\/\/org.cocoapods.CoreBluetoothMock\/documentation\/CoreBluetoothMock\/CBMPeer"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralPreview\/title","value":"CBMPeripheralPreview","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"CBMPeripheralPreview"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralPreview\/fragments"},{"op":"replace","value":[{"text":"CBMPeripheralPreview","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralPreview\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative~1debugDescription\/title","value":"debugDescription","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative~1debugDescription\/fragments","op":"replace","value":[{"text":"debugDescription","kind":"identifier"}]},{"value":"CBMPeripheralDelegateProxyWithL2CAPChannel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxyWithL2CAPChannel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxyWithL2CAPChannel\/fragments","value":[{"kind":"identifier","text":"CBMPeripheralDelegateProxyWithL2CAPChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxyWithL2CAPChannel\/navigatorTitle","value":[{"text":"CBMPeripheralDelegateProxyWithL2CAPChannel","kind":"identifier"}]},{"value":"CBMPeer","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeer\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeer\/fragments","value":[{"text":"CBMPeer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeer\/navigatorTitle","value":[{"text":"CBMPeer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/title","op":"replace","value":"CBMCentralManagerNative"},{"value":[{"kind":"identifier","text":"CBMCentralManagerNative"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CBMCentralManagerNative"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManagerNative\/navigatorTitle"},{"value":"CBMPeripheralDelegateProxy","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/fragments","value":[{"text":"CBMPeripheralDelegateProxy","kind":"identifier"}],"op":"replace"},{"value":[{"text":"CBMPeripheralDelegateProxy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralDelegateProxy\/navigatorTitle"},{"value":"CBMPeripheralNative","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative\/fragments","op":"replace","value":[{"text":"CBMPeripheralNative","kind":"identifier"}]},{"value":[{"text":"CBMPeripheralNative","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/title","value":"CBMCentralManager"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/fragments","value":[{"kind":"identifier","text":"CBMCentralManager"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMCentralManager\/navigatorTitle","value":[{"text":"CBMCentralManager","kind":"identifier"}]},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative~1hash\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralNative~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock\/title","value":"CBMPeripheralMock"},{"value":[{"text":"CBMPeripheralMock","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.CoreBluetoothMock~1documentation~1CoreBluetoothMock~1CBMPeripheralMock\/navigatorTitle","value":[{"text":"CBMPeripheralMock","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}